### ISSUE TITLE
Support for as many predefined variables as possible

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#10]
https://docs.gitlab.com/ee/ci/variables/predefined_variables.html

**Comment by bcouetil** [comment]
@firecow thanks for already providing that many Gitlab variables !

I still miss these, for now calculated or added to `variables.yml`. By the way, very nice way of handling Gitlab's multiple variables source 👏 

- CI_SERVER_HOST
- CI_API_V4_URL
- CI_MERGE_REQUEST_IID
- CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
- CI_MERGE_REQUEST_TARGET_BRANCH_NAME
- CI_PROJECT_PATH
- CI_MERGE_REQUEST_PROJECT_URL: $CI_PROJECT_URL/-/merge_requests/1
- CI_PROJECT_PATH: $CI_PROJECT_PATH_SLUG

Last one is a bug when the project is on a group of projects, `CI_PROJECT_PATH` should be `group/project` and `CI_PROJECT_PATH_SLUG` `group-project`, but `CI_PROJECT_PATH_SLUG` is actually `group/project`

**Comment by firecow** [comment]
@bcouetil https://github.com/firecow/gitlab-ci-local/commit/2c99a1299153e5d38370864aee463c72b92b3931
This is what you ment, right ?

**Comment by bcouetil** [comment]
CI_SERVER_HOST is really only the host (without https). Consequently, no need to illustrate with 443 (but you can keep it if you like).

**Comment by firecow** [comment]
Right, here it is https://github.com/firecow/gitlab-ci-local/commit/3324c69b46b4179f5aa942603182d927e9e5120a

**Comment by bcouetil** [comment]
Thats it, thanks 🙏
