### ISSUE TITLE
CI_COMMIT_SHORT_SHA is not always 8 characters

### ISSUE THREAD

**Issue by peterbbeu** [firecow/gitlab-ci-local#1003]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
hello-world:
  stage: build
  script:
    - |
     echo "${CI_COMMIT_SHORT_SHA} (length: ${#CI_COMMIT_SHORT_SHA})"
```

**Expected behavior**
https://gitlab.com/petervv/gitlab-ci-test/-/jobs/5326992572

**Host information**
Ubuntu 22.04
gitlab-ci-local 4.44.0

**Containerd binary**
n/a

**Additional context**
[As per the docs](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html), `CI_COMMIT_SHORT_SHA` should always be length 8. I've seen both 7 and 9 in other gitlab-ci-local runs, this is what actually triggered me to report this bug.

Here's a minimum reproducible repository: https://github.com/peterbbeu/gitlab-ci-local-testcase/tree/5d89ce7e323c708d132e74aa4ec596a72ae314d4

Here is the associated pipeline that demonstrates it: https://github.com/peterbbeu/gitlab-ci-local-testcase/actions/runs/6571309679/job/17850211765#step:7:8

In that run, it happens to have a length of 7:
```
parsing and downloads finished in 61 ms
hello-world starting shell (build)
hello-world > $ echo "${CI_COMMIT_SHORT_SHA} (length: ${#CI_COMMIT_SHORT_SHA})" # collapsed multi-line command
hello-world > 5d89ce7 (length: 7)
hello-world finished in 15 ms

 PASS  hello-world
pipeline finished in 212 ms
```

**Comment by firecow** [comment]
We are literally using the output from `git rev-parse --short HEAD`

https://github.com/firecow/gitlab-ci-local/blob/master/src/git-data.ts#L52

**Comment by peterbbeu** [comment]
Created a PR, hopefully it suffices
