### ISSUE TITLE
Multiple volumes

### ISSUE THREAD

**Issue by klimonoid** [firecow/gitlab-ci-local#1010]
**Is your feature request related to a problem? Please describe.**
I am developing a pipeline which is similar to docker-swarm-php example. The difference is in volumes. In addition to docker socket I want to mount shared directory. With this I want to fix the next problem: I am unable to mount file/directory created inside of pipeline to docker container that I run inside of pipeline. For example a config file or .env file. I found this solution [here](https://gitlab.com/gitlab-org/gitlab-foss/-/issues/41227#note_260000211). On my build server I have gitlab runner configured in similar way and I want to be able to duplicate this configuration in gitlab-ci-local:
```
...
volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/shared:/shared"]
...
```

**Describe the solution you'd like**
It will be very cool to be able to mount multiple volumes to the gitlab-local-ci. For example to be able to specify them in .gitlab-ci-local-env as follows:
```
VOLUME="/var/run/docker.sock:/var/run/docker.sock, /shared:/shared"
```
or something like that.

**Describe alternatives you've considered**
I also think that my problem can be solved in different way. I am not good in making pipelines, so maybe I am missing something and I could solve this problem in different way. 

**Additional context**

**Comment by firecow** [comment]
Try with spaces

VOLUME="/var/run/docker.sock:/var/run/docker.sock /something/:/app/"

**Comment by firecow** [comment]
@klimonoid Any luck?

**Comment by klimonoid** [comment]
I'll try this on monday. Thank you very much

**Comment by firecow** [comment]
I'm sure it will work. Just reopen if it doesn't.
