### ISSUE TITLE
Alternate .gitlab-ci.yml name/path

### ISSUE THREAD

**Issue by bcouetil** [firecow/gitlab-ci-local#104]
# Love 

Thank you very much for this great tool, that will help me a lot with a few more features 🥰

# Request

## Description

There is no way to provide an alternate `.gitlab-ci.yml` file. This is crucial while some feature are missing, having a `.local.gitlab-ci.yml` as workaround.

`--cwd` could handle a filename, or we could have a `--yml path/to/alternate-gitlab-ci.yml`

# Workaround

## Description

rename the file before and after debugging session

## Impact

- ✅ low : needs actions once before/after a debugging session
- medium : fixed using another top level .gitlab-ci.yml
- high : needs deep refactoring, everywhere in templates or everytime or both

**Comment by firecow** [comment]
@bcouetil Isn't this feature already present via the --file option ?

**Comment by bcouetil** [comment]
Oh yes thanks ! I looked on an old version or overlooked... closing
