### ISSUE TITLE
before_script, script and after_script can be strings

### ISSUE THREAD

**Issue by hverlin** [firecow/gitlab-ci-local#1043]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
test-job:
  before_script: echo "Before test"
  script: echo "Test something"
  after_script: echo "After something"
```

**Expected behavior**
[example job logs](https://gitlab.com/hverlin/gitlab-ci-local-tests/-/jobs/5593774386)

**Host information**
Ubuntu
gitlab-ci-local 4.1.33

**Containerd binary**
Docker

**Additional context**
The spec indicates this it should be an array. However, the implementation seems to support plain strings:
https://docs.gitlab.com/ee/ci/yaml/#before_script

The example for scripts shows a plain string being used:
https://docs.gitlab.com/ee/ci/yaml/#script
![image](https://github.com/firecow/gitlab-ci-local/assets/9151470/c752beb5-dfe5-4799-a30c-a53e4ee3fe2a)

![image](https://github.com/firecow/gitlab-ci-local/assets/9151470/05c1be16-f475-453f-8ca8-bd8f7b574cd6)

Currently, `gitlab-ci-local` crashes with the following error:
```
    TypeError: job.beforeScripts.forEach is not a function

      74 |         for (const job of jobs) {
      75 |             if (job.trigger) continue;
    > 76 |             job.beforeScripts.forEach((s: any) => assert(typeof s === "string", chalk`{blue ${job.name}} before_script contains non string value`));
         |                               ^
      77 |             job.afterScripts.forEach((s: any) => assert(typeof s === "string", chalk`{blue ${job.name}} after_script contains non string value`));
      78 |             job.scripts.forEach((s: any) => assert(typeof s === "string", chalk`{blue ${job.name}} script contains non string value`));
      79 |         }
```

**Comment by hverlin** [comment]
@firecow Would it be possible to release a new version? Or otherwise, do you know when a new one will be available?

**Comment by firecow** [comment]
I'll make a release during the weekend @hverlin 👍

**Comment by hverlin** [comment]
Thanks!
