### ISSUE TITLE
Failing to wait for services to start on MacOS Sonoma

### ISSUE THREAD

**Issue by earthiverse** [firecow/gitlab-ci-local#1053]
I'm getting this error: `docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "mockserver:1080": executable file not found in $PATH: unknown.`

Command:
```shell
gitlab-ci-local --concurrency=1 test:small
```

Output:
```
parsing and downloads finished in 53 ms
test:small                                        starting php:7.1-alpine (test)
test:small                                        copied to docker volumes in 750 ms
test:small                                        started service image: mockserver/mockserver:latest with aliases: mockserver-mockserver, mockserver__mockserver, mockserver in 240 ms
test:small                                        service image: mockserver/mockserver:latest healthcheck failed
test:small                                          Command failed with exit code 127: docker run --rm --name=gcl-wait-for-it-260001-0-1080 --network gitlab-ci-local-260001 docker.io/sumina46/wait-for-it mockserver:1080 -t 30
test:small                                          docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "mockserver:1080": executable file not found in $PATH: unknown.
test:small                                        also see (/Users/earthiverse/Sites/mockserver/.gitlab-ci-local/services-output/testOgsmall/mockserver/mockserver:latest-0.log)
test:small                                        $ return 0
test:small                                        finished in 2.16 s

 PASS  test:small  
 ```
 
 /Users/earthiverse/Sites/mockserver/.gitlab-ci-local/services-output/testOgsmall/mockserver/mockserver:latest-0.log
 ```
 ### stdout ###

### stderr ###

 ```

**Minimal .gitlab-ci.yml illustrating the issue**
```yml
test:minimal:
  image: php:7.1-alpine
  services:
    - name: mockserver/mockserver:latest
      alias: mockserver
  script:
    - return 0
```

**Expected behavior**
No errors

**Host information**
macOS Sonoma 14.1.2 (Apple Silicon M1 Pro)
gitlab-ci-local 4.45.2

**Comment by firecow** [comment]
Can you provide a Dockerfile for this "mockserver". So I can reproduce.

**Comment by earthiverse** [comment]
> Can you provide a Dockerfile for this "mockserver". So I can reproduce.

I believe this is the one https://github.com/mock-server/mockserver/blob/mockserver-5.15.0/docker/Dockerfile
I'm pulling the service from https://hub.docker.com/r/mockserver/mockserver

**Comment by avoidik** [comment]
wait-for-it.sh script uses bash but there is not bash in the base image of https://hub.docker.com/r/sumina46/wait-for-it/tags

**Comment by firecow** [comment]
So wait a minute, your example isn't working on gitlab.com with "real" runners?

**Comment by earthiverse** [comment]
> So wait a minute, your example isn't working on gitlab.com with "real" runners?

No, it works on my GitLab CI without issues. There aren't any errors in the CI logs.

**Comment by avoidik** [comment]
@firecow I was unable to find a maintainer of the original docker image, here is a commit caused the issue https://github.com/firecow/gitlab-ci-local/commit/90a3d3bab3ebf9778e32a32a0a31a5705160ba8b perhaps @lisn0 can help?

**Comment by lisn0** [comment]
Just fixed the Docker image. I sincerely apologize! Should work now. Let me know if you run into any more problems. Thanks for the heads up!
