### ISSUE TITLE
Handle yaml anchors

### ISSUE THREAD

**Issue by bcouetil** [firecow/gitlab-ci-local#107]
# Love 

Thank you very much for this great tool, that will help me a lot with a few more features 🥰

# Request

## Description

Gitlab CI does not allow fine grained layering of script : just 2 layers, before_script/script.

If we want more, we can use one-line yaml anchors :

```
.get-version: &get-version
  - export VERSION=$(cat VERSION.txt) && echo "$VERSION"

.build-gke-image:
  before_script:
    [...]
    - *get-version
    [...]
  script:
    [...]
```

## Symptom

`script.split is not a function`

# Workaround

## Description

replace every yaml anchors with actual content

## Impact

- low : needs actions once before/after a debugging session
- medium : fixed using another top level .gitlab-ci.yml
- ✅ high : needs deep refactoring, everywhere in templates or everytime or both

**Comment by firecow** [comment]
I'm using the js-yaml package, this might be because I don't support multilevel script listing. 
I shall investigate.

**Comment by firecow** [comment]
https://github.com/firecow/gitlab-ci-local/pull/113 multidimension script is coming @bcouetil
