### ISSUE TITLE
Graceful stop or docker containers clean

### ISSUE THREAD

**Issue by bcouetil** [firecow/gitlab-ci-local#108]
# Love 

Thank you very much for this great tool, that will help me a lot with a few more features 🥰

# Request

## Description

When we stop the process with Ctrl+C, containers are still there. It would be nice to have a command to interrupt in a clean way. And maybe name containers with some prefix, and on next launch the process would recognize an clean the mess if any.

## Symptom

Lots of stopped, and sometimes running, containers

# Workaround

## Description

stop containers (if some are still running) and prune.

## Impact

- ✅ low : needs actions once before/after a debugging session
- medium : fixed using another top level .gitlab-ci.yml
- high : needs deep refactoring, everywhere in templates or everytime or both

**Comment by firecow** [comment]
Can you provide a list of container names that are kept alive, after you do a CTRL-C please.

**Comment by bcouetil** [comment]
They are up while there are performing the jobs task, then stop :

```
➜  ~ docker ps -a                                                                 (customer_dev/default)
CONTAINER ID   IMAGE                COMMAND                   CREATED          STATUS                     PORTS     NAMES
80340c8dbd6c   maven:3.6.3-jdk-11   "/usr/local/bin/mvn-…"    16 seconds ago   Exited (0) 5 seconds ago             quizzical_wu
f610844b60df   maven:3.6.3-jdk-11   "/usr/local/bin/mvn-…"    16 seconds ago   Up 8 seconds                         stoic_faraday
54d551892edc   ruby:2.7.1-alpine    "sh -c '\nif [ -x /us…"   16 seconds ago   Exited (0) 7 seconds ago             interesting_margulis
➜  ~ docker ps -a                                                                                                                                                                           (customer_dev/default)
CONTAINER ID   IMAGE                COMMAND                   CREATED          STATUS                      PORTS     NAMES
80340c8dbd6c   maven:3.6.3-jdk-11   "/usr/local/bin/mvn-…"    37 seconds ago   Exited (0) 27 seconds ago             quizzical_wu
f610844b60df   maven:3.6.3-jdk-11   "/usr/local/bin/mvn-…"    37 seconds ago   Exited (0) 16 seconds ago             stoic_faraday
54d551892edc   ruby:2.7.1-alpine    "sh -c '\nif [ -x /us…"   37 seconds ago   Exited (0) 29 seconds ago             interesting_margulis
```

**Comment by firecow** [comment]
Aah, I see.
I shall catch the CTRL+C and docker rm -f all container ids known too gitlab-ci-local @bcouetil

**Comment by bcouetil** [comment]
Yes that would be nice, thanks.

**Comment by firecow** [comment]
https://github.com/firecow/gitlab-ci-local/pull/111 It has been done. Closing this issue @bcouetil

**Comment by bcouetil** [comment]
You rock :heart:
