### ISSUE TITLE
Support .gitlab-ci.yaml (RFC 9512)

### ISSUE THREAD

**Issue by ioggstream** [firecow/gitlab-ci-local#1128]
**Expected behavior**

Look for .gitlab-ci.yaml since `.yaml` is the preferred extension according to RFC 9512 https://www.rfc-editor.org/rfc/rfc9512.html

**Host information**
Ubuntu
gitlab-ci-local 4.1.33

**Containerd binary**
docker

**Additional context**

YAML media type registration establishes security and interoperability considerations for yaml content.

**Comment by firecow** [comment]
Does Gitlab find files with `yaml` extension?

**Comment by firecow** [comment]
![image](https://github.com/firecow/gitlab-ci-local/assets/973602/e4d9e28b-dadd-4b16-b390-94ab75ade3f4)

![image](https://github.com/firecow/gitlab-ci-local/assets/973602/531557cd-7c97-4d27-a7a2-f7427d228c7a)

Notice how no pipeline was spawned for the "Tralalalala" commit.

Use the `--file .gitlab-ci.yaml` cli option, 

or set an environment variable on your terminal

```sh
export GCL_FILE=.gitlab-ci.yaml
```

**Comment by firecow** [comment]
![image](https://github.com/firecow/gitlab-ci-local/assets/973602/bc2190cb-96f0-4529-b7a7-4e4bb8c67d0f)

You can change it in your project settings, which I'm guessing you have done.
