### ISSUE TITLE
setting the docker container MAC address

### ISSUE THREAD

**Issue by sh-cau** [firecow/gitlab-ci-local#1144]
**Is your feature request related to a problem? Please describe.**
I want to pass additional options, that is to say, especially setting the MAC address, of the docker container like I would with, e.g., 
```
gitlab-runner exec docker --docker-mac-address=AA:BB:CC:DD:EE:FF <JOB_NAME>
```
**Describe the solution you'd like**
I would like to achieve the above equivalent like so
```
gitlab-ci-local --docker-mac-addres=AA:BB:CC:DD:EE:FF <JOB_NAME>
```

**Describe alternatives you've considered**
I tried manipulating the `--container-executable`, i.e., 
```
gitlab-ci-local --container-executable="docker run --mac-address=AA:BB:CC:DD:EE:FF"
```
and
```
gitlab-ci-local --container-executable="docker --mac-address=AA:BB:CC:DD:EE:FF"
```
to no avail.

**Additional context**
I need this feature since the docker container runs a MATLAB instance, the license of which is linked to a fixed MAC address.

Thank you!

**Comment by ANGkeith** [comment]
hmm, if we support this, how do you run this via the gitlab runnner? 

have you tried the following,

hacky way, which requires `--privileged` flag
```bash
job:
  image: bash
  script:
    - ifconfig eth0 hw ether "AA:BB:CC:DD:EE:FF"
    - ip a show eth0
```
![image](https://github.com/firecow/gitlab-ci-local/assets/28011783/c9a36459-0507-4b02-a73c-28827f67a530)

**Comment by sh-cau** [comment]
The actual gitlab runner is registered using `gitlab-runner register --docker-mac-address AA:BB:CC:DD:EE:FF ...`, which writes the mac address in the `config.toml` of the gitlab runner much like described in your second reference. Unfortunately, `gitlab-runner exec` [ignores this configuration](https://gitlab.com/gitlab-org/gitlab/-/issues/216301) entirely. 

You solution works, however, this requires me to adjust the `.gitlab-ci.yaml` everytime I want to test locally and this, in fact, is the reason I quit using `gitlab-runner exec` because with that you can't pass CI-specific environment variables, say, `CI_JOB_TOKEN` or `CI_PIPELINE_SOURCE`, which also leads to me having to rename for the testing time.
