### ISSUE TITLE
Increment pipelineIid on every run ?

### ISSUE THREAD

**Issue by bcouetil** [firecow/gitlab-ci-local#126]
I would benefit from a pipelineIid incremented on every run, even a single job (with or without `--needs`). I often use a subset of the pipeline for a faster run, using `--needs` to get the shortest path to my deployment job, for example.

But, for now, the pipelineIid is incremented only on full pipelines.

This would help me set a unique docker tag in docker build&push job, and getting it in next job, without adding specific value passing between jobs, only for local use.

What do you think ?

**Comment by firecow** [comment]
@bcouetil I'm thinking of "single job" as the gitlab ui "retry" button, and there pipelineId and pipelineIid's aren't incremented.
But maybe it does make sense to do it locally anyways, or at least be able to always increment via an option.
`--always-increment-predefines` or something like that.

**Comment by bcouetil** [comment]
How about increment when --needs ? This not like the retry button, this is kind of a pipeline 😁

**Comment by firecow** [comment]
I can live with that. Yeah, thats like a "semi" pipeline.

**Comment by firecow** [comment]
https://github.com/firecow/gitlab-ci-local/pull/138 @bcouetil
