### ISSUE TITLE
Failed to determine default branch using `refs/remotes/origin/HEAD`

### ISSUE THREAD

**Issue by fschrempf** [firecow/gitlab-ci-local#1267]
`gitlab-ci-local` uses `git symbolic-ref --short refs/remotes/origin/HEAD` to determine the remote default branch in GitLab. Depending on how the local repository was setup, this might not be available (see [this link](https://github.com/jhauberg/gitdoctor/issues/3#issue-414991765) for details) and causing failures like this:

```
Error: Command failed with exit code 128: git symbolic-ref --short refs/remotes/origin/HEAD
```

A workaround is to add the symbolic-ref manually as described [here](https://stackoverflow.com/a/17639471/1923776).

A fix might be possible by parsing the output from `git remote show origin` to determine the default branch as described [here](https://github.com/jhauberg/gitdoctor/issues/3#issuecomment-467979523). 

**Expected behavior**

`gitlab-ci-local` runs without failure even if `refs/remotes/origin/HEAD` is not available

**Host information**
Manjaro
gitlab-ci-local 4.50.1

**Containerd binary**
podman version 5.1.0

**Comment by ANGkeith** [comment]
> Expected behavior
gitlab-ci-local runs without failure even if `refs/remotes/origin/HEAD` is not available

most likely your issue will be resolved by  https://github.com/firecow/gitlab-ci-local/pull/1256/files

and if `refs/remotes/origin/HEAD` is not available, you'll get the following message

![image](https://github.com/firecow/gitlab-ci-local/assets/28011783/bd3b2b36-a33f-40f8-a1e2-3ca563b137da)

**Comment by ANGkeith** [comment]
> A fix might be possible by parsing the output from git remote show origin to determine the default branch as described https://github.com/jhauberg/gitdoctor/issues/3#issuecomment-467979523.

yup, i think `git remote show origin` will be a nice to have, but it's a very expensive operation. took ~ 4 seconds on my computer. 

i don't think i'll be implementing it though, but if someone is, just take note, and perhaps cache the result or something

**Comment by fschrempf** [comment]
Confirming that 4.51.0 seems to fix the issue. Thanks! Great work!
