### ISSUE TITLE
Utilizing --job flag generates Parser error

### ISSUE THREAD

**Issue by dmentock** [firecow/gitlab-ci-local#1296]
**Minimal .gitlab-ci.yml illustrating the issue**
```
$ gitlab-ci-local --job <jobname>
TypeError: jobs.forEach is not a function
    at Parser.init (/snapshot/firecow-gitlab-ci-local/src/parser.ts:206:18)
    at Function.create (/snapshot/firecow-gitlab-ci-local/src/parser.ts:60:9)
    at handler (/snapshot/firecow-gitlab-ci-local/src/handler.ts:78:18)
    at Object.handler (/snapshot/firecow-gitlab-ci-local/src/index.ts:37:21)
```
(simply running `gitlab-ci-local ` without any argument runs the entire pipeline with no problems)

**Expected behavior**

should just run singular job. 

**Host information**
Ubuntu 22.04
gitlab-ci-local 4.52.1

**Comment by ANGkeith** [comment]
it should be `gitlab-ci-local <jobname>`

**Comment by dmentock** [comment]
I see, I saw it on some forum after I realized that `gitlab-ci-local <jobname>` executed the entire pipeline instead of just a single test for some reason, I will look more closely into that then.

**Comment by ANGkeith** [comment]
> It might still be worth looking into it since `--job` seems to be recognized as an argument, given that we don't get an "invalid arg" error

yeah agree
