### ISSUE TITLE
Error "must specify at least one container source"

### ISSUE THREAD

**Issue by bcouetil** [firecow/gitlab-ci-local#130]
On some racing conditions, when a lot of jobs are on the same stage (and start all at once), the tool stops abruptly with the message : `must specify at least one container source`. It is after all the images pull.

With 7 jobs in parallel, it happens once out of 5 times approx.

From internet, this message seems to be from `docker cp`. I suspect that one container is not fully created before the `docker cp`.

**Comment by moberghammer** [comment]
I have encountered this frequently as well

**Comment by firecow** [comment]
@bcouetil New version out. Have no other way of reaching you :smile:

**Comment by bcouetil** [comment]
I'm watching this repo, you already reached me, and I already downloaded, tested on all my usual scenarios, works great !

Just that, on my beeffy pipeline mentioned here, I had to launch it 5 times to go over this issue 😥

**Comment by firecow** [comment]
@bcouetil I have my eyes directly on this bug atm.
I think it might be that the docker create commands return exit 0, and then it takes the daemon time to actually finish the creation.
Aka, I need a docker container ls | grep ${containerId} check somewhere right after docker create commands.

**Comment by firecow** [comment]
@bcouetil https://github.com/firecow/gitlab-ci-local/pull/132
I'm not able to reproduce this issue locally. Will you be my "meatproxy" ?

**Comment by bcouetil** [comment]
Can't reproduce for now :sweat_smile: The minute I find a consistant way to reproduce, I'll test the fix. Thanks for your quick and hard work :blush:

**Comment by firecow** [comment]
https://github.com/firecow/gitlab-ci-local/pull/132
