### ISSUE TITLE
Keep the container running

### ISSUE THREAD

**Issue by tbarbette** [firecow/gitlab-ci-local#1318]
**Is your feature request related to a problem? Please describe.**
I'd like to use the gitlab-ci-local as a way to quickly setup my environment.

**Describe the solution you'd like**
Have something like --keep-running or --attach (where we attach to the container after he last job, for instance).

**Describe alternatives you've considered**
Do all the steps in the gitlab-ci manually, but it defeats its purpose :) I didn't find a way to do this currently.

**Additional context**
It's also useful as a generic way to get an environment ready on repositories where gitlab-ci is used.

**Comment by firecow** [comment]
Dublicate of https://github.com/firecow/gitlab-ci-local/issues/1032

**Comment by tbarbette** [comment]
Ah, yes wrong keywords. Sorry !
