### ISSUE TITLE
Add --env-file-to-variables cli option

### ISSUE THREAD

**Issue by AmineDjeghri** [firecow/gitlab-ci-local#1332]
**Is your feature request related to a problem? Please describe.**
 Currently, I must store the .env file in one directory, limiting flexibility, and having to manager two separate .env files. I'd like to be able to specify the .env file's location via an environment variable so it can be used from any directory or path.

**Describe the solution you'd like**
add the option to define the path to the .env file using an environment variable, like this: export GCL_ENV_FILE=.env. This would allow the gitlab-ci-local command to use the .env file from any given path, regardless of its directory. This change would allow for more flexibility in working with multiple environments and project structures.

**Comment by ANGkeith** [comment]
What exactly are you trying to do ? 

I assume you are hoping to have a centralized place to defined the "gitlab variables" for your pipeline

![image](https://github.com/user-attachments/assets/d63f890f-4759-43af-a222-5c51631e8ee6)

This might help help you
[home-file-variables](https://github.com/firecow/gitlab-ci-local?tab=readme-ov-file#home-file-variables)
[project-file-variables](https://github.com/firecow/gitlab-ci-local?tab=readme-ov-file#project-file-variables)

**Comment by AmineDjeghri** [comment]
I just want to pass a .env file variables.
We have a project that runs with environment variables, and we do it with a .env. 

If you take an example on GitHub Act (a tool to run GitHub actions locally), we can pass .env path. 
Also for local testing, we also use .env file .

It would be great to have this on gitlab-ci-local

**Comment by ANGkeith** [comment]
I see, so you're requesting for the hard-coded path `.gitlab-ci-local-variables.yml` to be configurable right ?

**Comment by AmineDjeghri** [comment]
Thank you for you quick response !
I'm asking for something like this : 

`export GCL_ENV_FILE=.env gitlab-ci-local`

**Comment by ANGkeith** [comment]
Creating the following symbolic link should be a quick fix while waiting for this to be implemented

```bash
ln -s .env .gitlab-ci-local-variables.yml 
```

**Comment by firecow** [comment]
What kind of stuff would be placed in such `.env` file?

**Comment by AmineDjeghri** [comment]
À .env preferably since it's the most used type of file to contain variables (in python)

**Comment by firecow** [comment]
But what kind of values are you putting in your .env file that you want to pass to `gitlab-ci-local`?

**Comment by AmineDjeghri** [comment]
I want to pass all the variables . A .env file is not specific and contains many env variables that change when you switch projects

**Comment by firecow** [comment]
I think you need to clarify very precisely what you want this feature to become in a new issue or here.

Add very realworld like .env files and gitlab-ci.yml's n' such...


Normally people put variables inside the `<cwd>/.gitlab-ci-local-variables.yml` or `~/.gitlab-ci-local/variables.yml`

**Comment by AmineDjeghri** [comment]
Sorry but I don't know how to be clearer than this 😅
I want to be able to load the environment variables from a specified .env file .
So for example when I run the gitlab ci local, I provide the path of the .env file and it will load all the env variables


Here is an example of a .env file (this one is named .env.example but the true name is .env). It contains some environment variables that will be loaded 

https://github.com/platformsh-templates/laravel/blob/master/.env.example

**Comment by ANGkeith** [comment]
![image](https://github.com/user-attachments/assets/1d8aa684-7aaa-40f3-b1d2-7e8616ee558a)

is the top pane of the screenshot what you're requesting ? 
are we understanding you correctly ?

**Comment by AmineDjeghri** [comment]
The variables inside a .env needs to have the "=" instead of ":".

WHO="I like ...."

But the idea is this . You are correct

**Comment by ANGkeith** [comment]
> Are we talking about the .env file should be extrapolated into `GCL_` "commands/options" or variables living inside your jobs?

Yeah, I think this is where the confusion comes from, haha. I was wondering the same thing.

I believe he's referring to the `variables used within your jobs`.

**Comment by firecow** [comment]
This is why I wanted a precise .env file with real world contents :smile:

**Comment by AmineDjeghri** [comment]
I think it is better to write a little scenario for what I want 


I have a repository that contains somewhere a .env file (it is ignored in .gitignore)

I run the gitlab ci local command and I specify the path to the .env file

Gitlab ci local will load inside my container the variables that are inside the .env

If I do : echo $VARIABLE1 inside my gitlab ci local container, I will the the value of the variable that is inside the .env which means that it properly exported the variables inside the .env file

**Comment by firecow** [comment]
Yes yes... 

We need a cli options called `--env-file-to-variables=.env`.

Rename the title to "Add --env-file-to-variables cli option" :smile:

**Comment by AmineDjeghri** [comment]
Glad that we finally understand each other 😂
I renamed the title

**Comment by ANGkeith** [comment]
> We need a cli options called `--env-file-to-variables=.env`

i was thinking about something like this instead, https://github.com/firecow/gitlab-ci-local/pull/1355/files#diff-3d6e22f8e4281faf7d19dcacaf5fe63566f6ada084252104ef5f04b9c687e140R121-R123

what do you think ?

**Comment by ANGkeith** [comment]
ok just pushed the test, should be good now

**Comment by AmineDjeghri** [comment]
I already provided a link to a.env example. But here is a copy paste of that same file



`APP_NAME=Laravel
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=laravel
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
FILESYSTEM_DISK=local
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

MEMCACHED_HOST=127.0.0.1`

**Comment by firecow** [comment]
@AmineDjeghri I'll get it released during the day
