### ISSUE TITLE
`.gitlab-ci-local-variables.yml` not being correctly parsed.

### ISSUE THREAD

**Issue by ekohilas** [firecow/gitlab-ci-local#1333]
I can't seem to get `.gitlab-ci-local-variables.yml` to be read in as variables.

I'm trying to understand how to set this up, and when running on my `.gitlab-ci.yml` file, `gitlab-ci-local` fails to run because a custom variable our yaml isn't configured.

Which is fine, as I can configure it myself.

If I go to do so through the CLI using `gitlab-ci-local --list --variable CUSTOM_VAR=value` it works fine.

Same goes for setting it up using `.gitlab-ci-local-env`

However when I configure `.gitlab-ci-local-variables.yml` as described in the readme:

```yml
---
  CUSTOM_VAR: value
```

I get an error saying that my variable isn't defined.

On debugging the code, I find that the logic for the expanded variables is the same, so I believe the values set in variablesFromFiles and expanded aren't correctly parsed by the rest of the code (since variables seem like they can be read in from multiple places, not just the unified expanded).

Or, am I misunderstanding how to use this tool?

If so, could more guidance be added to the readme please?

For now, I can use `--variable` but this won't scale for a more thorough solution :/

**Comment by ekohilas** [comment]
(Have edited to amend with different findings)

**Comment by ekohilas** [comment]
Sorry I still get the same issue :/

**Comment by ekohilas** [comment]
The furthest I've gotten with debugging is that it fails within `Utils.forEachRealJob`

**Comment by ekohilas** [comment]
In the constructor of a job, the variables are set to the following:

```
this._variables = {...globalVariables, ...jobVariables, ...matrixVariables, ...predefinedVariables, ...argvVariables};
```

Then, they're used in the environment variables.

```
// Find environment matched variables
if (this.environment && expandVariables) {
    const expanded = Utils.expandVariables(this._variables);
    this.environment.name = Utils.expandText(this.environment.name, expanded);
    this.environment.url = Utils.expandText(this.environment.url, expanded);
}
```

This is where the program starts to error, because it can't find the variable and thus `this.environment.name=''`

But directly below we see where `variablesFromFiles` first gets used.
```
const envMatchedVariables = Utils.findEnvMatchedVariables(variablesFromFiles, this.fileVariablesDir, this.environment);
```

So it seems that the solution would be:
```
// Find environment matched variables
if (this.environment && expandVariables) {
    const globalEnvironmentVariables = Utils.findEnvMatchedVariables(variablesFromFiles, this.fileVariablesDir, "*");
    const environmentVariables = {...this._variables, ...globalEnvironmentVariables};
    const expanded = Utils.expandVariables(environmentVariables);
    this.environment.name = Utils.expandText(this.environment.name, expanded);
    this.environment.url = Utils.expandText(this.environment.url, expanded);
}
```

**Comment by firecow** [comment]
What is the exact error you are getting?

**Comment by ekohilas** [comment]
Error:
```
• 'environment' property type must be string at deploy.environment
• property 'name' must not have fewer than 1 characters at deploy.environment.name
```

The job contains:
```
  environment:
    name: "$CUSTOM_VAR"
```

**Comment by firecow** [comment]
I'm going to need an as simple example, to reproduce what you are experiencing...
