### ISSUE TITLE
Minor misleading typo in README.md

### ISSUE THREAD

**Issue by stdedos** [firecow/gitlab-ci-local#1344]
There is a small technical error in the 

https://github.com/firecow/gitlab-ci-local/blob/cf8f61e67a4c0332da217b1de5f90f5f023a2a0a/README.md?plain=1#L66

suggestion.

They key is `.asc` (ASCII-armored) format, and not binary (i.e. `.gpg`)

Ofc it doesn't make a difference when piped, but it kinda does when you want to setup e.g.

```list
deb [ signed-by=/etc/apt/sources.keyring.d/gitlab-ci-local-ppa.asc ] https://gitlab-ci-local-ppa.firecow.dk ./
```

(for older apt versions that do not support the verbatim Signed-By key of the Deb822 format)

**Comment by firecow** [comment]
@stdedos Make a PR man 😃

**Comment by stdedos** [comment]
Also kinda sorta you should update the filename on the server. 

How about some `ln -s`-foo? 😄 

_PS: I'll send the PR later tonight _

**Comment by firecow** [comment]
Can you be more specific on what you want updated? I'm confused :D @stdedos

**Comment by stdedos** [comment]
You are exposing https://gitlab-ci-local-ppa.firecow.dk/pubkey.gpg for download.
As I have mentioned above, the extension is wrong - it should be https://gitlab-ci-local-ppa.firecow.dk/pubkey.asc

So I would ask you to rename the file `pubkey.gpg` to `pubkey.asc`.

However, I understand that you have been having the https://gitlab-ci-local-ppa.firecow.dk/pubkey.gpg URL public for some time - so you cannot "just remove it".
So probably you will end up with both https://gitlab-ci-local-ppa.firecow.dk/pubkey.gpg and https://gitlab-ci-local-ppa.firecow.dk/pubkey.asc pointing at the same file

**Comment by firecow** [comment]
Aah.. I see.. We shall just have both.

**Comment by stdedos** [comment]
> Add a dublicate in your PR

You mean

```bash
curl -s "https://gitlab-ci-local-ppa.firecow.dk/pubkey.asc" | sudo tee "${PPA_KEY_PATH}"
```
?

**Comment by firecow** [comment]
Wait a minute the file doesn't exists until next version, my bad :smile:
