### ISSUE TITLE
Allow --fetch-includes to work on a specific job run instead of individual tasks

### ISSUE THREAD

**Issue by elafontaine** [firecow/gitlab-ci-local#1371]
**Is your feature request related to a problem? Please describe.**
I would like to "always pull" the latest gitlab-CI jobs definition of my "includes".  Like `--fetch-includes` but allowing to have this option to run the job after pulling all the latest includes if specified.

**Describe the solution you'd like**
Allowing the `--fetch-include` to execute before trying to get the jobs definition from local.  This would make it get a fresh definition everytime.

**Describe alternatives you've considered**
We've made a 2 stages run script, one that does the fetch-include and one that actually run the job we want to run.  This works, but it's a itching that could be easily handled from within the binary itself (from our perspective ;) we could be wrong).

**Comment by ANGkeith** [comment]
should be resolved #1365
