### ISSUE TITLE
Clean oldest artifacts

### ISSUE THREAD

**Issue by bcouetil** [firecow/gitlab-ci-local#139]
Now artifacts are in `.gitlab-ci-local/artifacts/<pipelineID>`.

It stacks up pretty rapidely, one for each pipeline launched. 1.6GB on a project of mine since the new feature (of mine... this is my mess :stuck_out_tongue_closed_eyes: ).

On top of that, the root directory is copied to containers, this folder included. Losing some time on every jobs.

It would be great to have a configurable number of artifacts folders kept, and delete the older ones. Maybe 2 kept by default.

I think that deleting every folders with name < `pipelineIid-$retention` is simple and satisfying enough.

**Comment by firecow** [comment]
`.gitlab-ci-local` is copied to the container ?
Well, that doesn't make any sense.
There are actually two issues here then. Only copy tracked files, and add --clean-artifacts cli option.
@bcouetil

**Comment by firecow** [comment]
https://github.com/firecow/gitlab-ci-local/issues/141 @bcouetil I've created the "other" task.

**Comment by bcouetil** [comment]
The `--clean-artifacts` is a great idea. Even simpler. But this has to be done before the pipeline, not after, to at least get latest artifacts.

**Comment by firecow** [comment]
@bcouetil Do we even need the artifacts to be pipeline specific ?

**Comment by bcouetil** [comment]
I did it to mimic Gitlab... But no, not me. In fact we can keep only last artifacts, you are right. YAGNI !

**Comment by firecow** [comment]
https://github.com/firecow/gitlab-ci-local/pull/144
