### ISSUE TITLE
Only copy tracked files into docker containers

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#141]

**Comment by bcouetil** [comment]
This is just a guess of mine, since specifying excludes in `docker cp` is not possible (I searched the net extensively when implementing the artifacts separation feature).

**Comment by bcouetil** [comment]
This was a good guess :

![Screenshot from 2021-04-17 21-12-14](https://user-images.githubusercontent.com/42612335/115124286-a921c800-9fc1-11eb-800a-d957be2e146c.png)

**Comment by bcouetil** [comment]
If we don't have any solution, a soft link to `/tmp` would avoid artifacts copy, I think.

**Comment by firecow** [comment]
```typescript
            const {output} = await Utils.spawn("git ls-files", this.cwd);
            for (const line of output.split(/\r?\n/g).filter((line) => line !== "")) {
                const dir = ("./" + line).replace(/[^/]+$/, "");
                await Utils.spawn(`mkdir -p /tmp/gitlab-ci-local-job/${this.name}/${dir}`);
            }
            await Utils.spawn(`docker cp /tmp/gitlab-ci-local-job/${this.name}/. ${this.containerId}:/builds/`);
            for (const line of output.split(/\r?\n/g).filter((line) => line !== "")) {
                await Utils.spawn(`docker cp ${line} ${this.containerId}:/builds/${line}`, this.cwd);
            }
```

But it adds 13 secs to my jobs `copied source to container in 14 s`

**Comment by bcouetil** [comment]
Indeed, we do that to save time, not loose some :sweat_smile:

**Comment by firecow** [comment]
```
mkdir -p .gitlab-ci-local/builds/job-name/
rsync -ah --delete --exclude-from=<(git -C . ls-files --exclude-standard -oi --directory) . .gitlab-ci-local/builds/job-name/
docker cp .gitlab-ci-local/builds/job-name/. /build/.
```

And it goes like this ? @bcouetil You like ?

**Comment by bcouetil** [comment]
Wow ! And performance wise ?

**Comment by firecow** [comment]
@bcouetil You the man with the biggest project. https://github.com/firecow/gitlab-ci-local/pull/146 Try it out...

**Comment by firecow** [comment]
@bcouetil Its probably a good idea to exclude .gitlab-ci-local folder from being indexed by your editor, hehe :smile:

**Comment by firecow** [comment]
11mb of tracked file
1st run 500ms
2nd run 90ms
