### ISSUE TITLE
Linux Ubuntu 18.04 support

### ISSUE THREAD

**Issue by frakman1** [firecow/gitlab-ci-local#1419]
I don't know if Ubuntu 18.04 is supported or not. If so, then I am reporting this bug. 
If not, I request that it be supported if possible.

I installed the tool using apt as per the instructions.
```
$ file /usr/local/bin/gitlab-ci-local
/usr/local/bin/gitlab-ci-local: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=0f0b42a210d882aeae0d1c78366ca0df7ad87f02, for GNU/Linux 3.2.0, stripped
```
I get a segmentation faul core dump when I try to run it.
```
$ LD_LIBRARY_PATH=/opt/glibc-2.28/lib:$LD_LIBRARY_PATH  gitlab-ci-local
Segmentation fault (core dumped)
```
I had to install glib-2.28 manually otherwise it wouldn't even run
```
$ gitlab-ci-local
gitlab-ci-local: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by gitlab-ci-local)
```

**Host information**
```
$ uname -a
Linux Kubuntu18 5.4.0-99-generic #112~18.04.1-Ubuntu SMP Thu Feb 3 14:09:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
gitlab-ci-local ?? 

**Containerd binary**
I am running on a Linux VM.

**Comment by firecow** [comment]
Yeah, we are not gonna spent time supporting an OS that is this old.

https://stackoverflow.com/questions/72513993/how-to-install-glibc-2-29-or-higher-in-ubuntu-18-04
You can try building and installing a newer `glibc` yourself, perhaps that will work.
