### ISSUE TITLE
for noobies the readme does not mention esbuild has to be run before packaging

### ISSUE THREAD

**Issue by TristanFAURE** [firecow/gitlab-ci-local#1426]
**Minimal .gitlab-ci.yml illustrating the issue**
not need
```

**Expected behavior**
as said in the title, I tried to build locally because I needed to pull https include.
I'm not familiar with node and following README instructions I saw the call to npm run esbuild was missing

**Host information**
Ubuntu
gitlab-ci-local 4.55.0

**Comment by firecow** [comment]
You don't have to run esbuild.

I test the program like this locally.

```
node src/index.js --cwd ../somefolder-with-gitlabci
```

**Comment by TristanFAURE** [comment]
Thanks for the feedback and sorry if it was useless. I did not notice you have the bin folder created with this command 
(i got a bin folder not found error when I tried to package it)

**Comment by ANGkeith** [comment]
> I tried to build locally because I needed to pull https include.

could you elaborate a bit more on what you are trying to do ? 

---


There are multiple ways of running this project locally

1. building a package binary (single executabe)
  - `npm run esbuild` follow by `npm run pkg-<macos/linux/win/all>` 
  ie. 
  
![image](https://github.com/user-attachments/assets/55b69f04-0c86-4329-bae1-eede293a0df3)

2. compiling the typescript into javascript
  - `npm run build` should generate the `.js` files in the `src` dir
  -  you should be able to run gcl via `node src/index.js`
  ie.  
  
![image](https://github.com/user-attachments/assets/aa37f230-15e1-4ad6-a4fa-a8a3f4ffba52)
  currently i think we're only using this as one of the step to publish the package to  https://www.npmjs.com/package/gitlab-ci-local
3. executing the typescript file directly without the `.js` file
  - `npx tsx src/index.ts`
  
4. executing the typescript file directly without the `.js` file with hot-reloading
  - `npm run dev`

**Comment by TristanFAURE** [comment]
OK thanks I finally succeed I just think it could be mentioned in the documentation ?

**Comment by ANGkeith** [comment]
https://github.com/TristanFAURE/gitlab-ci-local/tree/master?tab=readme-ov-file#development

I pushed some commits into your mr.. 

if there's anything else feel free to add more info
