### ISSUE TITLE
Bug in rule interpretation

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#1431]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
  rules:
    - { if: $GITLAB_CI == 'false' && $APP_ENV_TIER =~ 'dev', when: manual, allow_failure: true }
    - { if: $GITLAB_CI == 'true' && $APP_ENV_TIER =~ 'stage', when: manual, allow_failure: true }
    - { if: $GITLAB_CI == 'true' && $APP_ENV_TIER =~ 'prod' && $CI_COMMIT_TAG != null, when: manual, allow_failure: true }
    - { when: never }
```

**Expected behavior**
I expect these rules to produce no errors

**Host information**
Ubuntu
gitlab-ci-local 4.52.1 works, gitlab-ci-local 4.53.0 does not, 

**Containerd binary**
docker

**Additional context**
```
mjn@mjn-laptop:~/$ gitlab-ci-local --list --variable GITLAB_CI=false

Error attempting to evaluate the following rules:
  rules:
    - if: '"false" == 'false' && "dev" =~ 'dev''
as
```javascript
"false" == 'false' && "dev" =~ 'dev'
\```
```

**Comment by ANGkeith** [comment]
The rhs of ~= should be regex
![image](https://github.com/user-attachments/assets/d6f7fad3-f9a5-4130-8ca0-9168245a2cc5)

as per https://docs.gitlab.com/ee/ci/jobs/job_rules.html#unexpected-behavior-from-regular-expression-matching-with-

**Comment by ANGkeith** [comment]
opps.. seemed like i have missed out on the single quotes here
https://github.com/firecow/gitlab-ci-local/blob/master/src/utils.ts#L234
