### ISSUE TITLE
Documentation: Rename example for env file

### ISSUE THREAD

**Issue by gbmd** [firecow/gitlab-ci-local#1433]
The readme suggests the following: 
`Add a .gitlab-ci-local-env file to the current working directory or a .env file in $HOME/.gitlab-ci-local`.
According to `gcl --help` though, the default name is `.gitlab-ci-local-variables.yml`. 
It took me some time to figure out why my variables were not accessible inside my executor's docker containers.
So I would suggest to make the documentation a bit more self-explanatory like this:

`Add a .gitlab-ci-local-variables.yml file to the current working directory or a .env file in $HOME/.gitlab-ci-local.`.

Thanks in advance!

**Comment by ANGkeith** [comment]
This is frequently confused. 

This https://github.com/firecow/gitlab-ci-local?tab=readme-ov-file#dotenv-file section of the docs is referring to the following 
![image](https://github.com/user-attachments/assets/c8aa62ef-b0cc-4626-a279-105063daa605)



For what you are trying to do, you should actually refer to:
https://github.com/firecow/gitlab-ci-local?tab=readme-ov-file#home-file-variables
https://github.com/firecow/gitlab-ci-local?tab=readme-ov-file#project-file-variables


Hopefully this is clearer now.  Feel free to open an mr to phrase it better

**Comment by ANGkeith** [comment]
fixed in https://github.com/firecow/gitlab-ci-local/pull/1434
