### ISSUE TITLE
`CI_PROJECT_DIR` variable is missing

### ISSUE THREAD

**Issue by JoyceBabu** [firecow/gitlab-ci-local#154]
GitLab CI creates a variable named `CI_PROJECT_DIR` with the path to the build directory. Currently `gitlab-ci-local` is not creating the variable.

> `CI_PROJECT_DIR` - The full path the repository is cloned to, and where the job runs from. If the GitLab Runner builds_dir parameter is set, this variable is set relative to the value of builds_dir. 
>
> https://docs.gitlab.com/ee/ci/variables/predefined_variables.html

**Comment by firecow** [comment]
@JoyceBabu You want collab invite ?
https://github.com/firecow/gitlab-ci-local/pull/155 Heres a PR for CI_PROJECT_DIR

**Comment by JoyceBabu** [comment]
@firecow I am just testing `gitlab-ci-local` on a personal project of mine. But I am not too familiar with GitLab CI, and hence I don't think I can be of much help here. Thanks for the offer anyway.

Btw, I really appreciate the work you have done here. I was trying to debug an issue with `apt-get` not working, and it would have been really inconvenient to push every change to GitLab for testing. `gitlab-ci-local` was really helpful.

**Comment by firecow** [comment]
@JoyceBabu Thank you very much :smile: I will keep the PR's coming, until everything is as close to gitlab remote as possible....
