### ISSUE TITLE
Suggestion for project variables

### ISSUE THREAD

**Issue by JoyceBabu** [firecow/gitlab-ci-local#156]
While a global registry is necessary for `global` and `group` level variables, I think it is much better to keep the project level config within the project directory. This allows keeping the project directory self contained.

Since we already have a `.gitlab-ci-local` directory inside the project directory, would it be possible to load project level variables from `$PROJECT_DIR/.gitlab-ci-local/variables.yml` too. Since this directory is supposed to be gitignored, there is no risk of any sensitive variables leaking by mistake.

Also, the current format is not very intuitive. For example, I copy pasted the remote url from my `.git/config` to  the `project` section of `$HOME/.gitlab-ci-local/variables.yml`, and had difficulty getting it to work. It took me some time to realize  that I have copy pasted the remote url in `ssh` format  (`git.myhost.com:group/project.git`  instead of `git.myhost.com/group/project.git`). If we add a project specific `variables.yml` it can be a simple `key: value` list.

**Comment by JoyceBabu** [comment]
I can send a PR, i you are interested.

**Comment by bcouetil** [comment]
I like the current handling off all variable levels in the same file. But it would not hurt merging it with a local file 😉

**Comment by JoyceBabu** [comment]
I am not suggesting to replace the existing method, but as an additional option for configuring the variables.

In case we go ahead with this, and merge the variables, which one gets higher priority?

**Comment by firecow** [comment]
cwd/.gitlab-ci-local/variables.yml gets highest.
We can also replace all : with / and add an --variables option that prints the variables that the jobs. will get injected

**Comment by JoyceBabu** [comment]
I have created a PR. Can you please check?

https://github.com/firecow/gitlab-ci-local/pull/157

**Comment by JoyceBabu** [comment]
> We can also searcg/replace all : with / runtime and add an --variables option that prints the variables that the jobs will get injected, for easier debugging

Is that only for projects? Replacing the `:` doesn't make much sense for groups. Or is it better to keep it simple and just print a warning message if a `:` character is detected?

**Comment by firecow** [comment]
A warning is fine...
But no URL can contain colons, so we can just infer / always. You decide.
