### ISSUE TITLE
File Variables are in a potentially dangerous location

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#159]
Make sure they cannot accidentally be added to projects git repos, by not putting them in `.gitlab-ci-local/file-variables/`

Yes, we had an incident, where a developer pushed his private key to our gitlab :smile:

**Comment by JoyceBabu** [comment]
Should't `.gitlab-ci-local` be gitignored always? 

How about adding an entry to `.gitignore` automatically when the directory is created. You could even take it a step further by asking the user whether to commit the change, and create a commit automatically on confirmation.

**Comment by firecow** [comment]
Auto generating a .gitignore file is an excellent solution.

**Comment by bcouetil** [comment]
Sorry but I don't like it. This is an intrusion in one of my precioussss files :sweat_smile: 

I'd better like a big warning saying that this file is not git ignored !

**Comment by firecow** [comment]
If thats the case, then we should just not have file-variables in the `.gitlab-ci-local/file-variables/` directory.

**Comment by firecow** [comment]
Auto appending stuff to `${cwd}/.gitignore` isn't my cup of tea either.
Putting a file inside `.gitlab-ci-local/.gitignore` won't help us, will it ?

**Comment by bcouetil** [comment]
Oh I did not know we could do that ! I suggest auto create `.gitlab-ci-local/.gitignore` if not existing. If the user then edit it, it is its choice ! but we helped him the first time.

**Comment by firecow** [comment]
PR incoming

**Comment by JoyceBabu** [comment]
> Auto appending stuff to `${cwd}/.gitignore` isn't my cup of tea either.
> Putting a ignore inside `.gitlab-ci-local/.gitignore` won't help us, will it ?

Perfect

**Comment by firecow** [comment]
After the .gitignore file copy stuff, I'm deeming it unnecessary to "help" the users more to avoid file-variables being comittet to git.
