### ISSUE TITLE
Improve readability of --list ?

### ISSUE THREAD

**Issue by bcouetil** [firecow/gitlab-ci-local#164]
Now that the tool is perfect for my needs :pray: 😍, let's discuss some minor improvements

Did not use --list in a while, and launched today, seeing this :

![Screenshot from 2021-04-28 13-41-13](https://user-images.githubusercontent.com/42612335/116397936-7da3a680-a827-11eb-9e46-72e19fa613fa.png)

Some first impressions :
- The background red of CAN FAIL is too much. My mind screams "what did I do wrong ?!" 
- Not having columns makes it difficult to understand
- Stages would better be between jobs, we would then have pseudo-pipeline view ! This would benefit to end report, too

Suggestion :

```
job        description                    when        allow_failure  needs
---[ 🔍 Check 🔢 Calculate ]----
version    version check and calculate    on_success  false 
------[ 🏗 Package ✨ MR ]------
package  maven package                    on_success  false          [version]
lint       lint deploy                    on_success  false          [version]
-----[ 🐳 Image 🔺 Cheops ]-----
test       test and check quality for MR  on_success  false          [package]
docker     dev build GKE docker image     on_success  false          [package]
----[ 🚀 Deploy ⏮ Rollback ]----
deploy     feat GKE deploy                on_success  false          [lint,docker]
ns-delete  feat GKE delete ns             manual      true
rollback   feat GKE rollback              manual      true
```

What do you think ?

Note : a manual job is `allow_failure: true` by default.

**Comment by firecow** [comment]
![image](https://user-images.githubusercontent.com/973602/116400341-3965d580-a82a-11eb-850e-4871fd37e319.png)

I think we shall remove the red and yellow bg's from --list, and just make the font red and yellow.
As you see in my screenshot, the columns are aligned, so we need to figure out whats going on here.

Did you just write when: manual or is it part of a rules: segment ?

**Comment by firecow** [comment]
![image](https://user-images.githubusercontent.com/973602/116400592-834ebb80-a82a-11eb-8ea7-19ddfb2a0b09.png)
This is better right ? Colorwise...

**Comment by bcouetil** [comment]
The alignment is due to emojis, they are always messing up the alignment, don't worry about that.

Yes, color-wise it is better. But still red for the normal behavior does not suit me...

It is part of `rules` segment.

a manual job is allow_failure: true by default.

**Comment by firecow** [comment]
If that is true, I have a bug in the rules tests... I'm reproducing remotely

**Comment by firecow** [comment]
![image](https://user-images.githubusercontent.com/973602/116401145-2b648480-a82b-11eb-928b-3e196a4818f3.png)

```
---yml
test-job:
  tags: ["gitlab-org"]
  image: alpine
  rules:
    - if: $GITLAB_CI == 'true'
      when: manual
  script:
    - exit 1

**Comment by firecow** [comment]
I believe, you are confusing when: manual with the rules segment containing when: manual quirk..
I've touched that weird behavior too many times :D

**Comment by firecow** [comment]
![image](https://user-images.githubusercontent.com/973602/116403479-e42bc300-a82d-11eb-9fe4-ecf9b24502a1.png)

@bcouetil How about this one ?

**Comment by bcouetil** [comment]
You must be right ! And yes, this looks good.

Still, for cases when stages have lots of jobs, printing stage in between would be better, imho.
