### ISSUE TITLE
Implement wildcard in artifacts

### ISSUE THREAD

**Issue by bcouetil** [firecow/gitlab-ci-local#174]
I have a `target` folder in multiple subfolders (using maven modules), and would like this to work, as it is on Gitlab runners :

```
  artifacts:
    paths:
      - "*/target"
```

workaround :

```
  artifacts:
    paths:
      - "module-a/target"
      - "module-b/target"
```

**Comment by firecow** [comment]
The main problem here is that alpine images for instance doesn't support 
```

**Comment by firecow** [comment]
Maybe its time to invoke a little trick I know.
```
docker volume create ${jobName}-docker-volume
docker create -v ${jobName}-docker-volume:/builds/ ${imageName}
# run scripts
docker run -v ${jobName}-docker-volume:/builds/ --name intercontainer debian bash -c "shopt -s globstar;cp /builds/${artifactPath} /artifacts/"
docker cp intercontainer:/artifacts/ .gitlab-ci-local/artifacts/${jobName}
```

**Comment by bcouetil** [comment]
I would have guessed that `cp */target` would have worked no matter the image, but you seem way more informed than me on that matter :sweat_smile:

**Comment by firecow** [comment]
Single asterisk might work in all sorta images, but double globstar certainly won't :smile: But wth, an extra docker run per job with artifacts, we will live :smile:

**Comment by bcouetil** [comment]
Sorry @firecow , I forgot to test with emojis in job names, and this does not work :

![Screenshot from 2021-05-05 19-24-36](https://user-images.githubusercontent.com/42612335/117183347-ba4b4100-add7-11eb-825e-b5499d13d0aa.png)

**Comment by firecow** [comment]
@bcouetil I'll see if I can add emojies to my safeJobname function... We will be fine 😆😆

**Comment by firecow** [comment]
@bcouetil https://github.com/firecow/gitlab-ci-local/commit/9e1c27ede3cdc7cf75f1cc413ad573894c6ceb0b Threw it straight into master, hope thats ok.

**Comment by bcouetil** [comment]
Tested, working like a charm :tada:
