### ISSUE TITLE
Some of the predefinedVariables in src/job.ts have only constant sample strings

### ISSUE THREAD

**Issue by ck-trigfb** [firecow/gitlab-ci-local#176]
Some of the variables like CI_COMMIT_SHA in src/job.ts only have constant sample strings as values. Need to be replaced with the correct content e.g. for CI_COMMIT_SHA something like "git rev-parse HEAD".

**Comment by firecow** [comment]
@ck-trigfb Thanks for the report.
Besides CI_COMMIT_SHA are there any other keys, that you can find "good" values to?

**Comment by ck-trigfb** [comment]
Maybe you can start with some of these:
CI_COMMIT_SHORT_SHA: git rev-parse --short HEAD
CI_COMMIT_SHA: git rev-parse HEAD
CI_COMMIT_REF_PROTECTED: "false",
CI_COMMIT_BRANCH: git rev-parse --abbrev-ref HEAD
CI_COMMIT_REF_NAME: $(git branch --show-current)			
CI_COMMIT_REF_SLUG: 
BRANCH=$(git branch --show-current)
$(shell echo $(BRANCH) | cut -c -63 | sed -E 's/[^a-z0-9-]+/-/g' | sed -E 's/^-*([a-z0-9-]+[a-z0-9])-*$$/\1/g')

**Comment by bcouetil** [comment]
I was relying on the `local/branch` to distinguish it from remote branch in remote environment, but I can adapt by forcing it in global variables :smile:

**Comment by firecow** [comment]
@bcouetil I'm using GITLAB_CI=(true/false) to distinguish between local and remote.

**Comment by bcouetil** [comment]
Yes, so do I.

I was talking about some specific cases, like 1 branch 1 env. But i can use this too, adding a couple of "if" conditions.

And thinking about it, my way of doing it was not team friendly : collegues would mess my kubernetes namespace, since branch name was constant 😅
