### ISSUE TITLE
chown: unknown user/group root:root

### ISSUE THREAD

**Issue by ck-trigfb** [firecow/gitlab-ci-local#179]
In src/job.ts there is that part:
        if (this.imageName) {
            cmd += "cd /builds/\n";
            cmd += "chown root:root -R .\n";
            cmd += "chmod a+w -R .\n";

But f i use an image that has no root:root user like an image that is builded with "FROM scratch" (e.g. kaniko, in my case gcr.io/kaniko-project/executor:debug), then there will be the following error message: "chown: unknown user/group root:root"

As a workaround i copy user and group (root:root) from another ubuntu image to the kaniko image and create my own version of it. But i think that there are more situations where an Docker image maybe has no root:root user built-in.

**Comment by firecow** [comment]
Does this image work on remote gitlab-runners? @ck-trigfb

**Comment by ck-trigfb** [comment]
Yes. It works as described here: https://docs.gitlab.com/ee/ci/docker/using_kaniko.html

I have run it on my gitlab repository successfully:
`Executing "step_script" stage of the job script
01:19
Using docker image sha256:7053f62a27a84985c6ac886fcb5f9fa74090edb46536486f69364e3360f7c9ad for gcr.io/kaniko-project/executor:debug with digest gcr.io/kaniko-project/executor@sha256:fcccd2ab9f3892e33fc7f2e950c8e4fc665e7a4c66f6a9d70b300d7a2103592f ...
$ mkdir -p /kaniko/.docker
$ echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
$ /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG`

**Comment by firecow** [comment]
```
---
test-job:
  tags: [gitlab-org]
  image: gcr.io/kaniko-project/executor:debug
  script:
    - echo "Hello World"
```

![image](https://user-images.githubusercontent.com/973602/117770563-5c828300-b235-11eb-9147-09729265caa6.png)

Are you sure that it works on remote runners ? @ck-trigfb  
I cannot get it to work with this.

**Comment by firecow** [comment]
Yes, we have a problem with gitlab-ci-local

**Comment by ck-trigfb** [comment]
You need to ad this to override the entrypoint:
entrypoint: [""]

Kaniko is a very basic image based on "FROM scratch" and has no sh or other tools installed.

**Comment by firecow** [comment]
On it
