### ISSUE TITLE
a colon ":" or slash "/" in job names (job groups) throws an error "invalid characters for local volume"

### ISSUE THREAD

**Issue by ck-trigfb** [firecow/gitlab-ci-local#186]
In gitlab-ci you can group jobs with colon, slash or space: https://docs.gitlab.com/ee/ci/jobs/#group-jobs-in-a-pipeline
- `package/docker:`
- `package:docker:`
- `package docker:`

If you use colon or slash that will cause an error, because slash and colon are invalid character for a local volume name:
`Error response from daemon: create gcl-package/docker-100159: "gcl-package/docker-100159" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path`

**Comment by firecow** [comment]
@ck-trigfb You sure about the space? What operating system are you one?

**Comment by ck-trigfb** [comment]
Maybe I have to test it again, because I don’t ready the manual exactly. For groups only numbers are allowed, so that should be possible job names:
- package 1/3:
- package 1:3:
- package 1 3:

I am on a Windows 10 system with WSL2/Ubuntu.

**Comment by ck-trigfb** [comment]
Ok, i did some experiments today: Maybe we have to split this probelm into different issues:
1. job name can consist of nearly every character. This is a valid jobname "build-my&$"§$" shit:::::" (checked with CI Lint in gitlab). 

- This results in different problems in gitlab-ci-local because the job name is used for directory names.
- If you use images in the job, then also volumes cannot be mounted cause of the invalid characters

2.  Job groups: As described in the gitlab-ci docs (https://docs.gitlab.com/ee/ci/jobs/#group-jobs-in-a-pipeline) you can have job groups with syntax "X Y, X/Y, or X\Y". So something like that is valid  "test1 2". "test1/2", "test1:2", 

- Same problems as above: invalid character for directory and volume names

Maybe an idea: hash the job names and use the hash as the name for directories and for mounting volumes.

**Comment by firecow** [comment]
@ck-trigfb 
```
    get safeJobName() {
        if (this.name.match(/[^\w_-]+/)) {
            const buffer = Buffer.from(this.name, "utf8");
            return base32Encode(buffer, "Crockford", {padding: false});
        }
        return this.name;
    }
```
What about base32 with "Crockford" characters if jobnames fail the "sanity" check ?

**Comment by ck-trigfb** [comment]
Yeah, that should also do the trick ;).
