### ISSUE TITLE
rsync: rename "*/.git/objects/*" -> ".git/objects/*": Permission denied

### ISSUE THREAD

**Issue by ck-trigfb** [firecow/gitlab-ci-local#188]
I cannot reproduce it at the moment and i dont know exactly in with situations this error appears. But during my work with my code and after severals runs of gitlab-ci-local i am not able to start the pipeline again:
```
rsync: rename "/mnt/c/Users/UserName/Code/.gitlab-ci-local/builds/.docker/.git/objects/d6/.b7ef32c8478a48c3994dcadc86837f4371184d.0UT1kg" -> ".git/objects/d6/b7ef32c8478a48c3994dcadc86837f4371184d": Permission denied (13)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
```

Workaround for me is to delete the whole .gitlab-ci-local/ folder. After that is works again. Have to do that about 3-5 times a day.

**Comment by firecow** [comment]
How your .git folder i beyond me.
But none the less, I'll try adding it to rsync --exclude and see if that helps you out @ck-trigfb

**Comment by firecow** [comment]
Here is the rsync --exclude .git/ change.
https://github.com/firecow/gitlab-ci-local/commit/8d84502b691298beed5010afd919d5a3ad37fcf4

Just reopen, if you are still experiencing this issue. @ck-trigfb
