### ISSUE TITLE
Implement `cache: { key: { files: [] } }`

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#189]

**Comment by KTamas** [comment]
this would be quite crucial. following

**Comment by firecow** [comment]
@KTamas Rigtheo, I shall get to work :smile:

**Comment by firecow** [comment]
That should do it :smile: 
https://github.com/firecow/gitlab-ci-local/commit/7eec325168e3992c0999faf29c84c0ca54bd65e3

@KTamas Let me know, if it isn't working for ya...
