### ISSUE TITLE
wildcards when including local files

### ISSUE THREAD

**Issue by atli-c** [firecow/gitlab-ci-local#197]
https://about.gitlab.com/releases/2021/05/22/gitlab-13-12-released/#support-wildcards-when-including-yaml-cicd-configuration-files

**Comment by katrinleinweber** [comment]
Just to provide a search landing site: `Local include file cannot be found` seems to be the error (as of v4.26.1) when trying to run a job in a repo that uses that feature.

As a possible workaround/prototype, I tried using the [CI Lint API](https://docs.gitlab.com/ee/api/lint.html#validate-the-ci-yaml-configuration):

```
curl --request POST --header "Content-Type: application/json" \
       --data "$(yq eval --output-format=json < .gitlab-ci.yml | jq --join-output '. | @sh')" \
    https://gitlab.com/api/v4/ci/lint
```

but I couldn't get the `--data` formatting right.

**Comment by alexander-matthiesen** [comment]
I will have a look at this.
