### ISSUE TITLE
--list jobs alphabetically, group by stages in order

### ISSUE THREAD

**Issue by atli-c** [firecow/gitlab-ci-local#201]
When running `gitlab-ci-local --list` the list of should:
- be grouped by stages
- stages should be in same order as in gitlab-ci YAML file
- order jobs alphabetically within a stage.

**Comment by firecow** [comment]
Lets hide all when:never jobs, unless developers call --list-all @atli-c

**Comment by firecow** [comment]
https://github.com/firecow/gitlab-ci-local/commit/2adceb6d8efd0c80c768da242cd0060a3c707439 --list-all added here
