### ISSUE TITLE
git commands in pipeline

### ISSUE THREAD

**Issue by moberghammer** [firecow/gitlab-ci-local#203]
Remote supports git commands in a pipeline. Remote does not.
eg.
job1              $ git remote -v
job1              > fatal: Not a git repository (or any parent up to mount point /builds)

**Comment by jboyens** [comment]
Yup. Running into this as well, it looks like the .git directory isn't being rsync'd over.

**Comment by jboyens** [comment]
The offending line is here: https://github.com/firecow/gitlab-ci-local/blob/master/src/utils.ts#L155

It excludes the .git directory.

**Comment by bcouetil** [comment]
Yes, we excluded it because it was unneeded... until this issue 😅

**Comment by jboyens** [comment]
Welp. If it helps, tweaking that line fixes my build that depends on the .git directory (probably wrongly, but :shrug:)

**Comment by firecow** [comment]
Lets re-add it 😀

**Comment by firecow** [comment]
https://github.com/firecow/gitlab-ci-local/commit/ec3cbf181dddae0ca76c2b61cccbdaae7a42287d Done
