### ISSUE TITLE
Variables with values that contain spaces break the docker command line

### ISSUE THREAD

**Issue by jboyens** [firecow/gitlab-ci-local#204]
When running a build that uses a variable (specified in the `$HOME/.gitlab-ci-local/variables.yaml`) that is long and/or complex (specifically JSON) breaks the command-line generation for the docker command.

We have a variable in our group configuration that is a JSON file. It works fine as a value type variable (not file type) in our GitLab CI/CD pipeline.

If I attempt to use YAML's multline strings output with the JSON blurb, gitlab-ci-local will complain that the repository name must be lowercase when attempting to run the build. My guess, is that the variable is somehow corrupting the command string that is getting passed into Docker. I attempted to force it to a single-line, I tried shell-escaping it, I tried converting it to a file type variable (the container could not see the file), unfortunately, nothing I tried would successfully drive the variable into the container properly.

My workaround was to base64 the JSON and using that as the variable's value and temporarily changing my CI script to base64 decode it before using it. This got around the corruption, but means that running locally needs "tweaks".

**Comment by firecow** [comment]
I've came across encoding issues and docker run -e/--env-file in the past.
Can you give an example of your variables.yml?

**Comment by jboyens** [comment]
```
global:
  BROKEN_VAR: |
    {
      "private_key": "-----BEGIN PRIVATE KEY-----\n",
    }
```

In attempting to minimize it, this is where I got to. It seems to be around spaces appear in the JSON value. You can minimize it even further by changing the value to: `"-----BEGIN "`.

I did also notice that newlines (`\n`) embedded in the variable were un-escaped into the container and arrived as just `n` which would really mess up private keys or PEM files as they get passed in.

**Comment by jboyens** [comment]
You can see the second error by using this:
```
global:
  BROKEN_VAR: |
    {
      "private_key": "000\n000",
    }
```

and you'll observe that inside the container you get:
```
build $ echo $BROKEN_VAR
build > { private_key: 000n000, }
```

**Comment by bcouetil** [comment]
I solved this a while ago, testing every possible  here is my workaround : 
- transform as one-liner using `\n` (easy for JSON, most of the time `\n` are not needed, except for stuffs like private keys)
- escape `"` : replace them with `\"`
- put simple quotes around the whole variable content

Example :

```
global:
  GOOGLE_CREDENTIALS: '{ \"type\": \"service_account\", \"project_id\": \"sharxxx\", \"private_key_id\": \"e3feeb2xxx\", \"private_key\": \"-----BEGIN PRIVATE KEY-----\nxxx\nyyy\nzzz\n-----END PRIVATE KEY-----\n\", \"client_email\": \"aaa@xxx.iam.gserviceaccount.com\", \"client_id\": \"ccc\", \"auth_uri\": \"https://accounts.google.com/o/oauth2/auth\", \"token_uri\": \"https://oauth2.googleapis.com/token\", \"auth_provider_x509_cert_url\": \"https://www.googleapis.com/oauth2/v1/certs\", \"client_x509_cert_url\": \"https://www.googleapis.com/robot/v1/metadata/x509/sasasa.iam.gserviceaccount.com\" }'
 ```
 
 Funny thing : When investigating at that time, before finding this solution, `BEGIN ` (with the space) seemed to generate, on its own, a weird specific behavior 😅

**Comment by firecow** [comment]
Try this out https://github.com/firecow/gitlab-ci-local/commit/e82b4fa23711492ff8961dc6a1d5e7a7ca25d862
@bcouetil @jboyens 
If problems still persist, reopen the issue :smile:

**Comment by firecow** [comment]
@bcouetil I don't seem to be able to reproduce this.. 
Is it still present ?

**Comment by firecow** [comment]
Also I'm an idiot :smile: Fix incoming

**Comment by firecow** [comment]
I'm an idiot https://github.com/firecow/gitlab-ci-local/commit/b6c8c0c8b12277046082178f350b81b19cef2f9b fix here :smile:

**Comment by bcouetil** [comment]
Tested, approved ✅🙏
