### ISSUE TITLE
Override "entrypoint" cause on odd error

### ISSUE THREAD

**Issue by jboyens** [firecow/gitlab-ci-local#206]
I'll be honest here, I've done a little investigating, but this one is beyond me.

Using a build step that defines a service with an entrypoint, I received this error:
```
services:entrypoint must be an array
```

But, my entrypoint is most definitely an array:
```yaml
      entrypoint:
        - 'docker-entrypoint.sh'
        - '-c'
        - 'fsync=off'
        - '-c'
        - 'shared_buffers=256MB'
```

(I originally used the compact array syntax here to no avail)

I added some logging to src/service.ts:
```typescript
@ src/service.ts:21 @ export class Service {
        if (!this.serviceData || !this.serviceData.entrypoint) {
            return null;
        }
        console.log(this.serviceData);
        console.log(this.serviceData.entrypoint);
        console.log(typeof this.serviceData.entrypoint);
        assert(typeof this.serviceData.entrypoint !== "object", "services:entrypoint must be an array");
        return this.serviceData.entrypoint;
    }
```

and the resulting output:
```typescript
{
  name: 'xxx:latest',
  entrypoint: [
    'docker-entrypoint.sh',
    '-c',
    'fsync=off',
    '-c',
    'shared_buffers=256MB'
  ],
  command: undefined,
  alias: undefined
}
[
  'docker-entrypoint.sh',
  '-c',
  'fsync=off',
  '-c',
  'shared_buffers=256MB'
]
object
```

So I commented out the assertion and was greeted with:
```
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "shared_buffers=256MB": executable file not found in $PATH: unknown.
```

**Comment by jboyens** [comment]
I think I've pinned this down.

On line https://github.com/firecow/gitlab-ci-local/blob/0ad400d3f8b66c87a61a1fbcaa5530a2d8402719/src/job.ts#L614-L616 the entrypoint array is added to the Docker command line with each item being a separate entrypoint command, when the array should be joined and a single entrypoint added instead

**Comment by firecow** [comment]
Can you illustrate how a `docker run` command would look like ? (Using your above "example")

**Comment by firecow** [comment]
@jboyens Ping :arrow_up:

**Comment by firecow** [comment]
@jboyens Or maybe just a `.gitlab-ci.yml` illustrating the exact problem, then I would be able to do some better 'guesswork' :smile:

**Comment by ghillb** [comment]
I think I have encountered a related issue. This .gitlab-ci.yml, for a static site build with hugo, works on gitlab.com, but not with gitlab-ci-local:
```
stages:
- build

build-static-site:
  stage: build
  image:
    name: klakegg/hugo:0.83.1-busybox
    entrypoint: ["/bin/sh", "-c"]
  variables:
     GIT_SUBMODULE_STRATEGY: recursive
  script:
    - hugo -D --source hugo
  artifacts:
    expire_in: 1 days
    paths:
      - hugo/public
```
It causes this error:
```
Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "-c": executable file not found in $PATH: unknown
```

**Comment by firecow** [comment]
@ghillb 
What would that job translate to in terms of a docker run command?

```
docker run --entrypoint "/bin/sh -c" klakegg/hugo:0.83.1-busybox "hugo -D --source hugo"
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/bin/sh -c": stat /bin/sh -c: no such file or directory: unknown.
ERRO[0000] error waiting for container: context canceled 
```

The error produced here, isn't the outcome we wan't, I imagine :smile:

**Comment by cpontvieux-systra** [comment]
The problem in the code is that the `forEach` is misplaced.
An entrypoint could have a list of values, but that list should be joined and passed as a single string to `--entrypoint` command line option

**Comment by cpontvieux-systra** [comment]
In the meantime, you can use `['/usr/bin/env']` in `entrypoint` and then use `/bin/sh -c` in the command. But that’s not exactly the same…

**Comment by firecow** [comment]
I know, the "problem"...

I just don't know, how to translate the CI `image: { entrypoint: [] }` list into internal docker create/exec commands.

**Comment by cpontvieux-systra** [comment]
It translates to `docker run --entrypoint '' ...` (this two single quotes)

and `image: { entrypoint: ['foo', 'bar'] }` translates to `docker run --entrypoint 'foo bar' ...` You can join the list to a string with space as a separator.

**Comment by firecow** [comment]
@cpontvieux-systra Yes, that i know...
My problem arises when `entrypoint: ["/bin/sh", "-c"]` contains an "option" last.

How does that translate into a docker run command ?

**Comment by firecow** [comment]
Basicly... I need this
```yml
---
build-static-site:
  image:
    name: klakegg/hugo:0.83.1-busybox
    entrypoint: ["/bin/sh", "-c"]
  script:
    - hugo -D --source hugo
```

to result in this

![image](https://user-images.githubusercontent.com/973602/133384861-92aca0ce-828b-4c03-9244-c8c45e1cec4d.png)

From a "simple" docker run command.

**Comment by cpontvieux-systra** [comment]
Sorry my bad. Only the first argument on `entrypoint` list should be kept in `--entrypoint` command line, the rest should be prepended to the `command`.

So this will translates to:
```sh
docker run --rm --entrypoint '/bin/sh' klakegg/hugo:0.83.1-busybox -c "hugo -D --source hugo"
```

**Comment by firecow** [comment]
Crap... This will need a major refactoring in how i pass `scripts:` into docker containers...
But I'll get it done :smile:
