### ISSUE TITLE
--no-cleanup option

### ISSUE THREAD

**Issue by moberghammer** [firecow/gitlab-ci-local#207]
Add a --exec option to debug a docker executor job.

eg. 
`gitlab-ci-local some-job --exec bash` would run the docker command with -it and --exec <any shell or command>

**Comment by firecow** [comment]
@moberghammer Are we talking about an interactive debug mode, where you are able to run commands from within the "job" container?

**Comment by moberghammer** [comment]
Yes to debug interaction with services, artifacts and other ressources

**Comment by Snurppa** [comment]
Another kind of wish that came up to my mind regarding debugging services. 

Maybe some switch like `--no-rm` to skip the removal of (some, eg service) containers so after the pipeline has been run, it would be possible to examine what kind of logs were output by the service containers with `docker logs <container-id>`. Now the `cleanupResources` will remove containers in every situation after running. Or maybe I could somehow use that `@Interactive` decorator to achieve this? 

Anyways, not sure if that is good or bad idea. And there might be already a way to debug the service containers, that I just did not realize yet? Do you think this could be another feature issue if this sounds feasible? Thanks again!

**Comment by firecow** [comment]
```
--no-cleanup
```
Would be a great option...

**Comment by firecow** [comment]
We should just always put container logs in .gitlab-ci-local/container_logs/
