### ISSUE TITLE
CI_COMMIT_REF_NAME not populated correctly when branch name has a slash

### ISSUE THREAD

**Issue by tOmoness** [firecow/gitlab-ci-local#209]
If I have a branch named something like `task/my_awesome_branch` the CI_COMMIT_REF_NAME predefined variable just says `task`.

**Comment by firecow** [comment]
Roger that 👍 Will get that fixed right up...

**Comment by firecow** [comment]
@tOmoness here you go https://github.com/firecow/gitlab-ci-local/commit/7b8d262e54520310cbb8f76d5a0956d4f2fd6f7e
