### ISSUE TITLE
File variables in docker containers

### ISSUE THREAD

**Issue by finduspedersen** [firecow/gitlab-ci-local#214]
I have defined a "file variable" in ~/.gitlab-ci-local/variables, and the file content is correctly copied to /path/to/project/.gitlab-ci-local/file-variables/<name>. Unfortunately the content of this directory does not seem to be copied to new docker containers created when "gitlab-ci-local" is executing.

Is this an error or is there something which I just don't understand?

**Comment by firecow** [comment]
You might have stumbled upon something.
But I don't quite understand the problem in-depth i'm affraid.
Can you paste me your `~/.gitlab-ci-local/variables.yml` (anonymized) and a `.gitlab-ci.yml` file that  illustrates the issue? @finduspedersen

**Comment by finduspedersen** [comment]
Here you have a zip-file with variables.yml and .gitlab-ci.yml.

When running gitlab-ci-local, I get this output:

  $ gitlab-ci-local
  parsing and downloads finished in 122 ms
  test-job starting docker:19.03.5-dind (test)
  test-job pulled docker:19.03.5-dind in 217 ms
  test-job copied source to container in 522 ms
  test-job copied artifacts to container in 534 ms
  test-job $ echo Value: ${OS_RELEASE_FILE}
  test-job > Value: .gitlab-ci-local/file-variables/os-release
  test-job $ cat ${OS_RELEASE_FILE}
  test-job > cat: can't open '.gitlab-ci-local/file-variables/os-release': No such file or directory
  test-job finished in 5.99 s  FAIL 1

As you see, the file .gitlab-ci-local/file-variables/os-release is not available in the docker-container.
[mytest.zip](https://github.com/firecow/gitlab-ci-local/files/6864619/mytest.zip)

**Comment by firecow** [comment]
I'm pretty sure file variables have never worked ever since, we added --exclude .gitlab-ci-local to `.docker` folder's rsync command.

**Comment by finduspedersen** [comment]
I can confirm that the issue is now solved and that I can access the file variables that I need.
Thank you for your help - and for a great product :-)
