### ISSUE TITLE
Shell-executor build folder isolation

### ISSUE THREAD

**Issue by MoritzBrueckner** [firecow/gitlab-ci-local#22]
First of all thanks for this great tool, it's awesome :)

I wish there would be a way to let the pipeline run in another isolated directory so that changes done by the pipeline don't affect the repository itself.

For example the command could look like this:
```
gitlab-ci-local --dir build
```
This would then create a directory called `build`, copy the project's content into it and run the pipeline in that directory.

**Comment by firecow** [comment]
Shouldn't be to hard to make.
Only problem being the duration of the copy operation if the project gets too "big".
Gimme a few days, and you will have it.

**Comment by MoritzBrueckner** [comment]
I think even without rsync this will probably be faster than the cloning Gitlab does when the pipeline is run so it probably isn't that much of a problem.

> May I ask, what you aren't trying to achieve by using such an option? Are your pipelines changing "tracked" files?

I use this tool for debugging and currently my pipeline clones some other dependencies which then are cloned into the project's working directory, so I have to manually delete them after testing the pipeline (which is a bit annoying). With the proposed switch you could just create a new folder and add it to gitignore.

Also, pipelines might rename files or change their content which can be cumbersome to reverse by hand.

**Comment by firecow** [comment]
That's what I thought.
I think, we would have to recreate what an actual runner does, and that is to create a folder for each job, when they are run simultaneously.

**Comment by firecow** [comment]
4.9.5 contains job isolation via /build/ folders for docker-executor.
Are you using shell-executor in your use-case @MoritzBrueckner

**Comment by MoritzBrueckner** [comment]
Thanks! Yes, I think I was using shell-executor. Now I'm using docker but I guess that such feature should be available for all executor types.

**Comment by firecow** [comment]
Yes, job isolation must be possible in shell-executor as well
