### ISSUE TITLE
Doesn't support `include` shorthand

### ISSUE THREAD

**Issue by KTamas** [firecow/gitlab-ci-local#225]
This doesn't work:

`include: '/ci/shared/cache_variables.yml'`

Error message: `Didn't understand include "/"`

this is "[Single string with the include:local method implied](https://docs.gitlab.com/ee/ci/yaml/includes.html)"

This does work:

```
include:
  - local: '/ci/shared/cache_variables.yml'
```

**Comment by firecow** [comment]
https://github.com/firecow/gitlab-ci-local/commit/42bc8f51e43847302dddc081da56bb4615c641b8

![image](https://user-images.githubusercontent.com/973602/130664740-1facb155-655f-4be2-a81e-574d53ec244e.png)
