### ISSUE TITLE
needs: { job: value, artifacts: true }

### ISSUE THREAD

**Issue by ColdIce1** [firecow/gitlab-ci-local#232]
See: [Artifact downloads with needs ](https://docs.gitlab.com/ee/ci/yaml/#artifact-downloads-with-needs).

Test:
```build_job:
  stage: build
  script:
    - "mkdir build"
    - "echo building >> build/file"
  artifacts:
    paths:
      - build/

release:
  stage: test
  needs:
    - job: build_job
      artifacts: true
  script:
    - "ls"
    - "echo finished building"
```

**Comment by firecow** [comment]
Is this syntax new?

None the less, `needs: [build-job]` will download the artifacts, for now, use that syntax until I have implemented this "new" way ... @ColdIce1

**Comment by ColdIce1** [comment]
Not new, introduced in: GitLab 12.6. 
Thanks for the suggestion!

**Comment by firecow** [comment]
Done https://github.com/firecow/gitlab-ci-local/commit/7a684cefe635199dcec13b0ef68f7cac0b283150 @ColdIce1
