### ISSUE TITLE
cache != artifacts

### ISSUE THREAD

**Issue by Snurppa** [firecow/gitlab-ci-local#233]
I think there is a misunderstanding baked in `execScripts`. It tangles cache and artifacts, because this line https://github.com/firecow/gitlab-ci-local/blob/master/src/job.ts#L596 expects that for a job `artifacts:` is defined before any "cache items" are copied anywhere. 

If you have a job with `cache` defined but no `artifacts`, the files are not actually "cached" between runs/jobs. This is because the actual `cacheMount` copying is inside the `if (... this.artifacts.paths.length > 0) {`  clause.

For example if you would run this [npm depedencies](https://docs.gitlab.com/ee/ci/caching/index.html#cache-nodejs-dependencies) job again and again with this tool, it would download the dependencies every time again and again, although it should not do that because the initial dependencies should be already present from host in the `cacheMount` and thus visible for `npm` subsequent run.

I bumped into this problem when running subsequent runs and was confused because it downloaded deps on every invocation, although the `cache` configuration works correctly in actual GitLab. It took a while to spot the "bug" in the source code 😸 

I think I might be able to come up with PR, but did not do that yet because I don't understand enough what happens and why with the artifacts copying here: https://github.com/firecow/gitlab-ci-local/blob/master/src/job.ts#L596-L641. Especially because in my mind, the artifacts and the cache are actually two different things 🙂 

Anyways, thanks very much for the tool, it is really helpful! And tell me what you think about this finding.

**Comment by firecow** [comment]
@Snurppa 
Artifacts and cache's are two different things.

But if you have artifacts, that live inside a cached folder via docker mounts, we need to have the docker mount present, when copying artifacts into `.gitlab-ci-local/artifacts`

Do you have an `.gitlab-ci.yml` and some bash commands that can reproduce/display the issue you are experiencing ?

**Comment by Snurppa** [comment]
Thanks! I came up with very simple setup, and the caching seems to work fine, the deps are, like it should be, **not** downloaded between runs https://gitlab.com/Snurppa/local-ci-test. Will still try to compare difference to our bigger project and gitlab.yml and see if I can get an actual reproduction of the issue I'm seeing with that (deps downloaded every time).

**Comment by Snurppa** [comment]
Okay I'm sorry for barking at the wrong tree. The problem was indeed on my end. I was downloading Maven deps. I had an artifact that contains the "local repository" folder, it was defined as: `$CI_PROJECT_DIR/.m2`. It was in a separate job. Now when another job started to download the deps and the CI_PROJET_DIR will be set to `/builds/${this.safeJobName}` in this tool, it was downloading deps into different folder compared to what was expected by `cache:` declaration. That's why I was always seeing deps downloaded again and again. The cache indeed works correctly, problem was between where I was downloading deps and the `cache:` declaration.

I _think_ the cache works on GitLab itself, so maybe the `CI_PROJECT_DIR` has different semantics there compared to local. Have to check that too though, might have same issue there 🙂
