### ISSUE TITLE
Cannot run example

### ISSUE THREAD

**Issue by savalik** [firecow/gitlab-ci-local#241]
I installed gitlab-ci-local via npm and am trying to run the example but it doesn't work:

![image](https://user-images.githubusercontent.com/2318480/134697893-65b23ef1-11ca-49e3-9f2d-6a80b848bd1c.png)

Can I debug it somehow? Or maybe you can add some log output?

**Comment by firecow** [comment]
Looks like you are using Windows. @savalik 
Can you try gitbash?

**Comment by savalik** [comment]
Thanks! It's work in gitbash, I forgot about it, sorry.
