### ISSUE TITLE
Tab completion not working, without running any gitlab-ci-local command beforehand

### ISSUE THREAD

**Issue by nizacegodk** [firecow/gitlab-ci-local#243]
Probably a very nice-to-have feature/bug-fix.

But auto completion does not work, if you bump the tag reference of a include statement. You need to run a command such as `gitlab-ci-local --list` before tab completion begins to work again.

It would be nice if the auto completion script would pull the required dependencies if they were missing, when trying to auto complete.

**Comment by firecow** [comment]
How often should the "includes" be re-fetched when in "tab-completion" mode.
We can't do it on every tab, since it would delay the result display quiet a bit.

**Comment by nizacegodk** [comment]
A perfect solution that is both always correct and fast, is probably not possible. But I still think we should extend the normal behaviour for tab to the initial tab also.

So I propose that the only time that the files are fetched in tab-completion mode, is when the files are not present.
The current behaviour of tab-completion could be argued to already be implemented this way, since files are never refetched in tab-completion mode. And this only add an initial fetch, and none refetches.
