### ISSUE TITLE
--lint option or json schema check

### ISSUE THREAD

**Issue by moberghammer** [firecow/gitlab-ci-local#264]
**Is your feature request related to a problem? Please describe.**
My pipeline fails with gitlab ci yaml lint errors

**Describe the solution you'd like**
An --lint option that calls gitlab with my private token

**Describe alternatives you've considered**
git push and see error in gitlab

**Additional context**
https://www.npmjs.com/package/gitlab-ci-lint

**Comment by firecow** [comment]
Since gitlab-ci-local is made to find errors pre contacting gitlab, we will close this card.

**Comment by hverlin** [comment]
An alternative is to use e.g. the VSCode extension. 
https://docs.gitlab.com/ee/user/project/repository/vscode.html

However, I have found that the GitLab API was not really useful (https://docs.gitlab.com/ee/api/lint.html#yaml-expansion) as it has the following limitation:
> The expansion does not work for CI configuration added with [include: local](https://docs.gitlab.com/ee/ci/yaml/index.html#includelocal), and the [extends:](https://docs.gitlab.com/ee/ci/yaml/index.html#extends) keyword is [not fully supported](https://gitlab.com/gitlab-org/gitlab/-/issues/258843).

**Comment by hverlin** [comment]
My understanding is that just doing `--list` will eventually catch all errors that GitLab reports? (e.g., #859)

**Comment by bcouetil** [comment]
It is exactly what I'm doing for this usage, indeed.

**Comment by firecow** [comment]
> My understanding is that just doing `--list` will eventually catch all errors that GitLab reports? (e.g., #859)

Yes, exactly... 
gitlab-ci-local should blow up straight in the face 👍
