### ISSUE TITLE
Backslash escaping

### ISSUE THREAD

**Issue by Livan-pro** [firecow/gitlab-ci-local#266]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
job:
  script:
    - echo "\""
```

**Expected behavior**
Successful run.

**Host information**
Ubuntu
gitlab-ci-local 4.24.0

**Additional context**
gitlab-ci-local fails running job with message:
```job > ./.gitlab-ci-local/scripts/job: line 4: unexpected EOF while looking for matching `"'```
Line 4 of ./.gitlab-ci-local/scripts/job:
```echo "[32m$ echo \"\\"\"[39m"```
I think it's failing because backslash keeps unescaped in this echo command.
So changing https://github.com/firecow/gitlab-ci-local/blob/67a7048c916e394b2be12c71fbfede7b5e9aaf9f/src/job.ts#L381 to:
```typescript
const text = split[0]?.replace(/[\\]/g, "\\\\").replace(/["]/g, "\\\"").replace(/[$]/g, "\\$");
```
should fix this.

**Comment by firecow** [comment]
@Livan-pro https://github.com/firecow/gitlab-ci-local/commit/8a8c7c56326ec1f5b3de63c4f6d77938238d6d78 Here you go :smile:
