### ISSUE TITLE
Counterintuitive git add required to pick up local changes

### ISSUE THREAD

**Issue by pcuci** [firecow/gitlab-ci-local#271]
Had renamed a couple files and they disappeared 
![image](https://user-images.githubusercontent.com/2169849/137022474-ab40d31b-a7c6-4cc7-92ab-0d86130259ec.png)

![image](https://user-images.githubusercontent.com/2169849/137022595-0351a2c3-676a-4a8c-943a-760df8454fff.png)

After a `$ git add -A :/` all changes I made became available inside gitlab-ci-local

![image](https://user-images.githubusercontent.com/2169849/137022767-5b9a658a-0161-46e0-ad51-a80bfc6ff2dc.png)

Perhaps this is the desired behavior and I missed some docs explaining how local changes get ingested by gitlab-ci-local?

Thanks, not sure how to reproduce

**Comment by firecow** [comment]
I shall add to the README.md, that untracked/ignored files, will not be copied inside the jobs.
This is the desired behavior.
