### ISSUE TITLE
--outdated-include option

### ISSUE THREAD

**Issue by moberghammer** [firecow/gitlab-ci-local#289]
**Is your feature request related to a problem? Please describe.**
To keep includes updated to latest version in an easy way.

**Describe the solution you'd like**
The ref part of include tags is updated to latest semantic version.

**Describe alternatives you've considered**
This could be a list of possible updates.

**Additional context**
N/A

**Comment by moberghammer** [comment]
I have versioned modules that I include

**Comment by firecow** [comment]
--outdated-include would be the the options we are looking for.
```
npm outdated
composer outdated
```

I'm considering this extremely nice-to-have, and will probably not work on it any time soon :smile:

**Comment by firecow** [comment]
I'm closing this, I think its kindda out of scope. 

Its probably better that this feature is a completely different application.

`npm install -g gitlab-include-update-checker` or something like that.
