### ISSUE TITLE
Store caches in a named volume instead of the host on macOS

### ISSUE THREAD

**Issue by deviantintegral** [firecow/gitlab-ci-local#305]
**Is your feature request related to a problem? Please describe.**

#286 fixed caches by ensuring they persist across containers by storing the cache on the host. Unfortunately, Docker Desktop on macOS has _incredibly_ poor filesystem performance. For example, a job that caches composer's vendor directory that normally takes around 1 minute took 10 minutes to run. I'm sure it's similar with npm and other package managers that have many small files.

**Describe the solution you'd like**
Instead of storing caches on the host FS, store them in a Docker volume. This sidesteps performance issues on macOS.

**Describe alternatives you've considered**
 #286 could be reverted, or made optional, because for many users simply not caching will be much faster than using a host mount.

**Comment by bcouetil** [comment]
Interesting ! So a docker volume is not backed by FS ? Or not the same way ?

And I bet that #283 would be even more a problem, since it implies files syncing ? Could you try it ?

**Comment by deviantintegral** [comment]
Since Docker relies on linux kernel features, it has to be run inside of a VM on macOS. That means there needs to be some bridge to the host filesystem beyond bind mounts. Docker for Mac has `osxfs` which is unfortunately pretty slow: https://github.com/docker/roadmap/issues/7

Our development team has switched to using Mutagen for code syncing, which is basically "rsync as a persistent daemon".

Docker named volumes (and containers, and images, basically anything not mounted from the host) are stored inside a qemu qcow2 image which is basically as fast as native IO.

**Comment by bcouetil** [comment]
Seems a great idea.

A drawback, I guess, is that we would lose the cache on a `docker system prune`, and I heavily rely on that for gitlab-ci-local dangled containers...

**Comment by firecow** [comment]
@bcouetil Only `docker system prune --volumes` would clear internal docker volumes...

This would be a good option for MacOS users

**Comment by bcouetil** [comment]
Yes please for linux too 🤩

**Comment by bcouetil** [comment]
I was thinking of this subject, and if and when we implement this, we should offer some sort of user-initiated cache cleanup, since it becomes more complex than emptying a `/tmp/xxx` folder.

**Comment by firecow** [comment]
Yup like `--clean-cache` or something like that.
