### ISSUE TITLE
Mock external dependencies, making local testing easier

### ISSUE THREAD

**Issue by aepfli** [firecow/gitlab-ci-local#314]
Currently there are two repositories/projects you actually need for testing this project.

1. this repository
2. data within https://gitlab.com/firecow/gitlab-ci-local-includes for include testing

### Generally this is a fine approach but it has some downsides?

- if your change is also inflicting the 2 repo you have to merge requests, which need to be somehow in sync.
- the refs might get deleted on the testing repository, which are needed for the test, and how do you know which one you should use.
- the test-data-repository might be out of sync for a certain period of time, due to different branches with different changes in repo 1

### Proposal

instead of an own project, we could fork this repository to GitLab with an automatic mirror. This way we can have test-data and project code within the same repository. Additionally test changing data from maintainers could use the same `ref` for the includes and load the test data out of the same branch, just from gitlab.

Downsides is, that the includes might add additional paths, as we do not want to have this includes on the root level.

### Additional thoughts

This is just a proposal, which might improve the ability for externals to contribute. Additionally we could also provide a special test overwrite, where we load the file from the filesystem if there is no `CI` environment variable. This way we would also reduce the initial dependency to gitlab for local development.

**Comment by firecow** [comment]
I think mocking the curl/git archive requests would be an even better way to get around this issue. @aepfli

**Comment by firecow** [comment]
I'm renaming this issue and making it a Feature @aepfli

**Comment by aepfli** [comment]
> I do however think that mocking the curl/git archive requests would be a better way to get around them.

actually the best idea :D sometimes you cannot see the wood for the trees - lets see if i get some time during the austrian lockdown :)

**Comment by firecow** [comment]
@aepfli No rush :smile: The tests are working with a little local setup.

**Comment by aepfli** [comment]
```
    const downloadIncludeProjectFile = jest.spyOn(ParserIncludes, "downloadIncludeProjectFile");
    when(downloadIncludeProjectFile)
        .calledWith(expect.any(String), expect.any(String), expect.any(String), expect.any(String), expect.any(GitData))
        .mockImplementation((cwd: string, project: string, ref: string, file: string, gitData: GitData) =>  {
            const remote = gitData.remote;
            const target = `.gitlab-ci-local/includes/${remote.host}/${project}/${ref}/`
            fs.ensureDirSync(target);
            const normalizedFile = file.replace(/^\/+/, "");
            return fs.copyFile(`${cwd}/../../includes/${project}/${normalizedFile}`, `${cwd}/${target}/${normalizedFile}`);
        });
```
looks like the correct mock for downloading the one source - if i mock the whole function - but i will dig deeper into mocking the utils spawn within the parser-includes :) - i just persist this here for now :)
