### ISSUE TITLE
Question about debug/verbose mode

### ISSUE THREAD

**Issue by synergiator** [firecow/gitlab-ci-local#324]
Tried to run a pipeline which uses a template file shipped within every GitLab instance:
```
...
include:
  - template: Terraform.latest.gitlab-ci.yml
...
```
So, this template file is not contained in projects which use it. Admittedly, no idea how to simulate this scenario properly. But, runners resolve that somehow, I tried this also in an out-of-the-box runner installation so possibly GitLab can send it to its runner on request.

Running ```gitlab-ci-local``` produces in this case a very short output - just this one line:

```
stage:cleanup not found for destroy
```
What was it trying to do? Is there an option for a more verbose/debug output?

**Comment by firecow** [comment]
`https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Terraform.latest.gitlab-ci.yml`
Includes `https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Terraform/Base.latest.gitlab-ci.yml` has a job in `stage: cleanup`
You are missing cleanup in your `stages: []` array. @synergiator
