### ISSUE TITLE
How to add environment variables?

### ISSUE THREAD

**Issue by zomars** [firecow/gitlab-ci-local#34]
Is it possible?

**Comment by firecow** [comment]
```
export VARKEY="somevalues"
gitlab-ci-local run-job-that-prints-var-key
```

Already works. Is this what you mean ?

**Comment by firecow** [comment]
@zomars Did you solve you problem? Can I close this?

**Comment by zomars** [comment]
@firecow I haven't tested it yet, but I will close it sure.

**Comment by khalo-sa** [comment]
> ```
> export VARKEY="somevalue"
> gitlab-ci-local run-job-that-prints-var-key
> ```
> 
> Already works. Is this what you mean ?

Hi @firecow , sorry to post in a closed issue, but I just tried the exact snippet you posted here, and it doesn't seem to work.  Echo $VARKEY in a script doesn't print the value. Do you think this is a bug or am I missing something?

**Comment by firecow** [comment]
You need to use the `--variable SOMETHING=thatthing` 😁

**Comment by khalo-sa** [comment]
Thank you, it works! Maybe it is worth mentioning this in the readme :)?

**Comment by firecow** [comment]
Maybe, maybe 😁

**Comment by khalo-sa** [comment]
Actually, it would be great if it was possible to specify in the `.gitlab-ci-local-variables.yml` that the project expects some variables to be set as env vars. E.g. via a reserved value:
```yaml
---
SECRET_ENV="<FROM-ENV>"
```

That way you could avoid passing the --variable for every secret your project might need.

Well, if you think that would be a useful addition I might try to implement it in the next weeks.

**Comment by firecow** [comment]
I think thats the purpose of $HOME/.gitlab-ci-local/variables.yml

**Comment by khalo-sa** [comment]
Yep, but since that config is not part of your project's repository, it's not shareable. It requires everyone in the team to create and populate that file.

**Comment by firecow** [comment]
You can share variables via remote variables file.

**Comment by firecow** [comment]
None the less...

If we want host variables injected into gitlab ci locally, we need a mechanism to specify which we want injected. 
Create a feature request 👍
