### ISSUE TITLE
Different behavior from gitlab-ci-local than docker run

### ISSUE THREAD

**Issue by jg-cantaa** [firecow/gitlab-ci-local#341]
![Screenshot_2021-12-15_12-15-33](https://user-images.githubusercontent.com/95756912/146177110-782df0e7-71e9-4342-94ff-8bfd6b2d8d73.png)
![Screenshot_2021-12-15_12-16-55](https://user-images.githubusercontent.com/95756912/146177105-e83ba70e-e4fc-4159-84a5-b27f3da94f86.png)

**Minimal Project Structure Archive:**
[Issue.zip](https://github.com/firecow/gitlab-ci-local/files/7718797/Issue.zip)

**Expected behavior**
Like run.sh: the container builds successfully

**Host information**
Linux: Pop!_OS 20.04 LTS
gitlab-ci-local 4.27.0

**Comment by firecow** [comment]
Now this is a awesome bug report :smile: Thanks @jg-cantaa for putting in the work...

**Comment by firecow** [comment]
Fixed in https://github.com/firecow/gitlab-ci-local/commit/aab75ea66fb31626d32ed1cde9028e541817d99e

**Comment by jg-cantaa** [comment]
Thanks for the Quick fix! Do you have an estimate for when I can expect this to be released?

**Comment by firecow** [comment]
Tonight :+1:
