### ISSUE TITLE
Print the last [x] lines for fail/warn jobs in end report for easier failure debugging

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#342]
![image](https://user-images.githubusercontent.com/973602/146336142-e93f06b1-e690-4f52-bb1e-2cc6c6e8c80c.png)

Here, we have no chance of seeing the actual problem, unless we start a painful up scrolling workflow.
It would be nice that the last x lines for `docker-image` was printed in the end report

**Comment by bcouetil** [comment]
It would be nice indeed 🥰
