### ISSUE TITLE
Error while launching a container

### ISSUE THREAD

**Issue by LionnelC** [firecow/gitlab-ci-local#380]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
stages:
 - build
with docker:
  image: _image1_
  script:
    - echo "Heya"
```
I leave the default example cause it is not dependent of that.

**Expected behavior**
Launch the container.

**Host information**
Ubuntu 20.04 deployed inside a WSL.
gitlab-ci-local 4.28.1

**Additional context**
Cloning a project under a enterprise edition of gitlab.
Path is simple: https://gitlabserver/group1/project1
Cloning the master branch.
But when launching the container he try to copy with " (fetch)" in the path.
Here is the log:

with docker starting _image1_ (build)
with docker pulled _image1_ in 204 ms
bash: -c: line 0: syntax error near unexpected token `('
bash: -c: line 0: `docker cp /tmp/gitlab-ci-local-file-variables-group1-project1 (fetch)/ 216ae4a77b099e0b14f826e98ce8030029439d9c2a0ca63f88e7b78ced0391cc:/tmp/gitlab-ci-local-file-variables-group1-project1 (fetch)//'

On another repo group1/subgroup1/subgroup2/project2 there is no pb. 
I propose the fix here: https://github.com/LionnelC/gitlab-ci-local
If you know why, I take it also.

I try to hard set CI_PROJECT_PATH_SLUG in the .gitlab-ci-local-variables.yml but it has no effect

**Comment by firecow** [comment]
@LionnelC 
Can you run `git remote -v` for me please 😁

**Comment by LionnelC** [comment]
Effectively, I got something strange like that:

origin  https://gitlabserver/group1/project1 (fetch)
origin  https://gitlabserver/group1/project1 (push) 

But yes I realize that I forgot the '.git' at the end... With the good origin it doesn't require the fix.
Thanks a lot !
Do I close it without the fix ?

**Comment by firecow** [comment]
Nah, just close the pull request.
This issue will stay, we actually want to support "remotes" specified in this manner.
