### ISSUE TITLE
File variables for service containers

### ISSUE THREAD

**Issue by LimmaPaulus** [firecow/gitlab-ci-local#384]
Hi!
Is there any way to inject file variables not only to the main container but to services too? It seems that currently files are copied to volume which is bound only to the main container, right? So when I setup .gitlab-ci-local-variables.yml like this:
```
SOME_FILE_VARIABLE: '/path/to/file.json'
```
I can now read the file from path $SOME_FILE_VARIABLE in the main container, but in the service container, the file doesn't exist although the variable itself is readable.
My use case: one of my services requires a long JSON-configuration, which is saved to file.

**Comment by firecow** [comment]
It should be possible to get "file variables" mounted into service containers, yes...

**Comment by firecow** [comment]
@LimmaPaulus Can you try out https://github.com/firecow/gitlab-ci-local/pull/390 before I'm merging it to master.

**Comment by LimmaPaulus** [comment]
Thanks! How should I do this exactly? I tried `yarn global add https://github.com/firecow/gitlab-ci-local.git`, but it didn't make executable to ~/.yarn/bin
