### ISSUE TITLE
Name service containers by aliases

### ISSUE THREAD

**Issue by LimmaPaulus** [firecow/gitlab-ci-local#385]
I had a hard time debugging why one of my service containers didn't start as expected. IntelliJ Docker GUI made this easier, but because I had quite a handful of services in my job, it wasn't too easy to find the correct one after startup.

![image](https://user-images.githubusercontent.com/14800398/153548854-02cd9f9b-d5f6-48ef-a73d-d66dd4a0a6cd.png)

It would be nice if each container got a name derived from the alias, maybe run ID or similar as a prefix

![image](https://user-images.githubusercontent.com/14800398/153549024-abb9e8bf-ab89-4545-823c-d31434ad5e1b.png)

**Comment by firecow** [comment]
When this feature is implemented, remember to test for docker's max hostname length limit.

**Comment by firecow** [comment]
This doesn't seem to be a particularly active issue. I'm closing for now.
Anyone finding this feel free to reopen.

**Comment by timkinnane** [comment]
Sorry to poke this long dormant issue, but I would like this too fwiw.

It seems possible to set the container name if using docker-in-docker with Gitlab CI, but if you're just using the simple format like `image: node:22-bookworm` then you'll get random generated container name every time, like `clever_hofstadter` or `musing_sanderson`.

I use a UI to monitor running docker containers and history. It's not a massive issue but the random names are just polluting that view.
