### ISSUE TITLE
send informational output to stderr

### ISSUE THREAD

**Issue by meleu** [firecow/gitlab-ci-local#409]
I'd like to suggest that the output produced in the line 58 here to go to stderr instead of stdout.

https://github.com/firecow/gitlab-ci-local/blob/34cf128ee2d2376891926dc09e3f8e952ca866f6/src/parser.ts#L51-L61

The usecase where I noticed this (not so serious) problem:

```bash
gitlab-ci-local --preview > effective-gitlab-ci.yml
```

Then the `effective-gitlab-ci.yml` starts like this:
```yaml
parsing and downloads finished in 52 ms
---
stages:
  - .pre
  - pre-action
  - install-dependencies
  # ...
```

**Comment by firecow** [comment]
Good idea, I'll squeeze that into 4.29.1... It makes perfect sense...
