### ISSUE TITLE
Dev folder is ignored from builds

### ISSUE THREAD

**Issue by Keydus-art** [firecow/gitlab-ci-local#430]
Hello here,

first of all thanks for this great tool which is very effective for my use case.

I'm using Magento2 and I'm facing a bug. Magento2 saves its test configuration in a folder named "dev" at the root of the project. It seems that this "dev" folder is not copied in the build. Whenever I'm modifying the folder from "dev" to "dav" then the folder is copied properly.

In my case, I cannot execute the tests with the configuration without renaming the folder to be copied in the build created by `gitlab-ci-local`

Does anyone have faced this issue yet?

**Expected behavior**
"dev" folder should be copied to the build folder

Thanks!
Keyde

**Comment by firecow** [comment]
Hey @Keydus-art
Folders in cwd called dev are copied to the CI job.
This must be an error at your end somehow.

I need you to provide what version of gitlab-ci-local, you are running, and what OS you are using.
Also try to deduce your `.gitlab-ci.yml` and project files to an absolute minimum, to make an as small as possible reproducible example, that I can use for bughunting.

This is what I'm getting, when trying to prove that a folder called "dev" is special
![image](https://user-images.githubusercontent.com/973602/163672671-6eb6657b-039c-4aa5-8fe8-91c20d6bad5e.png)

**Comment by moberghammer** [comment]
@Keydus-art Do you have a .gitignore file with the dev folder or a pattern that matches it?

**Comment by mcapronextzodiofr** [comment]
Hello,

I could not figure out why the dev folder was not showing, but after rebuilding my project (like with a whole git clean before recloning the project) it worked perfectly.

Sorry, that was my bad

Thanks for the help,
Keydus

**Comment by Keydus-art** [comment]
Hello,

I could not figure out why the dev folder was not showing, but after rebuilding my project (like with a whole git clean before recloning the project) it worked perfectly.

Sorry, that was my bad

Thanks for the help,
Keydus
