### ISSUE TITLE
--completion flag ignored

### ISSUE THREAD

**Issue by bcouetil** [firecow/gitlab-ci-local#434]
**Minimal .gitlab-ci.yml illustrating the issue**

Completion flag seems to be ignored in v4.30.1, and launches the pipeline instead. Did not have the issue in v4.28.0.

```
> gitlab-ci-local --completion
parsing and downloads finished in 90 ms
✅-casting-test                starting groovy:3.0-jdk8 (✅ test)
✅-casting-test                pulled groovy:3.0-jdk8 in 203 ms
✅-casting-test                pulled docker:20.10.12-dind in 198 ms
[...]
```

**Host information**
Ubuntu
gitlab-ci-local 4.30.1

**Comment by firecow** [comment]
This fix is already in master, coming with next release
