### ISSUE TITLE
Package as NPX tool

### ISSUE THREAD

**Issue by v4dkou** [firecow/gitlab-ci-local#47]
It would be useful to have this tool in NPM to be able to run it with `npx gitlab-ci-local`

- Automatic updates would be handled by NPM
- No need to install binaries (out of free software spirit or security concerns)
- No traces left after running, unless specifically installed it with `npm i -g gitlab-ci-local`

To do that, you basically need to add a runnable (in terms of POSIX shells) JS script that imports the dist, modify your package.json and publish the code as an NPM library.

Here's how I would do it
1. `touch cli.js`
2. `chmod +x cli.js`

3. Edit `cli.js`
```diff
+ #!/usr/bin/env node
+ require('./dist/index.js')
```

4. Edit `package.json`
```diff
{
  "name": "gitlab-ci-local",
  "main": "index.js",
+  "bin": "cli.js", 
  "scripts": {
    "pkg-linux", // ...
```
5. npm publish

I would have done it myself, but as you're the author, you should probably have the rights to name the package `gitlab-ci-local` yourself.

**Comment by firecow** [comment]
You are right. Especially npm install -g will make sense for people that already have the nodejs ecosystem installed.
Regular npm install won't make much sense though, since gitlab-ci-local "should" be responsible for running npm install in projects.
I'll publish it on npm.js soon.

**Comment by firecow** [comment]
@v4dkou Right, its on npmjs.org

**Comment by firecow** [comment]
@v4dkou Oh, wait I just fucked up :smile: It will be online in 24 hours
```
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/gitlab-ci-local - gitlab-ci-local cannot be republished until 24 hours have passed.
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mjn/.npm/_logs/2020-12-22T09_28_20_327Z-debug.log

```

**Comment by firecow** [comment]
@v4dkou https://www.npmjs.com/package/gitlab-ci-local Now it works. Have fun.

**Comment by v4dkou** [comment]
@firecow `npx gitlab-ci-local` works perfectly even without prior global installation, thanks!
