### ISSUE TITLE
Support remote inclusion

### ISSUE THREAD

**Issue by cs35-owncloud** [firecow/gitlab-ci-local#474]
Hello,

first thing first, thanks for this wonderful tool ! After trying to run a gitlab runner locally, your tool almost fully fits my needs.

I have one .gitlab-ci.yml that I include in several repositories, the main goal is to maintain only one file, it's pretty straightforward:

```
---
include:
  - remote: 'https://gitlab.xxx/-/snippets/xx/raw/master/.gitlab-ci.yml'
```

If I try to run this, there it goes:

```
$ gitlab-ci-local --volume "/var/run/docker.sock:/var/run/docker.sock" 
parsing and downloads finished in 242 ms

pipeline finished in 342 ms
```

I tried with the **--fetch-includes** but it doesn't seem to work either

```
$ gitlab-ci-local --volume "/var/run/docker.sock:/var/run/docker.sock" --fetch-includes
parsing and downloads finished in 209 ms
```

I might have used the wrong parameters, feel free to point my mistake.
Would you consider adding the support of [remote includes](https://docs.gitlab.com/ee/ci/yaml/includes.html) ?
Sorry if it lacks details, feel free to tell me what could be lacking.

Thanks !

**Comment by firecow** [comment]
I think this is some sort of auth issue...
Is your gitlab instance public?

**Comment by cs35-owncloud** [comment]
Thanks for your answer, my gitlab is private but the snippet can be accessed by anyone as of now.
I'll give it a try with some online pastebin and a basic CI/CD, back to you soon.
Thanks.

**Comment by firecow** [comment]
`.gitlab-ci-local-env`
```
VOLUME="/var/run/docker.sock:/var/run/docker.sock"
```

Can you give me a complete example, i've tested various remote files as includes, so it must be something specific to yours.

**Comment by cs35-owncloud** [comment]
Hello,

thanks, indeed it works ! Is it possible to set this variable inside **$HOME/.gitlab-ci-local** ? Just like **$HOME/.gitlab-ci-local/variables.yml**. I'd like to avoir setting **.gitlab-ci-local-env** in every repository it'd be working on. I could ofc set an export in .bashrc but I was looking for a "more" gitlab-ci-local way.

Sure, there you go:

```
---
include:
  - remote: 'https://pastebin.com/raw/YyWB4mCw'
```

If you try to use it this way:

```
gitlab-ci-local --volume "/var/run/docker.sock:/var/run/docker.sock"
```

or this one:

```
gitlab-ci-local --volume "/var/run/docker.sock:/var/run/docker.sock" debian9
```

It won't work.

If you copy the whole CI/CD in a real script, let's say **test.yml**

```
gitlab-ci-local --volume "/var/run/docker.sock:/var/run/docker.sock" --file test.yml
```
This won't work

But this one would:

```
gitlab-ci-local --volume "/var/run/docker.sock:/var/run/docker.sock" --file test.yml debian9
```

Thanks again !

**Comment by cs35-owncloud** [comment]
Hello,

thanks, indeed it works ! Is it possible to set this variable inside **$HOME/.gitlab-ci-local** ? Just like **$HOME/.gitlab-ci-local/variables.yml**. I'd like to avoir setting **.gitlab-ci-local-env** in every repository it'd be working on. I could ofc set an export in .bashrc but I was looking for a "more" gitlab-ci-local way.

Sure, there you go:

```
---
include:
  - remote: 'https://pastebin.com/raw/YyWB4mCw'
```

If you try to use it this way:

```
gitlab-ci-local --volume "/var/run/docker.sock:/var/run/docker.sock"
```

or this one:

```
gitlab-ci-local --volume "/var/run/docker.sock:/var/run/docker.sock" debian9
```

It won't work.

If you copy the whole CI/CD in a real script, let's say **test.yml**

```
gitlab-ci-local --volume "/var/run/docker.sock:/var/run/docker.sock" --file test.yml
```
This won't work

But this one would:

```
gitlab-ci-local --volume "/var/run/docker.sock:/var/run/docker.sock" --file test.yml debian9
```

Thanks again !

**Comment by firecow** [comment]
Well, I don't know of any better place than .bashrc export...

**Comment by firecow** [comment]
```
---
include:
  - remote: 'https://pastebin.com/raw/YyWB4mCw'
```
:arrow_up: This is the `.gitlab-ci.yml` I'm using to test the following two commands.

`gitlab-ci-local --volume "/var/run/docker.sock:/var/run/docker.sock"`
Works just fine...


`gitlab-ci-local --volume "/var/run/docker.sock:/var/run/docker.sock" debian9"`
Works just fine...

**Comment by cs35-owncloud** [comment]
> ```
> ---
> include:
>   - remote: 'https://pastebin.com/raw/YyWB4mCw'
> ```
> 
> arrow_up This is the `.gitlab-ci.yml` I'm using to test the following two commands.
> 
> `gitlab-ci-local --volume "/var/run/docker.sock:/var/run/docker.sock"` Works just fine...
> 
> `gitlab-ci-local --volume "/var/run/docker.sock:/var/run/docker.sock" debian9"` Works just fine..

It's odd, I might do something wrong and/or have some bad configurations out here. In my case, it goes as I explained previously.

![gitlab-ci-local](https://user-images.githubusercontent.com/50915359/169777580-6128825e-d1ec-46d4-9aa7-058d2f56e79f.png)

But it's fine, I guess I have some bad configuration.

> I just added a README section about "local-only" quirks https://github.com/firecow/gitlab-ci-local#local-only

Thanks !

**Comment by cs35-owncloud** [comment]
I tried with with the gitlab-ci.yml content directly and it worked even without a remote.

So I tried to set a remote and using the remote gitlab-ci.yml, but it's the same behavior, sadly it doesn't work.

```
xxx@yyy:/tmp/test (master) $ git remote add origin gitlab@xxx:yyy/test.git
xxx@yyy:/tmp/test (master) $ gitlab-ci-local 
parsing and downloads finished in 38 ms
pipeline finished in 79 ms
xxx@yyy:/tmp/test (master) $ git remote
origin
xxx@yyy:/tmp/test (master) $ git remote -v
origin	gitlab@xxx:yyy/test.git (fetch)
origin	gitlab@xxx:yyy/test.git (push)
xxx@yyy:/tmp/test (master) $ cat .gitlab-ci.yml 
---
include:
  - remote: 'https://pastebin.com/raw/YyWB4mCw'
```
