### ISSUE TITLE
Configurable `.gitlab-ci-local` directory

### ISSUE THREAD

**Issue by Khez** [firecow/gitlab-ci-local#475]
When running the pipeline the directory `.gitlab-ci-local` is created in the root of the project

This appears to be hardcoded as `{cwd}/.gitlab-ci-local` (where cwd is configurable via --cwd)

Allowing a configuration of this path would make adoption easier:
- Symfony has a default tmp dir: `{Symfony.root}/var/tmp/`
- RubyOnRails has a default tmp dir: `"#{Rails.root}/tmp/"`

In our project we have a general tmp directory for various ci tools and we want to add `.gitlab-ci-local` to that path.

**Comment by firecow** [comment]
Should be very doable...

**Comment by Khez** [comment]
It's worth mentioning that most code scanners will duplicate autocomplete / references with the `.gitlab-ci-local` versions of all files unless excluded manually.

Looking forward to having this configurable 😃

**Comment by Khez** [comment]
Any idea when a new release is gonna occur ?

Checking the [latest release against master](https://github.com/firecow/gitlab-ci-local/compare/4.31.0...master) there are some version bumps, features and bugfixes.

**Comment by firecow** [comment]
Some time next week...
You checkout master.
And call the following in the meantime.

```
npm install
npx tsc
npm pack
sudo npm install -g gitlab-ci-local.tar.gz
```

**Comment by firecow** [comment]
Some time next week...
You checkout master.
And call the following in the meantime.

```
npm install
npx tsc
npm pack
sudo npm install -g gitlab-ci-local.tar.gz
```

Or just try it out using
```
npm install
npx tsc
./ts-node --cwd <path-to-application>
```

**Comment by Khez** [comment]
We can wait till next week.

Prepping some internal docs on how to use gitlab-ci-local in the meantime.

Thank you again for the help and the fast responses!

**Comment by firecow** [comment]
@Khez If you find anything vital that needs to be added to this projects README.md please let me know, and I will add it.
