### ISSUE TITLE
deb package auto install tabcompletion

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#488]
People without great debian knowledge gets tab completion out of the box 🤣

@FnuGk Can you investigate if brew has a similar post install script thingie we can utilize?

NPM pack has one, lets do that as well.

**Comment by FnuGk** [comment]
There is a few options for this

-  Just print a message on how to do it https://docs.brew.sh/Formula-Cookbook#messaging
- Add an optional step with https://docs.brew.sh/Formula-Cookbook#adding-optional-steps
- reverse the optional logic and have it install tab completion by default and use the option to not do that

homebrew packages are just ruby scripts so the worlds your oister :)
