### ISSUE TITLE
Read env variables from $HOME/.gitlab-ci-local/.env

### ISSUE THREAD

**Issue by cs35-owncloud** [firecow/gitlab-ci-local#497]
Hello,

as discussed [here](https://github.com/firecow/gitlab-ci-local/issues/474#issuecomment-1133004323), would you consider adding the support of reading env variables from **$HOME/.gitlab-ci-local/.env** ?

In my case, I need to share the same **$HOME/.gitlab-ci-local/** with several coworkers. It would be easier to have all the settings in one spot, for debugging and sharing.

Thanks.

**Comment by typoworx-de** [comment]
Additional question to @firecow is it possible to give cli-argument to use {project-dir}/.gitlab-ci-local-env as file?

**Comment by firecow** [comment]
CLI options are parsed from `.gitlab-ci-local-env`, so no that would be counter intuitive @typoworx-de

**Comment by cs35-owncloud** [comment]
Wuhuuu I can't wait :partying_face: thanks !
