### ISSUE TITLE
Ownersheip of current directory changes unexpectedly

### ISSUE THREAD

**Issue by naweiss** [firecow/gitlab-ci-local#508]
When creating a job with artifacts, for example:
```yml
build:
  image: docker:stable
  script:
    - echo "Hello world" > hello.txt
  artifacts:
    paths: [hello.txt]
```
You can run `sudo gitlab-ci-local` to run you job.
Then you will have the file `hello.txt` under `.gitlab-ci-local/artifacts/build/hello.txt` which is fine.
But, you will also have `hello.txt` in you current dir which is strange.
Moreover, the current directory will be suddenly owen by `root` which will break things since you will no longer be able to create new files in the current directory.
You will not be able to also checkout to some other branch if this branch has new file since git itself will fail to create new files.

The state of my git repo before running `sudo gitlab-ci-local`:
```
drwxr-xr-x 1 user user 4096 Jun 11 23:24 ./
drwxr-xr-x 1 user user 4096 May 19 21:33 ../
drwxr-xr-x 1 user user 4096 May 19 21:33 .git/
-rw-r--r-- 1 user user  115 Jun 11 23:16 .gitlab-ci.yml
```
And after:
```
drwxr-xr-x 1 root root 4096 May 19 21:34 ./
drwxr-xr-x 1 user user 4096 May 19 21:33 ../
drwxr-xr-x 1 user user 4096 May 19 21:33 .git/
-rw-r--r-- 1 user user  115 Jun 11 23:16 .gitlab-ci.yml
-rw-r--r-- 1 root root   12 May 19 21:34 hello.txt
```

Running with `--shell-isolation` does not help.

**Expected behavior**
Current dir (e.g. `.`) will not change ownership.
And maybe even that `hello.txt` will only be created under the artifacts directory.

**Host information**
Ubuntu 20.04
gitlab-ci-local 4.32.0

**Comment by firecow** [comment]
gitlab-ci-local should not be run with sudo

**Comment by naweiss** [comment]
I am probably missing something trivial.
But where running `gitlab-ci-local` as a non-root user I get lots of permission denied error on docker commands.

For example:
```
Error: command failed with exit code 1: docker image inspect docker:stable
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/docker:stable/json: dial unix /var/run/docker.sock: connect: permission denied```

**Comment by firecow** [comment]
Oh, your linux user needs to be in the docker group.

https://docs.docker.com/engine/install/linux-postinstall/
