### ISSUE TITLE
gitlab CI config optimization don't work completely

### ISSUE THREAD

**Issue by JacksonChen666** [firecow/gitlab-ci-local#512]
## The issue
Things like [yaml anchors](https://docs.gitlab.com/ee/ci/yaml/yaml_optimization.html#anchors) and [`extends`](https://docs.gitlab.com/ee/ci/yaml/yaml_optimization.html#use-extends-to-reuse-configuration-sections) don't apply correctly when doing `gitlab-ci-local --list-all` (or `gitlab-ci-local` at all) with the gitlab CI config containing such.

```
$ gitlab-ci-local --list-all                                
parsing and downloads finished in 46 ms
name       description  stage   when        allow_failure  needs
pages-tor               build   on_success  false 
```

## Minimal .gitlab-ci.yml illustrating the issue
https://gitlab.com/JacksonChen666/hugo-test/-/blob/a5da066685548a8bf66863ad49e8e8f321d4c244/.gitlab-ci.yml

## Expected behavior
I was expecting 2 jobs to show up.

- [listed jobs](https://gitlab.com/JacksonChen666/hugo-test/-/pipelines/566179553)
- [ci editor lint](https://gitlab.com/JacksonChen666/hugo-test/-/ci/editor?branch_name=main&tab=2)

## Host information
macOS
gitlab-ci-local 4.32.0

## Additional context
[complete usable testing repo](https://gitlab.com/JacksonChen666/hugo-test)

**Comment by firecow** [comment]
The is 404

**Comment by JacksonChen666** [comment]
> The link is 404

i forgot to replace the 404 link 🫠

**Comment by JacksonChen666** [comment]
i definitely didn't expect the solution to be removing the word "pages" from being in the "not allowed" list of job names.
i probably won't be changing the issue title.

AFAIK `pages` is a special but not reserved job name, indicating the folder `public/` in the artifacts from the job should be deployed to gitlab pages.
