### ISSUE TITLE
Win10: commands git & rsync not found

### ISSUE THREAD

**Issue by moepmoep12** [firecow/gitlab-ci-local#547]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  script:
    - echo "Heya"
```

**Expected behavior**
Log 'Heya'.

**Host information**
Win10
gitlab-ci-local 4.32.0

**Error message**
> Using fallback linux user id
parsing and downloads finished in 341 ms
Error: Command failed with exit code 127: rsync -a --delete-excluded --delete --exclude-from=<(git ls-files -o --directory | awk '{print "/"$0}') --exclude .gitlab-ci-local/ ./ .gitlab-ci-local/builds/.docker/
/bin/bash: git: command not found
/bin/bash: rsync: command not found
    at makeError (C:\Users\usr\AppData\Roaming\npm\node_modules\gitlab-ci-local\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\usr\AppData\Roaming\npm\node_modules\gitlab-ci-local\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Function.rsyncTrackedFiles (C:\Users\usr\AppData\Roaming\npm\node_modules\gitlab-ci-local\src\utils.ts:176:9)
    at handler (C:\Users\usr\AppData\Roaming\npm\node_modules\gitlab-ci-local\src\handler.ts:117:9)
    at Object.handler (C:\Users\usr\AppData\Roaming\npm\node_modules\gitlab-ci-local\src\index.ts:25:34) {
  shortMessage: `Command failed with exit code 127: rsync -a --delete-excluded --delete --exclude-from=<(git ls-files -o --directory | awk '{print "/"$0}') --exclude .gitlab-ci-local/ ./ .gitlab-ci-local/builds/.docker/`,
  command: `rsync -a --delete-excluded --delete --exclude-from=<(git ls-files -o --directory | awk '{print "/"$0}') --exclude .gitlab-ci-local/ ./ .gitlab-ci-local/builds/.docker/`,
  escapedCommand: `"rsync -a --delete-excluded --delete --exclude-from=<(git ls-files -o --directory | awk '{print \\"/\\"$0}') --exclude .gitlab-ci-local/ ./ .gitlab-ci-local/builds/.docker/"`,
  exitCode: 127,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '/bin/bash: git: command not found\n/bin/bash: rsync: command not found',
  all: '/bin/bash: git: command not found\n/bin/bash: rsync: command not found',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Are further setup steps required for windows?

**Comment by firecow** [comment]
@moepmoep12 I need more info.

Are you using Windows Subsystem for Linux?
Are you using Gitbash or Powershell?

**Comment by moepmoep12** [comment]
> Are you using Windows Subsystem for Linux? 

Yes, wsl2. Kernel-Version: 5.10.102.1

> Are you using Gitbash or Powershell?

I've tried both with the same result.

**Comment by firecow** [comment]
@moepmoep12 Can you try installing rsync for gitbash?
https://prasaz.medium.com/add-rsync-to-windows-git-bash-f42736bae1b3

**Comment by moepmoep12** [comment]
Installing rsync for gitbash did the trick, thank you. Consider adding this to the installation instructions for windows.

**Comment by firecow** [comment]
I will add it to the README.md right away.

**Comment by firecow** [comment]
@moepmoep12 Which instructions did you follow to install rsync under gitbash ?
