### ISSUE TITLE
NoArtifactsToSource as global configuration

### ISSUE THREAD

**Issue by alexander-matthiesen** [firecow/gitlab-ci-local#552]
**Is your feature request related to a problem? Please describe.**
Currently we have to amend our pipeline source code to not have artifacts copied into the cwd. 
If we would remove the descriptor, gitlab-ci-local would create unwanted files in the root of the repostory. These are hard to add to the .gitignore and be committed in the worst case.  

**Describe the solution you'd like**
Add a flag "--no-artifacts-to-source" as global configuration option. It would look like this:
`gitlab-ci-local --no-artifacts-to-source`

**Describe alternatives you've considered**
An alternative would be to add `# @NoArtifactsToSource` to every pipeline job with artifacts. This is kind of hard to maintain especially when we have contributions and they don't know that we need to add the descriptor if we want to run the job locally.

**Additional context**
It would need a change here:
https://github.com/firecow/gitlab-ci-local/blob/master/src/job.ts#L192

As well as a new global configuration flag and of course the documentation.

**Comment by firecow** [comment]
Aah... Great idea... 
I'll add that asap 🤟

**Comment by alexander-matthiesen** [comment]
No worries, I'm already on it. :)

PR will come in a few hours / days.
Thanks for the fast reply!
