### ISSUE TITLE
How to test gitlab-ci with the tool gitlab-ci-local

### ISSUE THREAD

**Issue by alexander-matthiesen** [firecow/gitlab-ci-local#559]
**Description**
This issue is more like a question to best practice than a feature request.

Currently we have a lot of contributors to our centralized pipeline and we want to have automated tests that are testing the jobs we are writing for our applications.

The requirements are the following:
 - Define things as "environment" like variables, files, ...
 - Execute the job with the gitlab-ci-local tooling
 - Assert outcome / created files against expectations
 - generate report to communicate outcome and include it in GitLab MRs for example

Do you have experience with that?

**Comment by firecow** [comment]
I have no experience with testing my Gitlab CI/CD pipeline jobs like this.

You could run gitlab-ci-local remotely on a shell-executor, and develop some sort of report generator program that parses outputs and verify files in correct locations, and have that tool create/edit a MR comment.

**Comment by alexander-matthiesen** [comment]
We created a concept for testing with gitlab-ci-local by using the [bats testing framework](https://github.com/bats-core/bats-core). 

I want to share my experience once we have it running in our gitlab pipeline.

Do you actually use gitlab-ci-local in your GitLab CI/CD pipelines within the shell runner to test some things?

Could you shortly describe how you have setup your shell runners because the current Idea is to run gitlab-ci-local multiple times (with the testing framework) within a shell runner. The current docker in docker solution is somehow a bit slow but maybe it's just a configuration issue.

Last question:
When do you plan the next release with the new features?

**Comment by firecow** [comment]
I'm releasing tonight properly.

I've never actually run gitlab-ci-local via gitlab ci/cd.

The shell executors we use is 100% default setup via gitlab-runner register --shell
