### ISSUE TITLE
FEAT:  Working completion for `gcl` alias

### ISSUE THREAD

**Issue by ben-alkov** [firecow/gitlab-ci-local#575]
**Describe the solution you'd like**

Have completion working for the `gcl` alias

**Describe alternatives you've considered**

Manually adding `gcl` to .bashrc (which works)

**Additional context**

```diff
# .bashrc
- complete -o bashdefault -o default -F _gitlab-ci-local_yargs_completions gitlab-ci-local
+ complete -o bashdefault -o default -F _gitlab-ci-local_yargs_completions gitlab-ci-local gcl
```

I'd open a PR, but I don't understand how completion generation works...

**Comment by firecow** [comment]
Have you read this?
https://github.com/firecow/gitlab-ci-local#tab-completion

**Comment by firecow** [comment]
@ben-alkov I'm closing this, feel free to elaborate and reopen it.

**Comment by ben-alkov** [comment]
When you run

`gitlab-ci-local --completion >> ~/.bashrc`

it injects

`complete -o bashdefault -o default -F _gitlab-ci-local_yargs_completions gitlab-ci-local`

into '~/.bashrc'.

Note that the only command for which completion is available is `gitlab-ci-local`. **Completion does not work for the `gcl` alias**.

If you add "gcl" to the end of the line which `gitlab-ci-local --completion >> ~/.bashrc` injects into '~/.bashrc', (so that the complete line looks like `complete -o bashdefault -o default -F _gitlab-ci-local_yargs_completions gitlab-ci-local gcl`), completion also works for the `gcl` alias.
