### ISSUE TITLE
print docker cp timing, docker pull timing, docker run timing, for debugging slow pipelines.

### ISSUE THREAD

**Issue by ZobairQ** [firecow/gitlab-ci-local#58]
Would be nice if we had a way to execute gitlab with -v or --verbose, to show more information on the execution.

**Comment by firecow** [comment]
Are there any specifc pieces of information you need?
I would rather let gitlab-ci-local be as verbose as possible, and have uses silent messages via a quiet option.

**Comment by firecow** [comment]
I have renamed this issue to actually describe a task

**Comment by firecow** [comment]
4.9.5 is way more verbose, when it comes to docker-executor jobs
