### ISSUE TITLE
Automatically enter container if build failed

### ISSUE THREAD

**Issue by Flowdalic** [firecow/gitlab-ci-local#587]
It would be great if gitlab-ci-local would automatically enter the container if a build failed, to allow for a post-mortem analysis.

**Comment by firecow** [comment]
Yeah, or brings up a dialog (Y/n) to docker exec -it into it.

**Comment by firecow** [comment]
This doesn't seem to be a particularly active issue. I'm closing for now.
Anyone finding this feel free to reopen.
