### ISSUE TITLE
Error while using gitlab-ci-local within podman

### ISSUE THREAD

**Issue by alexander-matthiesen** [firecow/gitlab-ci-local#596]
Currenty we are switching from docker in docker to podman in out pipeline. Since we are not allowed to have priviledged access in our gitlab runners, we need the podman functionality.

Currently we are running into this error message:

```
Error: Command failed with exit code 1: docker run --rm -v gcl-versioningOgcommon-44494-tmp:/tmp/ -v gcl-versioningOgcommon-44494-build:/app/ firecow/gitlab-ci-local-util bash -c chown 0:0 -R /app/ && chmod a+rw -R /app/ && chmod a+rw -R /tmp/
   unable to upgrade to tcp, received 409
       at makeError (/usr/local/lib/node_modules/gitlab-ci-local/node_modules/execa/lib/error.js:60:11)
       at handlePromise (/usr/local/lib/node_modules/gitlab-ci-local/node_modules/execa/index.js:118:26)
       at processTicksAndRejections (node:internal/process/task_queues:95:5)
       at Job.execScripts (/usr/local/lib/node_modules/gitlab-ci-local/src/job.ts:624:13)
       at Job.start (/usr/local/lib/node_modules/gitlab-ci-local/src/job.ts:367:36)
```

Do you know if that is a common issue that we need to fix on our side or is it a specific issue? 

### Assumption
I think it might have something to do with missing priviledges while creating containers from within podman.
It would be great if you could elaborate why priviledged access is needed at all. It seems it is only needed to set folder rights.

**Comment by firecow** [comment]
It's most likely podman not allowing permissions and owner to be set on host mounts.
Even though that error indicates that something is denied with networking.

I have never seen that error.

Is it possible to set at podman driver in real gitlab-runners?

**Comment by alexander-matthiesen** [comment]
We actually get a new issue. So we managed to have podman running but it seems that there is still a problem and I don't know if it is on running the gitlab-ci-local or the docker image that we are using or if it is still our podman configuration:

```
Error: Command failed with exit code 125: docker image inspect <DOCKER_IMAGE_URL>
   Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
   time="2022-10-27T17:31:31Z" level=warning msg="\"/\" is not a shared mount, this could cause issues or missing mounts with rootless containers"
   cannot clone: No space left on device
   user namespaces are not enabled in /proc/sys/user/max_user_namespaces
   Error: cannot re-exec process
       at makeError (/usr/local/lib/node_modules/gitlab-ci-local/node_modules/execa/lib/error.js:60:11)
       at handlePromise (/usr/local/lib/node_modules/gitlab-ci-local/node_modules/execa/index.js:118:26)
       at processTicksAndRejections (node:internal/process/task_queues:95:5)
       at Job.pullImage (/usr/local/lib/node_modules/gitlab-ci-local/src/job.ts:702:13)
       at Job.execScripts (/usr/local/lib/node_modules/gitlab-ci-local/src/job.ts:[53](https://gitlab.dev.codefactory.sh/platform/common-pipeline/-/jobs/8002070#L53)4:13)
       at Job.start (/usr/local/lib/node_modules/gitlab-ci-local/src/job.ts:377:36)
```

**Comment by firecow** [comment]
It says no disk space on device.
You sure the VM or host haven't run out of disk space?

**Comment by alexander-matthiesen** [comment]
Even with a completely fresh node and a privileged runner / podman it still gives that issue.

Maybe it can't mount the "/" that it tells in the line above the "no space left"?

`2022-10-27T17:31:31Z" level=warning msg="\"/\" is not a shared mount, this could cause issues or missing mounts with rootless containers`

**Comment by alexander-matthiesen** [comment]
Might be related to this one:
https://github.com/containers/podman/issues/7704

We will test things out and come back if we either find a solution or something still doesn't work.

**Comment by firecow** [comment]
Ok, reopen, if it isn't podman's fault

**Comment by firecow** [comment]
I can add a Dockerfile.utils...
It is just a debian with rsync installed.

I don't think that will solve the problem

Is podman not able to fetch docker images specified without the dockerhub.io prefix or what is going on here?

**Comment by alexander-matthiesen** [comment]
The problem is, that podman can't download `firecow/gitlab-ci-local-utils` because it doesn't know by default where the image is stored.

Here you can find more information: 
https://www.redhat.com/sysadmin/container-image-short-names

So we could amend the registry in our podman instance (which only solves it for us) or we amend that call to add the registry of docker so it is crystal clear where the image should be taken from.

**Comment by alexander-matthiesen** [comment]
@firecow should work now. PR was created. :)

**Comment by alexander-matthiesen** [comment]
@firecow is the `latest` version of the dockerimage automatically updated when merged to master or do we need to create a new release to make this usable?

**Comment by firecow** [comment]
Why is the docker image important?

**Comment by alexander-matthiesen** [comment]
Ah no, I meant the gitlab-ci-local version on npm: https://www.npmjs.com/package/gitlab-ci-local.

I work too much with DockerImages and GitLab CI so I'm kind of brainwashed. 😆 
But you are right, I mean the npm version.

**Comment by alexander-matthiesen** [comment]
![](https://de.meming.world/images/de/8/8e/All_Right_Then%2C_Keep_Your_Secrets.jpg)

Haha, just kidding. Until the next release I will add clone and build into my dockerimage. No stress at all. 
I just was curious how and when you are creating the releases. :)
