### ISSUE TITLE
$CI_PROJECT_PATH doesn't exist in service

### ISSUE THREAD

**Issue by kleijnweb** [firecow/gitlab-ci-local#599]
Expected behavior:

In a service for a job, I would expect /builds/$CI_PROJECT_PATH to refer to an existing directory that contains the project files. In other words: parity with GitLab CI.

Actual behavior:

GCL doesn't mount the project files anywhere.

**Comment by firecow** [comment]
Are you sure services gets a copy of the project files?

I just read the this https://docs.gitlab.com/ee/ci/services/ and nowhere was project files inside service container mentioned.

Can you paste an example, where project files are needed by a service, and I'll run it by my "debugging" gitlab runner to investigate the workflow?

**Comment by kleijnweb** [comment]
I ran into it with a company image that I can't share here, but it relies on /builds/$CI_PROJECT_PATH/some/path being present.

Technically the path relative to the the project directory is populated by a different job so it is possible it is only available in the service when it is published as an artifact, but I didn't see any immediate connection there.

**Comment by bcouetil** [comment]
I agree with @firecow, this is a special case of yours. Even the artifacts are not accessible to services.

There may be special mounting on your runners...

**Comment by firecow** [comment]
We need an example to use in a potential integration test, and for reproduction.

**Comment by firecow** [comment]
I'm closing this one for now.
Please do reopen, if an actual minimal example is provided.

**Comment by ticapix** [comment]
should be fixed with #661
