### ISSUE TITLE
Failed to check regexp rule in variable

### ISSUE THREAD

**Issue by greenmaid** [firecow/gitlab-ci-local#609]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
variables:
  PROD_REF: '/^(master|main)$/'

job:
  rules:
    - if: $CI_COMMIT_REF_NAME =~ $PROD_REF
  script:
    - echo "I should be running on master ou main branch"
```
**Current buggy behavior** => when = never
```
$ gitlab-ci-local --list-all
parsing and downloads finished in 45 ms
name  description  stage   when   allow_failure  needs
job               test    never  false  
```

**Expected behavior**  => when = on_success  
```
$ gitlab-ci-local --list-all
parsing and downloads finished in 45 ms
name  description  stage   when        allow_failure  needs
job               test    on_success  false    
```

**Host information**
Ubuntu WSL 22.04 - gitlab-ci-local 4.34.0

**Additional context**
This issue has been discovered using [To Be Continuous templates](https://gitlab.com/to-be-continuous)

Using `PROD_REF: '^(master|main)$'` (without `/`) make it working 🤔

Using `if: $CI_COMMIT_REF_NAME =~ /^(master|main)$/ ` make it working too

**Comment by firecow** [comment]
The bug most likely is that the right hand side variables isn't expanded.
