### ISSUE TITLE
File variable makes crash if service image doen't have /tmp

### ISSUE THREAD

**Issue by greenmaid** [firecow/gitlab-ci-local#610]
**Minimal config illustrating the issue**
* .gitlab-ci.yml
```yml
---
job:
  image: alpine
  services:
    - name: greenmaid/basic_listen:latest
  script:
    - echo "I should run normaly"
```

* .gitlab-ci-local-variables.yml
```
FILE_CONTENT_IN_VALUES:
  type: file
  values:
    '*': |
      Im file value
      I'm great for certs n' stuff
```

Here the key issue is that [service image](https://hub.docker.com/repository/docker/greenmaid/basic_listen) is a minimal one and do not have `/tmp` directory in its filesystem.

* result
```
$ gitlab-ci-local
parsing and downloads finished in 41 ms
job starting alpine:latest (test)
Error: Command failed with exit code 1: docker cp /tmp/gitlab-ci-local-file-variables-mederic.deverdilhac-test-ci-815307 fea39599b78b10fe7ee974eef251487dee0165a2b6c176009ac5b0874826d0f6:/tmp/gitlab-ci-local-file-variables-mederic.deverdilhac-test-ci-815307/
Error: No such container:path: fea39599b78b10fe7ee974eef251487dee0165a2b6c176009ac5b0874826d0f6:/tmp
    at makeError (/snapshot/firecow-gitlab-ci-local/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/snapshot/firecow-gitlab-ci-local/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Job.startService (/snapshot/firecow-gitlab-ci-local/src/job.ts:997:13)
    at Job.start (/snapshot/firecow-gitlab-ci-local/src/job.ts:370:44)
```

**Expected behavior**
job should run fine

**Host information**
Ubuntu WSL 22.04
gitlab-ci-local 4.34.0

**Additional context**
This issue has been discovered using [To Be Continuous templates](https://gitlab.com/to-be-continuous) which use [custom image from usage tracking](https://gitlab.com/to-be-continuous/tools/tracking/-/blob/master/Dockerfile)

**Comment by firecow** [comment]
```
# .gitlab-ci.yml
---
job:
  image: alpine
  services:
    - name: greenmaid/basic_listen:latest
  script:
    - echo "I should run normaly"
```

![image](https://user-images.githubusercontent.com/973602/195931982-89624e6b-91c6-4c8d-b504-461046dfd278.png)

I cannot reproduce.
I need a `docker --version` from you @greenmaid
