### ISSUE TITLE
add rules support to include

### ISSUE THREAD

**Issue by gbenguria** [firecow/gitlab-ci-local#627]
introduced in 14.2 https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/ci/yaml/includes.md#use-rules-with-include

I was trying to do use a local import when using gitlab-ci-local

`include:
  - project: '/gitlab-ci/common'
    ref: c35322209aaw6e
    file: 'validate-gitlab-ci.yml'
    rules:
      - if: '$GITLAB_CI == "true"'
  - local: git/gitlab-ci/validate-gitlab-ci.yml
    rules:
      - if: '$GITLAB_CI == "false"'

stages:
  - validate-gitlab-ci

validate-gitlab-ci:
  only:
    - refactor/to_script
`
when I realized that includes do no support rules yet

**Comment by firecow** [comment]
Uh, very nice, should be doable 👍
