### ISSUE TITLE
Downstream pipelines

### ISSUE THREAD

**Issue by nachovizzo** [firecow/gitlab-ci-local#632]
**THANKS** for such amazing tool

**Is your feature request related to a problem? Please describe.**
I'm testing a gitlab-ci locally, this CI is basically generating downstream tasks (aka, creating a pipeleine.yaml on the fly and running it). Up to the generation process works, but then the downstream tasks are not being executed 

**Describe the solution you'd like**
I would like to test [dowstream pipelines](https://docs.gitlab.com/ee/ci/pipelines/downstream_pipelines.html) locally. If there is interest on this, I can provide some hello-world examples.

**Describe alternatives you've considered**
Run first the `global.yml` pipeline, use the generated file to `gitlab-ci-local --file generated.yml` But this file `needs` a job from `global.yml` which of course does not exists anymore.

**Comment by firecow** [comment]
https://github.com/firecow/gitlab-ci-local/issues/94 Isn't this a dublicate of ?

**Comment by nachovizzo** [comment]
> Isn't this a dublicate of #94 ?

Yes looks like!
