### ISSUE TITLE
Service containers should check Config for ExposedPorts instead of ContainerConfig

### ISSUE THREAD

**Issue by peterbbeu** [firecow/gitlab-ci-local#639]
**Is your feature request related to a problem? Please describe.**
Currently one of my service containers fails with the following message:

```
Could not find exposed tcp ports foobar-image:0.0.1
```

This is likely due to `ContainerConfig` being used instead of `Config` (see https://github.com/firecow/gitlab-ci-local/blob/master/src/job.ts#L1010). From what I can tell from [this issue in the docker repository](https://github.com/moby/moby/issues/18880),  `Config` should be used unless one is explicitly trying to use the build history of the container 

Even more info: https://github.com/docker/cli/issues/2868 and https://github.com/moby/buildkit/issues/1696

**Describe the solution you'd like**
Get the `ExposedPorts` from `Config` in the `docker inspect` output

**Describe alternatives you've considered**
I considered trying to somehow get my `ExportedPorts` into `ContainerConfig` but I cannot seem to figure out how.

**Additional context**
Here's the truncated `docker inspect` output for the image:
```
docker inspect foobar-image:0.0.1
```

```json
[
    {
        "Id": "sha256:40fdfe984ef0aba1fd1cb32393a50229e9a3799ee278b984c77c153c9187d610",
...
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2022-11-01T13:44:57.510599391Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "9200/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NODE_VERSION=18.0.0",
                "YARN_VERSION=1.22.18"
            ],
            "Cmd": [
                "node"
            ],
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 569903726,
        "VirtualSize": 569903726,
...
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```

**Comment by firecow** [comment]
Can you provide an example, with a service image that isn't working with GCL?

**Comment by pedroterzero** [comment]
I will try to make one, hopefully tomorrow

**Comment by peterbbeu** [comment]
Here is a very simple test repo: https://github.com/peterbbeu/gitlab-ci-local-testcase

This is the `.gitlab-ci.yml`:
```yaml
hello-world:
  services:
    - ghcr.io/peterbbeu/gitlab-ci-local-testcase:latest
  script:
    - docker pull ghcr.io/peterbbeu/gitlab-ci-local-testcase:latest
    - echo "Hello World"
```

This is how the container was built: https://github.com/peterbbeu/gitlab-ci-local-testcase/blob/main/.github/workflows/ci.yml

Or more simply:
```bash
echo 'FROM nginx' > Dockerfile
DOCKER_BUILDKIT=1 docker build -t helloworld .
```

**Comment by firecow** [comment]
I don't get your test-case. How is anything located in `Config.ExposedPorts` in this test case ?

**Comment by peterbbeu** [comment]
> I don't get your test-case. How is anything located in `Config.ExposedPorts` in this test case ?

I'm not exactly sure I know what you mean, building the image with these steps puts the ExposedPorts in `Config`. It never puts anything in `ContainerConfig`, by design (see the links in my original post)

You could extend the example like this

```bash
echo 'FROM nginx' > Dockerfile
echo 'EXPOSE 1234' >> Dockerfile
DOCKER_BUILDKIT=1 docker build -t helloworld .
```

And it would put the extra expose in `Container.ExposedPorts` but not in `ContainerConfig.ExposedPorts`

**Comment by peterbbeu** [comment]
Running this testcase works fine for you though?

```yaml
hello-world:
  services:
    - ghcr.io/peterbbeu/gitlab-ci-local-testcase:latest
  script:
    - sleep 30
    - echo "Hello World"
```

If so, you can just close this issue.

**Comment by firecow** [comment]
Nope, this is a bug. MR incoming.

**Comment by peterbbeu** [comment]
Very nice. Thank you.

I love the tool btw, really makes the dev experience a lot better. Thanks for it.
