### ISSUE TITLE
Define several volumes in ~/.gitlab-ci-local/.env

### ISSUE THREAD

**Issue by cs35-owncloud** [firecow/gitlab-ci-local#640]
Hello,

I've tried using the example **examples/docker-in-docker-build** with several volumes.

I tweaked some files to fit my real use case:

* .gitlab-ci.yml

```
---
# @Description Build alpine
alpine-image:
  services:
    - docker:20.10.17-dind
  needs: []
  image: docker:stable
  stage: build
  script:
    - printenv
    - ls -all /certs/client
    - docker build .
```

* .gitlab-ci-local-env (all commented out since I want to use only ~/.gitlab-ci-local/.env)

```
#PRIVILEGED=true
#VOLUME=certs:/certs/client
#VARIABLE="DOCKER_TLS_CERTDIR=/certs"
```

* ~/.gitlab-ci-local/.env

```
VOLUME="certs:/certs/client /var/run/docker.sock:/var/run/docker.sock"
PRIVILEGED=true
```

If I run the example:

```
$ gitlab-ci-local --cwd examples/docker-in-docker-build
parsing and downloads finished in 31 ms
alpine-image starting docker:stable (build)
alpine-image started service image: docker:20.10.17-dind with aliases: docker in 873 ms
alpine-image > still running...
alpine-image > still running...
alpine-image > still running...
alpine-image service image: docker:20.10.17-dind healthcheck failed: docker:2375
alpine-image service image: docker:20.10.17-dind healthcheck passed in 31 s
alpine-image copied to container in 497 ms
alpine-image service image: docker:20.10.17-dind healthcheck failed: docker:2376
alpine-image $ printenv
...
```

I have the healthcheck taking a long time.

If I had the volume directly to the command line, it's fine:

```
$ gitlab-ci-local --cwd examples/docker-in-docker-build --volume certs:/certs/client
parsing and downloads finished in 36 ms
alpine-image starting docker:stable (build)
alpine-image started service image: docker:20.10.17-dind with aliases: docker in 862 ms
alpine-image service image: docker:20.10.17-dind healthcheck passed in 1.53 s
alpine-image copied to container in 464 ms
alpine-image $ printenv
...
```

It's like the **certs:/certs/client** volume defined in **~/.gitlab-ci-local/.env** is not used.

gitlab-ci-local version: 4.34.0

It's there a way to make it work without specifying it in the command line ?
By the way, it looks like **DOCKER_TLS_CERTDIR** is not "useful" for the healthcheck problem here.
Thanks.

**Comment by firecow** [comment]
I'm able to reproduce. Hmmm.... This has been working at some point...
I shall fix, and make it part of next release.

**Comment by firecow** [comment]
Look at your service logs.
I'm sure the answer is within 😁
