### ISSUE TITLE
Permission denied on /gcl-build

### ISSUE THREAD

**Issue by alexander-matthiesen** [firecow/gitlab-ci-local#667]
**Is your feature request related to a problem? Please describe.**
When running the gitlab-ci-local within podman, we are getting the following error while generating our documentation artifacts.

```
    FAIL  generating:documentation
     >   File "/usr/lib/python3.9/shutil.py", line 521, in _copytree
     >     raise Error(errors)
     > shutil.Error: [('target/html/css/html.css', '/gcl-builds/documentation/html/css/html.css',
     "[Errno 13] Permission denied: '/gcl-builds/documentation/html/css/html.css'"),
     ('target/html/css/pdf.css', '/gcl-builds/documentation/html/css/pdf.css',
     "[Errno 13] Permission denied: '/gcl-builds/documentation/html/css/pdf.css'"),
```

**Describe the solution you'd like**
I don't know if it is a flaw within our dockerimage that generated the documentation, if it is related to podman or if it is a problem with gitlab-ci-local.

My question here is more, why the build directory needs to be on root level of the container and not for example in the home directory (which should have not permission issues).

**Describe alternatives you've considered**
We were already creating the folder within our gitlab-ci-local dockerimage and tried to set correct permissions (even allowing every user to use this folder).

```
RUN mkdir /gcl-builds
RUN chown -R :users /gcl-builds
RUN chmod -R a+rwX /gcl-builds
```

**Additional context**
-

**Comment by firecow** [comment]
We need a `echo "$(id -u):$(id -g)" from without that contain.

Or a `docker history <imagename>` where you grep after the Dockerfile `USER` field

**Comment by alexander-matthiesen** [comment]
The outcome of user id and user group is in every case "0:0". 

- 0:0 within the pipeline-test-job
  - 0:0 within bats
    - 0:0 before executing gitlab-ci-local
      - 0:0 within documentation:generation job _(this is the spawned podman instance)_

And here is the output of docker history:

```
   ID            CREATED        CREATED BY                                     SIZE        COMMENT
   eeb23a3ac9d4  292 years ago  RUN chmod +x doc-gen                           10.8 kB
   <missing>     292 years ago  COPY mkdocs-pdf.yml mkdocs-pdf.yml             6.66 kB
   <missing>     292 years ago  COPY mkdocs-html.yml mkdocs-html.yml           7.17 kB
   <missing>     292 years ago  COPY doc-gen doc-gen                           10.8 kB
   <missing>     292 years ago  COPY templates/css/pdf.css templates/css/p...  11.8 kB
   <missing>     292 years ago  COPY templates templates                       24.9 MB
   <missing>     292 years ago  COPY src src                                   72.7 kB
   <missing>     292 years ago  WORKDIR /generator                             4.1 kB
   <missing>     292 years ago  RUN apk --update --upgrade --no-cache --re...  11.7 MB
   <missing>     292 years ago  COPY templates/fonts /usr/share/fonts/Addi...  22 MB
   <missing>     292 years ago  RUN python3 -m pip install     --no-cache-...  135 MB
   <missing>     292 years ago  COPY requirements.txt requirements.txt         4.61 kB
   <missing>     292 years ago  RUN python3 -m pip install     --upgrade pip   16.3 MB
   <missing>     292 years ago  RUN pip config set global.cert /etc/ssl/ce...  9.22 kB
   <missing>     292 years ago  RUN apk add --update     git     jpeg-dev ...  719 MB
   <missing>     7 months ago   /bin/sh -c #(nop)  CMD ["/bin/sh"]             0 B
   <missing>     7 months ago   /bin/sh -c #(nop) ADD file:5d673d25da3a14c...  5.86 MB
```

So would you recommend to simple chown it to "0:0"?

```
RUN mkdir /gcl-builds
RUN chown -R 0:0 /gcl-builds
RUN chmod -R a+rwX /gcl-builds
```

**Comment by firecow** [comment]
GLC already does this...

**Comment by firecow** [comment]
Also try a build of GCL containing this PR
https://github.com/firecow/gitlab-ci-local/pull/665

**Comment by alexander-matthiesen** [comment]
Yes, in general it works. We also have some jobs that are working with our podman setup.

I also use already the master version which I clone and install inside the docker image. (of course just for testing)

Maybe we have issues with our python image in that gitlab job which is not correctly working with the podman restrictions.

**Comment by alexander-matthiesen** [comment]
Seems like /gcl-builds is not mounted as volume in the executed job (documentation-generation pipeline job in spawned podman instance).

**Comment by alexander-matthiesen** [comment]
Seems to be an python issue. We were setting `os.makedirs` which were not working because it wouldn't set the "all users permission (777)".

Here is a link for anyone who stumbles upon it:
https://stackoverflow.com/a/273227
