### ISSUE TITLE
--disable-umask cli option

### ISSUE THREAD

**Issue by hatvik** [firecow/gitlab-ci-local#671]
**Is your feature request related to a problem? Please describe.**
gitlab-ci-local seems to always do `docker create -u 0:0 ..`

This causes problems with file ownership and running applications/testing

**Describe the solution you'd like**
`docker create ...` without -u

**Describe alternatives you've considered**

**Additional context**

**Comment by firecow** [comment]
Is this possible with regular gitlab-runners?

**Comment by hatvik** [comment]
Yes, with `FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR` and creating images with `USER your-ci-user`

`If enabled will remove the usage of umask 0000 call for jobs executed with docker executor. Instead Runner will try to discover the UID and GID of the user configured for the image used by the build container and will change the ownership of the working directory and files by running the chmod command in the predefined container (after updating sources, restoring cache and downloading artifacts). POSIX utility id must be installed and operational in the build image for this feature flag. Runner will execute id with options -u and -g to retrieve the UID and GID.`

https://docs.gitlab.com/runner/configuration/feature-flags.html

**Comment by firecow** [comment]
Didn't know about flags. Labelling this as a feature request.

**Comment by alexander-matthiesen** [comment]
We also have this issue since this is overriding the user set in docker images. So if we definitely dont want root access, we are creating a new user but this is overwritten by the -u 0:0 option.

Example Dockerfile for helm 
```
FROM alpine:3.17.0

#* Create non-root user for compliance
ENV USER_NAME=ci-user
ENV GROUP_NAME=$USER_NAME

RUN addgroup $GROUP_NAME && \
    adduser  \
            --shell /bin/bash  \
            --disabled-password \
            --ingroup $GROUP_NAME  \
            $USER_NAME

WORKDIR /home/$USER_NAME

#* Install required tools
RUN apk add --update --no-cache  \
    #? Tools needed to run the scripts
    bash \
    grep \
    yq \
    git \
    #? Helm
    helm

#* Run as unprivileged user
USER $USER_NAME

ENV HELM_PUSH_VERSION=v0.10.3

RUN helm plugin install https://github.com/chartmuseum/helm-push --version=$HELM_PUSH_VERSION

```
