### ISSUE TITLE
Remote without .git

### ISSUE THREAD

**Issue by dannywillems** [firecow/gitlab-ci-local#693]
Opening this issue in case of people face the same error.
I was getting `syntax error near unexpected token` when running `gitlab-ci-local` on any job.
It appears to be a missing `.git` at the end of the remote. See this comment from @firecow https://github.com/firecow/gitlab-ci-local/issues/380#issuecomment-1031801331.
Solution: add `.git` to each of your remotes in your `.git/config`.

Thanks for the tool.

**Comment by firecow** [comment]
https://github.com/firecow/gitlab-ci-local/pull/728 Closes this issue
