### ISSUE TITLE
Using of 'DOCKER_HOST' variable will block dind service container to start

### ISSUE THREAD

**Issue by iutipikin** [firecow/gitlab-ci-local#702]
Hi folks. While working with dind jobs I noticed what if you are using well-known docker variables as ci/cd variables e.g. "DOCKER_HOST" to make you dind dokerd working, gitlab-ci-local will fail to start service container (as this assignment will somehow override the one for gitlab-ci-local). Workaround is kind are simple, but in my case I have lots of places to rewrite :(  

Workaround: export DOCKER_HOST=tcp://dind:2375 inside 'script'

**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  services:
    - name: docker:dind
       alias: dind
  variables:
    DOCKER_HOST: tcp://dind:2375
  script:
    - echo "Heya"
```

**Expected behaviour**
both service and main containers are started, service's dockerd is used in main job container

**Actual behaviour**
`Command failed with exit code 1: docker create -u 0:0 <cmd args> error during connect: Post "http://dind:2375/v1.24/containers/create": dial tcp: lookup dind: no such host`

**Host information**
MacOS 12.6
gitlab-ci-local 4.36.1

**Additional context**
I'm using rancher desktop for docker runtime

**Comment by firecow** [comment]
Please provide a job output of this working on gitlab.com.

**Comment by firecow** [comment]
Closing this for now, feel free to reopen, if you get time to provide us with additional information from a gitlab runner instance.

**Comment by firecow** [comment]
Does this work on remote runners?

**Comment by trovio-lijn** [comment]
I can confirm this as well. I ran a job that had some DOCKER_* vars tonight, and only when I removed (or rather overwrote with `DOCKER_VAR: ""` them all, I saw the dind container starting up in my `watch docker ps` window. 

All of these jobs run fine on gitlab runners (SaaS Premium).

Let me know if I can help out with testing anything. Me trying to fix the code will probably only make things worse 🤪

**Comment by eljuanchosf** [comment]
@firecow - I can confirm that it works on remote runners but not with `gcl`. 

Output is:

```
test        copied to docker volumes in 398 ms
Error: Command failed with exit code 1: docker create --interactive --network gitlab-ci-local-51458 --user 0:0 --network-alias=docker -e DOCKER_HOST -e DOCKER_TLS_CERTDIR -e DOCKER_DRIVER -e GITLAB_USER_LOGIN -e GITLAB_USER_EMAIL -e GITLAB_USER_NAME -e GITLAB_USER_ID -e CI_COMMIT_SHORT_SHA -e CI_COMMIT_SHA -e CI_PROJECT_NAME -e CI_PROJECT_TITLE -e CI_PROJECT_PATH -e CI_PROJECT_PATH_SLUG -e CI_PROJECT_NAMESPACE -e CI_PROJECT_VISIBILITY -e CI_PROJECT_ID -e CI_COMMIT_REF_PROTECTED -e CI_COMMIT_BRANCH -e CI_COMMIT_REF_NAME -e CI_COMMIT_REF_SLUG -e CI_COMMIT_TITLE -e CI_COMMIT_MESSAGE -e CI_COMMIT_DESCRIPTION -e CI_PIPELINE_SOURCE -e CI_SERVER_HOST -e CI_SERVER_PORT -e CI_SERVER_URL -e CI_SERVER_PROTOCOL -e CI_API_V4_URL -e CI_PROJECT_URL -e GITLAB_CI -e CI_JOB_ID -e CI_PIPELINE_ID -e CI_PIPELINE_IID -e CI_JOB_NAME -e CI_JOB_NAME_SLUG -e CI_JOB_STAGE -e CI_PROJECT_DIR -e CI_JOB_URL -e CI_PIPELINE_URL -e CI_ENVIRONMENT_NAME -e CI_ENVIRONMENT_SLUG -e CI_ENVIRONMENT_URL -e CI_NODE_INDEX -e CI_NODE_TOTAL -e CI_REGISTRY -e CI_REGISTRY_IMAGE --volume gcl-test-51458-build:/gcl-builds --volume gcl-test-51458-tmp:/tmp/gitlab-ci-local-file-variables-Vitrifi-x-51458 docker:dind "--tls=false" 
error during connect: Post "http://docker:2375/v1.24/containers/create": dial tcp: lookup docker: no such host
    at makeError (/opt/homebrew/Cellar/gitlab-ci-local/4.45.0/libexec/lib/node_modules/gitlab-ci-local/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/opt/homebrew/Cellar/gitlab-ci-local/4.45.0/libexec/lib/node_modules/gitlab-ci-local/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Job.startService (/opt/homebrew/Cellar/gitlab-ci-local/4.45.0/libexec/lib/node_modules/gitlab-ci-local/src/job.ts:1063:39)
    at /opt/homebrew/Cellar/gitlab-ci-local/4.45.0/libexec/lib/node_modules/gitlab-ci-local/src/job.ts:447:48
    at async Promise.all (index 0)
    at Job.start (/opt/homebrew/Cellar/gitlab-ci-local/4.45.0/libexec/lib/node_modules/gitlab-ci-local/src/job.ts:443:13)
    at /opt/homebrew/Cellar/gitlab-ci-local/4.45.0/libexec/lib/node_modules/gitlab-ci-local/node_modules/p-map/index.js:57:22
```

**Comment by firecow** [comment]
With the proposed changes I've managed  to get rid of the errors, we were seeing. However the following yml produces a new error that gitlab.com isn't producing.

```yml
---
job:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker --version
```

`gitlab-ci-local job --privileged`

![image](https://github.com/firecow/gitlab-ci-local/assets/973602/6a9ac591-4ef9-4c91-aa07-e564b1183f4c)

Can you guys figure out what the duce I'm missing?

**Comment by bcouetil** [comment]
I can confirm that it is working in 4.46.0, many thanks 🙏
