### ISSUE TITLE
Limit concurrent jobs

### ISSUE THREAD

**Issue by olkitu** [firecow/gitlab-ci-local#703]
Add possible limit concurrency jobs. I have some tests example run normally over 10 jobs same time but no way run in local computer so many concurrent jobs.

**Comment by bcouetil** [comment]
I realize that I'm doing a lot of unnecessary work to get around this limitation on my biggest projects.

A big +1 for this 👍

**Comment by firecow** [comment]
This is just for preventing your PC's getting too hot right?
Is there anything buggy going on, that we should fix?

**Comment by bcouetil** [comment]
CPU is not the main concern.

It could allow too much RAM, which makes jobs, or even the Docker system, crash.

**Comment by olkitu** [comment]
Yes too much load when example have over 10 jobs in same stage. Normally on CI have scalable environment to run on multiple nodes.

**Comment by naweiss** [comment]
Opened a PR for this

**Comment by bcouetil** [comment]
Thank you all, nice feature 🙏
