### ISSUE TITLE
'gitlab-ci-local-util' pulls runs into 'toomanyrequests: You have reached your pull rate limit'

### ISSUE THREAD

**Issue by alexander-matthiesen** [firecow/gitlab-ci-local#714]
**Is your feature request related to a problem? Please describe.**
Since gitlab-ci-local is spawning pods and needs the gitlab-ci-local-util to mount a volume, it also pulls that image the whole time.

We have trouble setting the docker config in those spawned pods so it is using out payed docker user. Therefore we were asking ourselves, why that image is needed with every gitlab-ci-local run or if it could be solved on another way (without pulling that image)

Since we are using gitlab-ci-local in out pipeline to run quite a few tests (every test is calling gitlab-ci-local) we are pretty fast at that pull limit from docker.

**Describe the solution you'd like**
gitlab-ci-local is not pulling the image and implements the image features on another way.

**Describe alternatives you've considered**
An alternative would be to correctly inject the docker config in gitlab-ci-local but that would only solve it for one particular user of gitlab-ci-local.

**Comment by firecow** [comment]
The image is needed by a temporary container that GCL spawns for artifact/cache copy in/out operations inside the builds/cache docker volume.

We can put a Dockerfile inside the actual application binary and docker build the image locally on peoples local machines to bypass dockerhub rate limiting.

**Comment by bcouetil** [comment]
Would it be possible to pull with the policy "if-not-present" ? don't know how to configure that, but that is pretty handy in the kubernetes world...

**Comment by firecow** [comment]
I fail to see how the temporary container run is causing this rate limiting.
How is it being pulled so many times?

**Comment by firecow** [comment]
I makes sense to do it.

**Comment by firecow** [comment]
On a second thought, building on the fly will pull exactly as many images, as actually just pulling it :smile:
