### ISSUE TITLE
Unexpected line breaks in version numbers in cargo output

### ISSUE THREAD

**Issue by detly** [firecow/gitlab-ci-local#725]
# Minimal .gitlab-ci.yml illustrating the issue

```yml
test:
  image: rust:1-slim
  script:
    - cargo install cargo2junit
```

# Expected behavior 
I see similar output to what I see locally eg. I run `docker run -i rust:1-slim cargo install` and I see cargo's usual output. Here's an extract:

```none
   Compiling thiserror v1.0.38
   Compiling itoa v1.0.5
   Compiling serde v1.0.152
   Compiling time-core v0.1.0
   Compiling arrayvec v0.5.2
```

# Actual behaviour

Cargo's output has a lot of extra line breaks. Here's a similar extract after running `gitlab-ci-local test`:

```none
test >    Compiling thiserror v1.0.38
test >    Compiling utf8parse v0.2.0
test >  
test >  
test >  
test > Compiling
test >  
test > itoa
test >  v
test > 1
test > .
test > 0
test > .5
test >  
test >  
test >  
test > Compiling
test >  
test > serde
test >  v
test > 1
test > .
test > 0
test > .
test > 152
test >    
test > Compiling arrayvec v0.5.2
test >  
test >   Compiling time-macros v0.2
test > .6
test >  
test >  
test >  
test > Compiling
test >  
test > serde_json
test >  v
test > 1
test > .
test > 0
test > .
test > 91
test >  
test >  
test >  
test > Compiling
test >  
test > xml-rs
test >  v
test > 0
test > .
test > 8.4
test >  
test >   Compiling ryu
test >  v1
test > .0
test > .12
test >    
test > Compiling
test >  
test > time
test >  v
test > 0
test > .
test > 3
test > .17
```

# Host information

Ubuntu 22.10
gitlab-ci-local 4.37.0

# Additional context

Cargo uses redrawing and colour in its output when attached to a tty. However, this is turned off for non-tty (aka. "dumb") terminals, as you can see with eg. `docker run -i rust:1-slim cargo install cargo2junit` vs `docker run -it rust:1-slim cargo install cargo2junit`.

**Comment by firecow** [comment]
Please provide a job output from gitlab.com, illustrating how it handles this case.

**Comment by detly** [comment]
Unfortunately I am out of free CI minutes, so it will have to wait until they reset. But the [project is here](https://gitlab.com/detly/gitlab-ci-local-test) if you have the time to fork and check it out yourself.

**Comment by firecow** [comment]
Here is what it should look like.
![image](https://user-images.githubusercontent.com/973602/212881585-38757097-12af-4680-8aa1-6e23a777ede2.png)

Here is how it currently looks like
![image](https://user-images.githubusercontent.com/973602/212881722-222c8850-ddd0-4a0f-b8e5-80706e7553eb.png)
