### ISSUE TITLE
Containers in same network

### ISSUE THREAD

**Issue by alexander-matthiesen** [firecow/gitlab-ci-local#726]
**Is your feature request related to a problem? Please describe.**
We want to have a service (wiremock) startet within the pipeline job "pipeline-tests". This wiremock is then added to a specific docker network "gitlab-ci-local-XXXXX". 

After that we are starting gitlab-ci-local again in the job with the wiremock service (for pipeline tests) but those startet gitlab-ci-local jobs are getting added to the default "bridge" network.

My question here is, why we are separating by network at all?

**Describe the solution you'd like**
Ditching the different networks and start all containers in the same network.

**Describe alternatives you've considered**

**Additional context**
We want to use gitlab-ci-local to run a pipeline testing job which runs gitlab-ci-local (very inception like)

**Comment by firecow** [comment]
Job A needs mariadb service
Job B needs mariadb service

Job A and B are started at the same time.

Which mariadb services gets to have port 3306.

**Comment by alexander-matthiesen** [comment]
I understand and that is reasonable. 

I think the 'gitlab-ci-local in gitlab-ci-local' case is also kind of an edge case.

What do you think of having a flag `--single-network` or something, which simply doesn't create multiple networks?

**Comment by firecow** [comment]
As long as it's non default i would be fine with it 👍

**Comment by firecow** [comment]
https://github.com/firecow/gitlab-ci-local/issues/991 I'm solving this issue in the next version of gitlab-ci-local.

Is that enought to get you past this use-case? @alexander-matthiesen

**Comment by firecow** [comment]
Feel free to reopen, if this still needs work to cater your use-case.
