### ISSUE TITLE
Support `.gitlab/gitlab-ci.yml` location

### ISSUE THREAD

**Issue by crubier** [firecow/gitlab-ci-local#74]
Gitlab allows to store the CI config at `.gitlab/gitlab-ci.yml`

But in this case:

- Running `gitlab-ci-local` in the root folder of my repo returns `. does not contain .gitlab-ci.yml`
- Running `gitlab-ci-local` in the `.gitlab` folder returns `Could not locate.gitconfig or .git/config file`

**Comment by firecow** [comment]
My test project is not picked up by gitlab 
![image](https://user-images.githubusercontent.com/973602/109963838-27196080-7ced-11eb-81a3-488273d64851.png)

Have you by any chance, told gitlab to look for the file in there ?

**Comment by firecow** [comment]
![image](https://user-images.githubusercontent.com/973602/109963971-57f99580-7ced-11eb-9739-f9184670adbf.png)

I think you have...

![image](https://user-images.githubusercontent.com/973602/109964174-998a4080-7ced-11eb-96ea-942995be2d87.png)

I think this, is what you actually want.

**Comment by firecow** [comment]
@crubier Any input on this ?

**Comment by crubier** [comment]
Indeed I think you are right 👍  I will try it

**Comment by firecow** [comment]
https://github.com/firecow/gitlab-ci-local/pull/84 @crubier 
Would this suffice, or do you need absolute paths to work as well ?

**Comment by firecow** [comment]
Its been merged to master, closing...
