### ISSUE TITLE
Add support for dind - docker in docker - using priviliged mode

### ISSUE THREAD

**Issue by synergiator** [firecow/gitlab-ci-local#75]
Currently, the simulated job has as it seems a hard-coded [`docker run`](https://github.com/firecow/gitlab-ci-local/blob/d9ece526414629a6ebc06440e6a7dc1426c48e94/src/job.ts#L304) statement.

For a "dind" (docker in docker) type of job where you build images and run containers, you need the [`--privileged`](https://docs.docker.com/engine/reference/run/) flag. Would be great to have an option for that!

**Comment by firecow** [comment]
Can you provide an as small as possible .gitlab-ci.yml I can use as test case? @synergiator

**Comment by firecow** [comment]
And wouldn't it make sense, to let "privileged" be default, and have people opt out via an local only rc file and "--no-priviliged" option?

**Comment by synergiator** [comment]
hi there - I'd say that leaving non-privileged as default is in terms of security a more careful choice, given that you have chances to pickup Docker images with evil code, they would be able to do anything with you environment in the scope of your user permissions.

Sample job ([from here](https://docs.gitlab.com/runner/executors/docker.html)):

```
image: docker:git
services:
- docker:dind

build:
  script:
  - docker build -t my-image .
  - docker push my-image

```
Or, without ```services```, just use the docker:dind image.

**Comment by firecow** [comment]
`services` ain't supported yet.
Lets make the the tool able to understand --priviligied and/or read option from a .gcl file

**Comment by firecow** [comment]
https://github.com/firecow/gitlab-ci-local/pull/82 Added privileged option.
Also GCL_* environment vars are now used if specified.

**Comment by firecow** [comment]
#82 is is master, closing

**Comment by bcouetil** [comment]
Wonderful tool :smile: 

@firecow would you mind provide an example of a job that would work ? I did not find any way even with the dummiest job...

**Comment by firecow** [comment]
@bcouetil I'm not sure I know a use case, where you would only use privileged mode.
What we need is the `services:` field implemented, that way a docker build routine could be implemented purely in docker-executor mode.

**Comment by bcouetil** [comment]
Thanks. If and when my main blockers are resolved (I created some new feature requests), I'll replace Docker with Kaniko as a workaround :smile:

**Comment by bcouetil** [comment]
@firecow @synergiator I managed to build images using Img : https://github.com/genuinetools/img

Same commands as Docker, but no service required. It still needs `--priviledged`, don't know why, but it works :tada:
