### ISSUE TITLE
Document how to run inside a docker container

### ISSUE THREAD

**Issue by udalrich** [firecow/gitlab-ci-local#753]
**Is your feature request related to a problem? Please describe.**
I am trying to use the project inside a docker container and having trouble getting it to work.

**Describe the solution you'd like**

I would like to do something like

```
docker run --rm -it -v $(pwd):/work -w /work firecow/gitlab-ci-local
gitlab-ci-local build
<output from running build job>
```

**Describe alternatives you've considered**

I tried using firecow/gitlab-ci-local-utils but that does not have GCL or npm installed.
`*/gitlab-ci-local` does not seem to exist

My best attempt thus far is

```
$ docker run --rm -it -v $(pwd):/work -w /work node:latest bash
$ apt-get update && apt-get install rsync
$ npm install gitlab-local-ci
$ gitlab-ci-local --list
<lists jobs as expected>
$ gitlab-ci-local style # style is a job in my .gitlab-ci.yml
Using fallback git user.name
Using fallback git user.email
parsing and downloads finished in 128 ms
style               starting python:3.11 (build)
Error: Command failed with ENOENT: docker volume create gcl-style-16608-tmp
spawn docker ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

The style job is 

```
style:
  image: python:3.11
  stage: build
  tags:
    - docker
  before_script:
    - python -m pip install pre-commit
  script:
    - pre-commit run --all-files

```

which attempts to run the job in a docker container.

I am guessing that I need to do some further setup to be able to run docker in docker, but I know that is complicated.

**Additional context**

**Comment by firecow** [comment]
You need bash >= 4 and docker cli with a daemon (aka docker-in-docker) or volume mount /var/run/docker.sock
