### ISSUE TITLE
on version "< 3" when an unknown template is included via "extends:" in a job, gitlabci-local crash on parsing the file

### ISSUE THREAD

**Issue by Psycojoker** [firecow/gitlab-ci-local#760]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---                          
include:                     
  - project: "orga/project"  
    ref: "main"              
    file:                    
      - "templates/stuff.yml"

stages:
  - tests         
              
some_job:           
  stage: tests         
  extends: .some_template    
  script: some_script        
```

**Expected behavior**
gitlabci-local should at least run but it crashes with:

```
Traceback (most recent call last):
  File "/tmp/rgrg/ve3/bin/gitlabci-local", line 8, in <module>
    sys.exit(main())
  File "/tmp/rgrg/ve3/lib/python3.7/site-packages/gitlabci_local/cli/main.py", line 298, in main
    result = MenusFeature(jobs=jobs, options=options).select()
  File "/tmp/rgrg/ve3/lib/python3.7/site-packages/gitlabci_local/features/menus.py", line 338, in select
    use_jk_keys=True,
  File "/tmp/rgrg/ve3/lib/python3.7/site-packages/questionary/prompts/checkbox.py", line 120, in checkbox
    choices, default, pointer=pointer, initial_choice=initial_choice
  File "/tmp/rgrg/ve3/lib/python3.7/site-packages/questionary/prompts/common.py", line 250, in __init__
    if not self.is_selection_valid():
  File "/tmp/rgrg/ve3/lib/python3.7/site-packages/questionary/prompts/common.py", line 421, in is_selection_valid
    return not self.is_selection_disabled() and not self.is_selection_a_separator()
  File "/tmp/rgrg/ve3/lib/python3.7/site-packages/questionary/prompts/common.py", line 418, in is_selection_disabled
    return self.choices[self.pointed_at].disabled
AttributeError: 'InquirerControl' object has no attribute 'pointed_at'
```

If you remove the line:
```
  extends: .some_template
```

You don't have this crash anymore. This is a template provided by the `include` (but removing the whole include block also produce the crash)

**Host information**
fresh install in a virtualenv, here is the output of pip freeze:

```
certifi==2022.12.7
charset-normalizer==3.0.1
colored==1.4.4
docker==6.0.1
gitlabci-local==6.0.0
idna==3.4
packaging==23.0
prompt-toolkit==3.0.37
python-dotenv==0.21.1
PyYAML==6.0
questionary==1.10.0
requests==2.28.2
update-checker==0.18.0
urllib3==1.26.14
wcwidth==0.2.6
websocket-client==1.5.1
```

Python version:

```
❯ python --version
Python 3.7.7
```

Distribution is Ubuntu LTS jammy

**Additional context**

I had to get back to "gitlabci-local" version 3.1.2 (<4) to not have this crash anymore. This version is able to detect an unknown include.

Anyway, thanks a lot for this software, it's great :heart:

**Comment by firecow** [comment]
## Missing includes reports proper error message.
`gitlab-ci-local` output
![image](https://user-images.githubusercontent.com/973602/220940578-f8bf8f99-02b9-4643-94e8-44b1da9a2857.png)

`gitlab` output
![image](https://user-images.githubusercontent.com/973602/220940728-854172ba-1ece-4d71-a80b-0211d559558b.png)



## Missing extends reports proper error message.
`gitlab-ci-local` output
![image](https://user-images.githubusercontent.com/973602/220940945-496d08fc-10c3-4667-a147-ca3e51990fad.png)

`gitlab` output 
![image](https://user-images.githubusercontent.com/973602/220941106-f83c8ed9-2bc1-4f7b-9d8f-c3ccbee568ec.png)


You should consider switching to `gitlab-ci-local` over `gitlabci_local` if you want proper error messages :smile:
