### ISSUE TITLE
Share specs for build environment dependencies - a Dockerfile?

### ISSUE THREAD

**Issue by synergiator** [firecow/gitlab-ci-local#77]
I've tried to build master and 4.9.0 and after that I get runtime errors. (nodeJS v10.19.0)

For 4.9.0 ```npm start``` outputs:
```
SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/user/github/gitlab-ci-local/src/yargs.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/home/user/github/gitlab-ci-local/node_modules/ts-node/src/index.ts:1056:23)
```

**Comment by firecow** [comment]
https://github.com/firecow/gitlab-ci-local/blob/d9ece526414629a6ebc06440e6a7dc1426c48e94/package.json#L57

**Comment by firecow** [comment]
In what way would Dockerfile help us?

**Comment by synergiator** [comment]
yes, I could build it inside a container in isolated way.

**Comment by firecow** [comment]
How would such a "workflow" look more precisely?
```
docker build . -t whatnot
ID=$(docker run -d whatnot)
docker cp ${ID}:bin/ bin
```
Something like this?

**Comment by synergiator** [comment]
exactly - build the image, run the container, get the binary.

**Comment by firecow** [comment]
https://github.com/firecow/gitlab-ci-local/blob/master/docker-npm

`./docker-npm install`
`./docker-npm prepublishOnly`
etc. etc.


Will this suffice ?

**Comment by firecow** [comment]
@synergiator Ping :smile:

**Comment by synergiator** [comment]
thank you for providing this tooling: will try and share results

**Comment by synergiator** [comment]
So it gets stuck at this step:

```
./docker-npm run prepublishOnly

> gitlab-ci-local@4.9.9 prepublishOnly
> npm run check-all && chmod +x src/index.js


> gitlab-ci-local@4.9.9 check-all
> npm run build && npm run lint && npm run ncu && npm run coverage && npm run audit


> gitlab-ci-local@4.9.9 build
> rm -f src/*.js src/*.d.ts && tsc


> gitlab-ci-local@4.9.9 lint
> npx eslint .


> gitlab-ci-local@4.9.9 ncu
> ncu --target latest -e 2

Checking /app/package.json
[====================] 30/30 100%

 ts-jest     ^26.5.2  →  ^26.5.3     
 typescript   ^4.2.2  →   ^4.2.3     

Run ncu -u to upgrade package.json

Dependencies not up-to-date
```
What I a trying to achieve:
* clone the repo
* hack ```--privileged``` into the place it belongs to for to suit my current purposes
* build the binary :-)

**Comment by firecow** [comment]
Oh, right I've made prepublishOnly break if there are new npm packages

**Comment by firecow** [comment]
Running ./docker-npm pkg-linux will still build the binary though

**Comment by firecow** [comment]
The --priviliged MR is incoming soon btw...

**Comment by firecow** [comment]
I use ts-node during development, that way I don't have to build binaries all the time.

**Comment by firecow** [comment]
https://github.com/firecow/gitlab-ci-local/blob/master/ts-node @synergiator 
You need npm install locally to use it though
```
./ts-node --cwd examples/docker-compose-nodejs
```

**Comment by firecow** [comment]
I'm closing this. 
Been using ./docker-npm myself, during development, and it works as expected.
