### ISSUE TITLE
Debian PPA URL returns http 404

### ISSUE THREAD

**Issue by felsgaertner** [firecow/gitlab-ci-local#773]
I am trying to install on Debian using the deb ppa sources.

[gitlab-ci-local.list](https://github.com/firecow/gitlab-ci-local/blob/752c2f2aa6d31e8e0eda7cf86dbb443e4f2a449a/ppa/gitlab-ci-local.list#L1) mentions https://firecow.github.io/gitlab-ci-local/ppa/ - this URL returns http error 404.

**Comment by firecow** [comment]
Well, thats correct, no index.html file in that location.

You have to provide more information.
