### ISSUE TITLE
How to populate runner variables like CI_COMMIT_REF_SLUG with useful value?!

### ISSUE THREAD

**Issue by typoworx-de** [firecow/gitlab-ci-local#779]
I'm testing gitlab.com workflow locally with gitlab-ci-local. The gitlab-ci.yml uses f.e. CI_COMMIT_REF_SLUG which later will be used to tag the image which will be pushed to my local running docker registry for testing purposes.

Currently it would only be possible to set a fixed value to CI_COMMIT_REF_SLUG. It would be great to fill it with a build-count or something to have an altering value.

**Comment by typoworx-de** [comment]
May be some kind of interaction hook or script that can modify/inject such values per run would be nice to have? The gitlab-ci-local is typescript and nodejs right?

**Comment by bcouetil** [comment]
Hello :) 

CI_COMMIT_REF_SLUG is the branch on which you are. If you run another pipeline on the same branch, even on gitlab.com, you would have the same value.

What you want is a changing CI_COMMIT_REF_SLUG for tests.

you may use `$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID` when you are in local (when `$GITLAB_CI = "false"`)

or maybe override CI_COMMIT_REF_SLUG in the your local variable file, but I don't know if setting this works :

`CI_COMMIT_REF_SLUG=$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID`

**Comment by firecow** [comment]
```
---
test-job:
  script:
    - echo "$CI_COMMIT_REF_SLUG"
```

```
gitlab-ci-local --variable CI_COMMIT_REF_SLUG=myman
```
Do this solve you use-case @typoworx-de ?

**Comment by firecow** [comment]
https://github.com/firecow/gitlab-ci-local/pull/782 When this PR is in master, you are able to do this. @typoworx-de 

```
gitlab-ci-local --variable CI_COMMIT_REF_SLUG='$CI_JOB_ID'
```

**Comment by typoworx-de** [comment]
Thanks for your quick help @firecow I somehow made it working by simply adding this ```CI_COMMIT_REF_SLUG: local-build``` to .gitlab-ci-local-variables.yml and in the meantime after updating to more recent version it works.

I'll never the less check your approach if it may be more useful. Some kind of nodejs "hooks" written in nodejs still may be an interesting "plugin/hook" like feature for the future and some edge-cases where dev's need to adjust things when gitlab-ci-local has been started (without scripting around).
