### ISSUE TITLE
Unusual attraction of this project over the past few weeks

### ISSUE THREAD

**Issue by bcouetil** [firecow/gitlab-ci-local#781]
I want to report an unusual, but steady, attraction of this project over the past few weeks... did Elon Musk talked about it or something ? 😁 

Well deserved recognition 👏

And congratulations for the 1000 ⭐️ 🎉 

[![Star History Chart](https://api.star-history.com/svg?repos=firecow/gitlab-ci-local&type=Date)](https://star-history.com/#firecow/gitlab-ci-local&Date)

**Comment by firecow** [comment]
Thanks 🤟
I have no clue what happened, someone must have tweeted something.

**Comment by bcouetil** [comment]
In fact, GCL is becoming the de-facto standard for local GitLab pipelines, it is recommended everywhere on official issues 💪 : https://gitlab.com/gitlab-org/gitlab-runner/-/issues/2797#note_1309430596

**Comment by bcouetil** [comment]
I wrote an article that advertises GCL ✌️ https://dev.to/zenika/gitlab-ci-yaml-modifications-tackling-the-feedback-loop-problem-4ib1

And at Zenika when giving trainings we speak about it everytime 😁

Keep up the good work my friend 😉

**Comment by firecow** [comment]
Very nice 😁 Thank you...
