### ISSUE TITLE
Artifacts do not work: no artifacts copied

### ISSUE THREAD

**Issue by typoworx-de** [firecow/gitlab-ci-local#788]
**Minimal .gitlab-ci.yml illustrating the issue**
See my [gist](https://gist.github.com/typoworx-de/cc8bcd648d0112471ca16aac4e66f9dd) including the .gitlab-ci.yml and Dockerfile test for simple artifact

**Expected behavior**
I've created a Dockerfile that does:
```
RUN \
  echo "Test" > /build/my-artifact.txt 
```

The test-artifact is present building an image and opening a shell. Why is it not exported as instructed in gitlab-ci.yml using artifacts?

**Host information**
Ubuntu
gitlab-ci-local 4.39.0

**Comment by bcouetil** [comment]
GitLab can only set, as artifacts, paths that are in current directory.

You put an absolute directory in `artifacts:paths`

On top of that, you create the file in an image produced by the job, without mounting anything, how can the job access this file ?

**Comment by firecow** [comment]
@typoworx-de Please provide a link or screenshot of this actually working in regular Gitlab CI/CD 👍

**Comment by typoworx-de** [comment]
@bcouetil thanks for the hint. Just for understanding about paths in ```artifacts:paths``` will this have to be relative to docker WORKDIR directive? I'm compiling PHP docker-image with final app in "/app". The default WORKDIR should be /var/www at least in the final rc image (but eventually I could test against an earlier stage doing the artifacts).

Thanks for helping to understand that.

**Comment by bcouetil** [comment]
> Uhm okay I think I understand now... artifacts are not ment to extract from the docker root, but the workdir of gitlab-ci scripts, is that correct?

Yes.

> I'll would have to execute docker cp then to extract something from build-stage image first is that the correct way to solve such use-case?

Docker cp is for containers, not images.

I would use that instead for images :

```
    - docker create --name="tmp_$$" $MY_IMAGE
    - docker export tmp_$$ | tar t
```

**Comment by typoworx-de** [comment]
@bcouetil you're absolutely right about docker cp. wrong context there.

But thanks for pointing me in the right direction. I'll think docker export is somehow overhead if one just wants a small piece of it. What do you think about this hack?

```Dockerfile.artifact-extractor
# syntax = docker/dockerfile:1.4.0
ARG ARTIFACT_IMAGE
FROM $ARTIFACT_IMAGE AS artifact-source

FROM busybox
ARG ARTIFACT_IMAGE
ARG ARTIFACT_SOURCE

WORKDIR /artifacts

COPY --from=artifact-source $ARTIFACT_SOURCE /artifacts
```

and in gitlab-ci script:
```
- docker run --rm -it -v $(pwd)/artifacts:/export $(docker build -q -f Dockerfile.artifact-extractor --build-arg ARTIFACT_IMAGE="$IMAGE_TAG" --build-arg ARTIFACT_SOURCE="/build/*" . 2> /dev/null) sh -c 'cp -R /artifacts/* /export/'
```

works as far as I tested and I think it's much less overhead than exporting whole docker image?!

**Comment by bcouetil** [comment]
If it works, it's OK I guess.

I'm not confident with the whole process : you have a shell runner that pops a docker image and get a file from it.

Nowadays, everyone is using docker runners directly.

**Comment by typoworx-de** [comment]
@bcouetil thanks for the help. It works I just had to remove '-it' to make it non-interactive as using it like above in the pipeline caused ```the input device is not a TTY``` while using docker run with ```-it``` (interactive mode)

**Comment by firecow** [comment]
```
build:
  variables:
    CONTAINER_ID: $CI_JOB_ID
  artifacts:
    paths: [builds]
  script:
    - docker build . -t imagename
    - docker create --name $CONTAINER_ID imagename
    - mkdir -p builds/
    - docker copy $CONTAINER_ID:/var/www/html builds
  after_script:
    - docker rm -f $CONTAINER_ID
```
