### ISSUE TITLE
Connecting to Docker volume where the build happened

### ISSUE THREAD

**Issue by saheerb** [firecow/gitlab-ci-local#790]
**Is your feature request related to a problem? Please describe.**
This is more like a question than feature request. I couldn't find this in the documentation. Apologies if this is already mentioned somewhere.

I use docker executer exclusively for my project. Normally my work flow is:
* Clone to my PC (Mac)
* use `.gitlab-ci-local` for testing
* Make changes in PC.

My questions:
* Does `.gitlab-ci-local` uses new docker volume everytime? Is it possible to reuse?
* I can see some docker containers of `firecow/gitlab-ci-local-util` running when using `docker ps -a`. What are those?
* Is it possible to know which docker volume is used for which build?
* Is it possible to "connect" (exec) to a docker container after the build?
* How is the source in "host" copied to Docker container?

**Comment by firecow** [comment]
Make sure you have a "clean" docker env, by calling `docker system prune --all --volumes --force` 
```
gitlab-ci-local --no-cleanup
```
Call `docker volume ls` and `docker container ls`, and notice how GCL haven't cleanup after itself.

**Comment by saheerb** [comment]
I understand there is an option to cleanup. What I was asking is, how the source in host is copied to docker volume? And is it possible to reuse once built?

Our build takes a good 15 minutes, and will help in great deal if rerun reuses existing volume/workspace.

**Comment by saheerb** [comment]
sorry I might have types too fast. I will try with `--no-cleanup`

**Comment by bcouetil** [comment]
Hello 👋

Don't forget also that you could leverage GitLab cache, which is implemented. It can be fast, especially with --mount-cache option.
