### ISSUE TITLE
Change CI_PROJECT_NAME to folder name instead of local-project

### ISSUE THREAD

**Issue by moberghammer** [firecow/gitlab-ci-local#81]
As specified in https://docs.gitlab.com/ee/ci/variables/predefined_variables.html

CI_PROJECT_NAME The name of the directory for the project. For example if the project URL is gitlab.example.com/group-name/project-1, CI_PROJECT_NAME is project-1.

It makes sense to use the folder containing the checkout when running gitlab-ci-local

**Comment by firecow** [comment]
I will parse as many as possible from `git remote -v` and use values from that URL

**Comment by firecow** [comment]
https://github.com/firecow/gitlab-ci-local/pull/86
BOOM BABY @moberghammer
