### ISSUE TITLE
gitlab-ci-local-util Docker is outdated and doesn't support linux/arm64

### ISSUE THREAD

**Issue by clementperon** [firecow/gitlab-ci-local#811]
Hi,

I'm trying to run gitlab-ci-local on MacOS apple silicon machine.

My docker images are compatible with linux/arm64 and I set my env like this:
export DOCKER_DEFAULT_PLATFORM=linux/arm64

Unfortunately the gitlab-ci-local-utils doesn't support it and seems a bit Outdated is it possible to rebuild with multiple arch support ?
https://hub.docker.com/r/firecow/gitlab-ci-local-util/tags

I can provide a script to do so if needed

**Comment by firecow** [comment]
I will make a fix 👍

**Comment by firecow** [comment]
![image](https://user-images.githubusercontent.com/973602/230780949-9c2778e1-2738-4e5e-a468-b933cb54c6dc.png)

All done

**Comment by clementperon** [comment]
Thank you <3

**Comment by firecow** [comment]
> Thank you !

Is it working as it should?

**Comment by clementperon** [comment]
I will be able to test that on Tuesday, will let you know !

**Comment by clementperon** [comment]
@firecow yep it works 👍
