### ISSUE TITLE
Display docker logs in case of direct error

### ISSUE THREAD

**Issue by ecourreges-orange** [firecow/gitlab-ci-local#856]
**Is your feature request related to a problem? Please describe.**
It took me a bit of time to figure out if I could display logs of the first steps in gitlab-ci-local and couldn't find any verbose toggle or anything.  
The FAIL here does not help much. My problem was a bad credential on the docker pull.

```shell
$ gitlab-ci-local 
parsing and downloads finished in 125 ms
bla                              starting xxx.xxx.net/helm/helm:v3.7.1-r1 (bla)
bla                              copied to docker volumes in 985 ms

 FAIL  bla                             
pipeline finished in 1.93 s
$ docker run --rm xxx.xxx.net/helm/helm:v3.7.1-r1
Unable to find image 'xxx.xxx.net/helm/helm:v3.7.1-r1' locally
docker: Error response from daemon: Head "https://xxx.xxx.net/v2/helm/manifests/v3.7.1-r1": unknown: Bad credentials.
See 'docker run --help'.
``` 

**Describe the solution you'd like**
Display the docker logs in this case of failure to save the user some debug time.  
The `copied to docker volumes` is also misleading as the failed part is the "starting image (job)"

Thanks

**Comment by firecow** [comment]
Thought I've already made this. But apparently i haven't. Coming right up.

**Comment by firecow** [comment]
sudo apt-get install gitlab-ci-local=4.38.1
```
Error: Command failed with exit code 1: docker pull alpino:latest
Error response from daemon: pull access denied for alpino, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
This is a bug regression introduced in 4.39.0.
