### ISSUE TITLE
validate that `tags:` value is in fact an array of strings

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#859]
**Is your feature request related to a problem? Please describe.**
I hate seeing this on gitlab.com
![image](https://github.com/firecow/gitlab-ci-local/assets/973602/ef39835e-0d18-4026-8283-e15f28233663)

**Describe the solution you'd like**
Verify that `tags:` value is in fact an array of strings

**Comment by ANGkeith** [comment]
I am hoping to use ajv to validate the loaded gitlab-ci.yml against the json-schema

are you open to the idea?

**Comment by ANGkeith** [comment]
>  if .gitlab-ci.yml was validated into well defined typescript types/interfaces.

i am not too sure how the above can be done though
