### ISSUE TITLE
View Docker job log

### ISSUE THREAD

**Issue by Time0o** [firecow/gitlab-ci-local#876]
This is a very basic question, likely I don't understand how to use this tool correctly, but when I simply execute `gitlab-ci-local MY_JOB` I get the following output:

```
parsing and downloads finished in 57 ms
MY_JOB         MY_CONTAINER (test)
MY_JOB         copied to docker volumes in 1.08 s
MY_JOB         finished in 1.12 s

PASS  MY_JOB
```

This job should take at least several minutes to run successfully so something is wrong here. But how can I find out what? Is the output of whatever is run in the started Docker image stored somewhere? Or can I attach to it before the job starts? This is not clear to me from the README or the `--help` output.

**Comment by firecow** [comment]
We need an as simple as possible `.gitlab-ci.yml` illustrating your issue.

Preferably paste a simplified version of your `$CWD/.gitlab-ci-local-env` and `$HOME/.gitlab-ci-local-env`  as well.

That's usually how we resolve most issue.

Reopen, when you provided this information.
