### ISSUE TITLE
allow configuration of "containerd" executable

### ISSUE THREAD

**Issue by nolange** [firecow/gitlab-ci-local#922]
**Is your feature request related to a problem? Please describe.**
I am using podman, which features a mostly compatible CLI for docker commands.
It would be great if I could use this setup automatically

**Describe the solution you'd like**

I would like this tool to test both `podman` and `docker` and use the
tool that was found (and don't even try to launch anything if nothing was found).

Allowing the tool path to be used would be another option

**Describe alternatives you've considered**

Well, a simple shell-script wrapper works of course.

**Comment by firecow** [comment]
A more detailed description of how this feature is supposed to be implemented is needed or the title needs to change.

I'm reading this as we need to run unit and integration tests with podman as well.

I'm closing for now, feel free to reopen, if you can clarify what you actually want.

**Comment by nolange** [comment]
1.  add an argument `--docker-cmd` which takes a path to an executable understanding the docker command-line
2.  if not set, use `docker` as default.
3.  Modify all hard-coded occurrences like `Utils.spawn(["docker",` to use the configured path via variable.

And as further improvement:
2b. Test executing `podman --version`, if successful use `podman` as default, else use `docker`

Whether tests for this are required is dependent on the developing guidelines of your project?

**Comment by firecow** [comment]
But isn't podman installing a symlink in /usr/local/bin/docker

**Comment by ebousse** [comment]
True, it's often possible with an additional package − for instance `podman-docker`, in Fedora, sets up such a symlink.

However in my case I have two environments where this is not possible:
- one where the users are forced to type `podman` instead of `docker` so that there is no ambiguity that podman is the actual tool being used,
- one where both podman and docker are installed, with docker being used only for a few cases where podman does not work, and where podman should be used for all others.

But I suppose these cases are not very common, and I would understand that `gitlab-ci-local` prefers not to support them. I simply add my story here in case :)

**Comment by ebousse** [comment]
That being said, I'm trying gitlab-ci-local with the symlink in a custom environment, and I get a `FAIL` with no message right after ` copied to docker volumes`… I suppose more work is required gitlab-ci-local side than simply supporting another executable path.

**Comment by firecow** [comment]
I would very much like gitlab-ci-local to support podman.

Adding a `--containerd-binary   [docker or podman]` cli option would make sense, but not before all the podman issues have been resolved. And right now I can't find a single issue surrounding gitlab-ci-local podman is not working, so please feel free to open issues about what doesn't work when using podman.

I'm currently working on this issue https://github.com/firecow/gitlab-ci-local/issues/964 hopefully we will be able to understand what needs change, when we can see an actual error message :laughing:

**Comment by firecow** [comment]
Now that I think about it. Adding a --containerd-binary would make sense to just do, it would make it easier to get to the bottom of these podman issues for developers that got environments with both docker and podman. I'm reopening this, and will try to add said cli option in next release.

**Comment by ebousse** [comment]
> I would very much like gitlab-ci-local to support podman.

Very glad to read this! Good luck with this endeavor!

> And right now I can't find a single issue surrounding gitlab-ci-local with podman is not working, so please feel free to open such issues.

I would be happy to open an issue with my current error, however is there a way to gather more logs from gitlab-ci-local? It's not very verbose in case I encounter unfortunately.

I'll try preparing a reproducible example though.

> Now that I think about it. Adding a --containerd-binary option would make sense to add, it would make it easier to get to the bottom of these podman issues for developers that got environments with both docker and podman.
I'm reopening this, and will try to add said cli option in next release.

Awesome, looking forward to it :+1:

**Comment by firecow** [comment]
@ebousse It's not supposed to be silent about errors, in fact it's supposed to log stack traces and everything, when something isn't work, see examples in https://github.com/firecow/gitlab-ci-local/issues/964

We must solve the FAIL without errors problem first, before you or anyone else with podman will be able to report any issues.

**Comment by firecow** [comment]
Just removed docker and installed podman https://github.com/firecow/gitlab-ci-local/issues/964#issuecomment-1698820620
I'm not seeing the early FAIL without error output.

**Comment by ebousse** [comment]
> @ebousse It's not supposed to be silent about errors, in fact it's supposed to log stack traces and everything, when something isn't working, see examples in https://github.com/firecow/gitlab-ci-local/issues/964

Indeed, you are correct − I forgot to upgrade gitlab-ci-local to the latest version, which now does log stack traces nicely.

> We must solve the FAIL without errors problem first, before you or anyone else with podman will be able to report any issues.

Opened an issue here: https://github.com/firecow/gitlab-ci-local/issues/922

**Comment by firecow** [comment]
```
> Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
```

**Comment by nolange** [comment]
> That being said, I'm trying gitlab-ci-local with the symlink in a custom environment, and I get a `FAIL` with no message right after `copied to docker volumes`… I suppose that for podman to work, more work is required gitlab-ci-local side than simply supporting another executable path.

Symlinks can be unreliable, this is what I use:

``` bash
#!/bin/sh
exec /usr/bin/podman "$@"
```

works fine for me

**Comment by firecow** [comment]
I'll add a `--container-executable` to next gitlab-ci-local version, then developers can chose whatever they want  :+1:

**Comment by firecow** [comment]
> > @ebousse It's not supposed to be silent about errors, in fact it's supposed to log stack traces and everything, when something isn't working, see examples in #964
> 
> Indeed, you are correct − I forgot to upgrade gitlab-ci-local to the latest version, which now does log stack traces nicely.
> 
> > We must solve the FAIL without errors problem first, before you or anyone else with podman will be able to report any issues.
> 
> Opened an issue here: #922

Your link is incorrect.

**Comment by ebousse** [comment]
> > Opened an issue here: #922
> 
> Your link is incorrect. @ebousse

Apologies, it was https://github.com/firecow/gitlab-ci-local/issues/975, which you already fixed :)
