### ISSUE TITLE
Add no-artifacts-to-source to help

### ISSUE THREAD

**Issue by naweiss** [firecow/gitlab-ci-local#924]
One of command line options of gitlab-ci-local is `--artifacts-to-source` which hints that gitlab-ci-local does not copy the artifacts to the source directory by default which is not true. also, from looking into the output of `--help` it is unclear how to disable this option.
I accidently discovered that it can be disabled by `--no-artifacts-to-source` after looking at the README of this repo. But, I don't think this is a good way to document this option. A batter way would be to add it to the output of `--help`.

**other alternatives**
1. Making this option false by default which will make more sense
2. Add a message to help clearifaying you can add a **no** prefix to boolean options

**Comment by firecow** [comment]
If we decide to add `--no-artifacts-to-source` to the help section.

We need to go through the rest of the "booleanlike" arguments and decide what makes sense to output for those.

I'm labeling this nice-to-have.

**Comment by naweiss** [comment]
There are three main issues in `yargs` addressing the issue mentioned above:

- https://github.com/yargs/yargs/issues/1116
- https://github.com/yargs/yargs/issues/2305
- https://github.com/yargs/yargs/issues/322

The suggested solutions are:

1. Adding `boolean-negation": false` to disable the `no` prefix and then defining you own `no` options explicitly when needed:
```
.option("artifacts-to-source", {
    type: "boolean",
    description: "Copy the generated artifacts into cwd",
    requiresArg: false,
})
.option("no-artifacts-to-source", {
    type: "boolean",
    description: "Do not copy the generated artifacts into cwd",
    requiresArg: false,
})
```
The help will show:
```
  --artifacts-to-source  Copy the generated artifacts into cwd [boolean]
  --no-artifacts-to-source  Do not copy the generated artifacts into cwd [boolean]
```
3. Showing only the `no` option since by default it is `true`, and manually hiding the true option:
```
.option("artifacts-to-source", {
    type: "boolean",
    hidden: true,
    requiresArg: false,
})
.option("no-artifacts-to-source", {
    type: "boolean",
    description: "Do not copy the generated artifacts into cwd",
    requiresArg: false,
})
```
The help will show:
```
  --no-artifacts-to-source  Do not copy the generated artifacts into cwd [boolean]
```
This also have the side effects of allowing `--no-no-artifacts-to-source` unless `boolean-negation": false` is defined.
4. Showing both by using an `alias` and explicitly defining the default value so it will be shown in `--help`:
```
.option("artifacts-to-source", {
    type: "boolean",
    description: "Copy the generated artifacts into cwd",
    default: true,
    alias: "no-artifacts-to-source",
    requiresArg: false,
})
```
The help will show:
```
  --artifacts-to-source, --no-artifacts-to-source  Copy the generated artifacts into cwd [boolean] [default: true]
```

I personally think that the third options looks visually the best. But, it might be confusing to anyone who reads the source code.

I would happily open a PR once we decide what option to go for.

**Comment by firecow** [comment]
@naweiss If we "just" add defaults to all cli options, I think 98% would be able to understand what will happen, and how to manipulate the option.
Adding both `--needs` and `--no-needs` to help section is a bit excessive in my opinion.

**Comment by naweiss** [comment]
I agree. But maybe we should have a general help comment that boolean options can be disabled via a no prefix. Since it is not trivial

**Comment by firecow** [comment]
"All flags can be negated with '--no-<flag>' or something like that.
