### ISSUE TITLE
docker-executor jobs shouldn't always run as root:root

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#990]
`USER` set in `Dockerfile` should be used.

Right now `docker create` has `-u 0:0` hardcoded, it shouldn't.

I've verified that gitlab.com runners actually use the linux user specified in `Dockerfile`

![image](https://github.com/firecow/gitlab-ci-local/assets/973602/113e6cee-7de4-43a1-9ac6-ae42e1e60965)

**Comment by benedikt-bartscher** [comment]
Did you try `gitlab-ci-local --umask=false` ?
