### ISSUE TITLE
Ability to specify a Docker network

### ISSUE THREAD

**Issue by maetthew** [firecow/gitlab-ci-local#991]
**Is your feature request related to a problem? Please describe.**
I have a workflow which consists of creating VMWare templates through [Packer](https://www.packer.io) in Gitlab CI. Packer starts a VM and mounts an installation ISO and spins up a webserver on a random port between 8000-9000 where the VM subsequently tries to fetch installation instructions from (e.g a preseed for Debian). When starting with `gitlab-ci-local` it connects to the bridge network and thus gets a 172.x.x.x IP which obviously the VM can't reach.

**Describe the solution you'd like**
Be able to specify a Docker network on which the `gitlab-ci-local` job should be ran.

**Describe alternatives you've considered**
None.

**Additional context**
None but happy to provide anything needed. 

I would like to add that I'm not 100% sure this is a feature request or a question - but I looked quite thoroughly for this feature and couldn't find anything about it. Or maybe I'm overlooking something completely, I'm quite new to all of this. Apologies in advance if that's the case.

**Comment by firecow** [comment]
Can you reference how you get a real runner to attach to a certain docker network?

I'm sure this option will be easy to add.

**Comment by maetthew** [comment]
You can configure `network_mode` for the Docker executor as per: https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-runnersdocker-section
