### ISSUE TITLE
feat: possibility to keep artifacts over consecutive runs

### ISSUE THREAD

**Issue by skuethe** [firecow/gitlab-ci-local#999]
**Is your feature request related to a problem? Please describe.**
Currently (as far as I know) artifacts are ALWAYS purged on every run (PR: https://github.com/firecow/gitlab-ci-local/pull/144).
For convenience I would like to re-use artifacts, f.e. when disabling specific (artifact building-) jobs and only execute jobs which rely on artifacts. This is currently not working.
An example would be:
job1: builds something (container image f.e.) and adds it as an artifact
job2: downloads artifact and scans it for vulnerabilities

If you then set a variable to skip "job1" (enforced by a `job1.rules[].if` statement) before a second pipeline execution, job2 would fail because of the missing artifact.
I am aware that, in this example, the scan result only change when we actually change / re-run the build job, but just ignore that for now ;)

**Describe the solution you'd like**
I guess there are two possibilities I can think of:
- add a CLI flag to skip purging of artifacts
- respect `[jobName].artifacts.expire_in` flag

That `expire_in` support would, of course, be the perfect addition. But having any possibility to keep the previous artifact would be nice.

**Describe alternatives you've considered**
I am unsure how `--shell-isolation` is playing into workarounds here. I am currently evaluating it with `SHELL_ISOLATION=true`, so that the artifacts are just kept inside the `.gitlab-ci-local/artifacts` folder and not send to the host.

**Additional context**

**Comment by firecow** [comment]
Gitlab reuses artifacts from previous jobs, when retrying single jobs.

```sh
gitlab-ci-local # purges artifacts
gitlab-ci-local test-job --needs # purges artifacts
gitlab-ci-local test-job # reuses artifactes
```

**Comment by skuethe** [comment]
> Gitlab reuses artifacts from previous jobs, when retrying single jobs.
> 
> ```sh
> gitlab-ci-local # purges artifacts
> gitlab-ci-local test-job --needs # purges artifacts
> gitlab-ci-local test-job # reuses artifactes
> ```
> 
> Isn't it doable for you to use the current "retry" mechanism?

Thank you for the quick feedback!
I am trying the "retry" mechanism, however I did set "NEEDS" variable to true. So that would explain the purging.

I will try this and remove the forced "needs".

Do you have any thoughts on the `expire_in` option?

Great job on this tool btw! Love it :)

**Comment by firecow** [comment]
Aaaa... You have needs on default, then it makes sense.

`artifacts.expire_in` doesn't affect execution flows on gitlab.com and neither should it in `gitlab-ci-local`, but we need a section in the readme properly explaining when artifacts are "reset", basicly properly explain --needs vs --no-needs.

**Comment by skuethe** [comment]
So, I did some testing:
- removed `NEEDS=true`
- executed `gitlab-ci-local` to create the artifact
- executed `gitlab-ci-local job2`

Results:
The artifact created from the first run was not purged (yay), but it was also not downloaded while running job2.
So job2 failed because the file from the artifact of job1 was not found.

Setup:
I have some other settings defined, which maybe (unknowingly) alter the behaviour of this :
```conf
CLEANUP=true
SHELL_ISOLATION=true
```

Also, "job1" is marked with `@NoArtifactsToSource`, to not copy the artifact into the local folder, but only keep it inside the `.gitlab-ci-local/artifacts` folder.

>
> `artifacts.expire_in` doesn't affect execution flows on gitlab.com and neither should it in `gitlab-ci-local`, but we need a section in the readme properly explaining when artifacts are "reset", basicly properly explain `--needs` vs `--no-needs`
>

My point with this feature request is not to affect the execution flow, but rather the live-cycle of artifacts and when they are being purged.
Hard-binding the artifact-purging to the execution flow logic seems to limits the possible use-cases I feel.

Is there a way to force "job2" to download the still existing artifact of "job1"? 
Adding it to `needs` does not work for me:
```yaml
job2:
  needs: ["job1"]
```

**Comment by firecow** [comment]
It works fine on my machine, ran these commands
```
gitlab-ci-local job2 --shell-isolation --needs
gitlab-ci-local job2 --shell-isolation --no-needs
```


Starting a new pipeline is what `gitlab-ci-local` and `gitlab-ci-local --needs` tries to emulate.
Retrying a job in a existing pipeline is what `gitlab-ci-local --no-needs` tries to emulate.

**Comment by firecow** [comment]
Put what you described here https://github.com/firecow/gitlab-ci-local/issues/999#issuecomment-1770951042 into a minimal `.gitlab-ci.yml` and provide the specific commands needed to illustrate the problem.

I'm closing for now, feel free to reopen.
